// GENERATED by tool/gen_dailies.dart — do not edit by hand.
//
// The daily room pool. Same rejection sampling as the campaign,
// different seeds so a daily is never a level already played,
// and interleaved across hinge counts so difficulty wanders
// rather than ramps. Indexed by date — see lib/daily.dart.
import 'geom.dart';
import 'level.dart';

const dailyLevels = <Level>[
  // day 1  ·  approach 0.152
  Level(
    name: 'day 1',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2948, 0.6288, 0.2476)),
      Box(center: V3(0.0000, 1.0060, 0.0000), half: V3(0.2083, 0.1982, 0.5949)),
    ],
    solution: Pose(0.8450, 0.1271, 0.0000),
  ),
  // day 2  ·  approach 0.056
  Level(
    name: 'day 2',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2626, 0.6284, 0.2368)),
      Box(center: V3(0.0000, -1.0055, 0.0000), half: V3(0.6073, 0.1716, 0.2520), hinged: true),
    ],
    solution: Pose(-1.3820, 0.0819, -0.0629),
  ),
  // day 3  ·  approach 0.028
  Level(
    name: 'day 3',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2160, 0.5043, 0.2413)),
      Box(center: V3(0.0000, -0.8068, 0.0000), half: V3(0.5164, 0.2547, 0.2600), hinged: true),
    ],
    solution: Pose(-2.6442, -0.0438, 0.2446),
  ),
  // day 4  ·  approach 0.116
  Level(
    name: 'day 4',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2012, 0.8720, 0.2742)),
      Box(center: V3(0.0000, 1.3952, 0.0000), half: V3(0.5458, 0.2996, 0.2774)),
    ],
    solution: Pose(-2.3217, 0.6479, 0.0000),
  ),
  // day 5  ·  approach 0.020
  Level(
    name: 'day 5',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2534, 0.5820, 0.2917)),
      Box(center: V3(0.0000, -0.9312, 0.0000), half: V3(0.2485, 0.2508, 0.6363), hinged: true),
    ],
    solution: Pose(-2.4868, -0.8263, -0.5380),
  ),
  // day 6  ·  approach 0.028
  Level(
    name: 'day 6',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2197, 0.5544, 0.2280)),
      Box(center: V3(0.0000, 0.8871, 0.0000), half: V3(0.7823, 0.2940, 0.2378), hinged: true),
    ],
    solution: Pose(-2.7206, 0.0816, -0.1482),
  ),
  // day 7  ·  approach 0.104
  Level(
    name: 'day 7',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2543, 0.8280, 0.2336)),
      Box(center: V3(0.0000, 1.3247, 0.0000), half: V3(0.7527, 0.2191, 0.2231)),
    ],
    solution: Pose(-2.2279, 0.1211, 0.0000),
  ),
  // day 8  ·  approach 0.016
  Level(
    name: 'day 8',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2445, 0.8782, 0.2930)),
      Box(center: V3(0.0000, -1.4051, 0.0000), half: V3(0.7402, 0.2336, 0.2414), hinged: true),
      Box(center: V3(-1.1843, -1.4051, 0.0000), half: V3(0.2681, 0.2431, 0.8051)),
      Box(center: V3(-1.1843, -1.4051, -1.2881), half: V3(0.9287, 0.2341, 0.2398)),
    ],
    solution: Pose(1.2339, 0.0026, 0.1567),
  ),
  // day 9  ·  approach 0.024
  Level(
    name: 'day 9',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2333, 0.6080, 0.2422)),
      Box(center: V3(0.0000, -0.9728, 0.0000), half: V3(0.6878, 0.1840, 0.2261), hinged: true),
    ],
    solution: Pose(-2.6350, 0.1932, -0.3349),
  ),
  // day 10  ·  approach 0.096
  Level(
    name: 'day 10',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2214, 0.7907, 0.2795)),
      Box(center: V3(0.0000, 1.2652, 0.0000), half: V3(0.2808, 0.2359, 0.8060)),
    ],
    solution: Pose(-2.1628, 0.0889, 0.0000),
  ),
  // day 11  ·  approach 0.012
  Level(
    name: 'day 11',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5316, 0.2807, 0.2222)),
      Box(center: V3(0.8505, 0.0000, 0.0000), half: V3(0.2939, 0.7076, 0.2756), hinged: true),
    ],
    solution: Pose(3.1070, -0.5157, 0.6720),
  ),
  // day 12  ·  approach 0.020
  Level(
    name: 'day 12',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2956, 0.8337, 0.2012)),
      Box(center: V3(0.0000, 1.3339, 0.0000), half: V3(0.5043, 0.1682, 0.1951), hinged: true),
    ],
    solution: Pose(-0.4508, 0.0045, -0.4339),
  ),
  // day 13  ·  approach 0.096
  Level(
    name: 'day 13',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2054, 0.6365, 0.2620)),
      Box(center: V3(0.0000, -1.0185, 0.0000), half: V3(0.6331, 0.1933, 0.2316)),
    ],
    solution: Pose(-2.0378, -0.1825, 0.0000),
  ),
  // day 14  ·  approach 0.012
  Level(
    name: 'day 14',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2645, 0.5174, 0.2551)),
      Box(center: V3(0.0000, -0.8278, 0.0000), half: V3(0.2567, 0.2863, 0.9190), hinged: true),
    ],
    solution: Pose(2.9959, 0.0375, 0.2669),
  ),
  // day 15  ·  approach 0.016
  Level(
    name: 'day 15',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2498, 0.5942, 0.2229)),
      Box(center: V3(0.0000, -0.9507, 0.0000), half: V3(0.5496, 0.2550, 0.2953), hinged: true),
    ],
    solution: Pose(-1.9315, -0.7734, -0.2347),
  ),
  // day 16  ·  approach 0.064
  Level(
    name: 'day 16',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2730, 0.6512, 0.2858)),
      Box(center: V3(0.0000, 1.0420, 0.0000), half: V3(0.2729, 0.1716, 0.7907)),
    ],
    solution: Pose(-0.9671, -0.1938, 0.0000),
  ),
  // day 17  ·  approach 0.012
  Level(
    name: 'day 17',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2776, 0.5213, 0.2860)),
      Box(center: V3(0.0000, 0.8340, 0.0000), half: V3(0.5051, 0.1809, 0.1878), hinged: true),
    ],
    solution: Pose(-1.2353, -0.7246, -0.9554),
  ),
  // day 18  ·  approach 0.016
  Level(
    name: 'day 18',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2712, 0.7505, 0.2588)),
      Box(center: V3(0.0000, -1.2008, 0.0000), half: V3(0.2734, 0.2416, 0.7327), hinged: true),
    ],
    solution: Pose(2.1883, 0.4707, 0.5941),
  ),
  // day 19  ·  approach 0.060
  Level(
    name: 'day 19',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2907, 0.6415, 0.2293)),
      Box(center: V3(0.0000, 1.0263, 0.0000), half: V3(0.5139, 0.2080, 0.2006)),
    ],
    solution: Pose(1.1942, -0.9935, 0.0000),
  ),
  // day 20  ·  approach 0.012
  Level(
    name: 'day 20',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2836, 0.5853, 0.1643)),
      Box(center: V3(0.0000, -0.9364, 0.0000), half: V3(0.2287, 0.1625, 0.6044), hinged: true),
    ],
    solution: Pose(-1.5650, 0.0761, 0.4704),
  ),
  // day 21  ·  approach 0.012
  Level(
    name: 'day 21',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2189, 0.5027, 0.2058)),
      Box(center: V3(0.0000, 0.8043, 0.0000), half: V3(0.6138, 0.2697, 0.2278), hinged: true),
    ],
    solution: Pose(-0.6964, -0.1291, 1.1923),
  ),
  // day 22  ·  approach 0.060
  Level(
    name: 'day 22',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2595, 0.6258, 0.2868)),
      Box(center: V3(0.0000, 1.0013, 0.0000), half: V3(0.2511, 0.2847, 0.8217)),
    ],
    solution: Pose(0.8539, -0.2989, 0.0000),
  ),
  // day 23  ·  approach 0.012
  Level(
    name: 'day 23',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8678, 0.2777, 0.1987)),
      Box(center: V3(-1.3884, 0.0000, 0.0000), half: V3(0.2879, 0.7829, 0.2775), hinged: true),
      Box(center: V3(-1.3884, 1.2526, 0.0000), half: V3(0.6248, 0.2850, 0.1799)),
      Box(center: V3(-2.3882, 1.2526, 0.0000), half: V3(0.2783, 0.2487, 0.7397)),
    ],
    solution: Pose(2.4354, 0.0233, -0.5536),
  ),
  // day 24  ·  approach 0.012
  Level(
    name: 'day 24',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5372, 0.2900, 0.2831)),
      Box(center: V3(-0.8595, 0.0000, 0.0000), half: V3(0.1753, 0.6591, 0.2985), hinged: true),
    ],
    solution: Pose(-0.6563, 0.1717, 1.1876),
  ),
  // day 25  ·  approach 0.060
  Level(
    name: 'day 25',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2456, 0.8979, 0.1805)),
      Box(center: V3(0.0000, -1.4367, 0.0000), half: V3(0.5708, 0.2131, 0.1768)),
    ],
    solution: Pose(-2.1489, 0.2776, 0.0000),
  ),
  // day 26  ·  approach 0.008
  Level(
    name: 'day 26',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2760, 0.6465, 0.1958)),
      Box(center: V3(0.0000, 1.0344, 0.0000), half: V3(0.8815, 0.2193, 0.2825), hinged: true),
    ],
    solution: Pose(-0.6396, -0.2828, -0.2357),
  ),
  // day 27  ·  approach 0.012
  Level(
    name: 'day 27',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7955, 0.2851, 0.2733)),
      Box(center: V3(-1.2728, 0.0000, 0.0000), half: V3(0.2429, 0.1665, 0.5406), hinged: true),
    ],
    solution: Pose(-1.9601, 1.0516, 0.5685),
  ),
  // day 28  ·  approach 0.056
  Level(
    name: 'day 28',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2899, 0.6579, 0.2648)),
      Box(center: V3(0.0000, -1.0526, 0.0000), half: V3(0.6950, 0.2426, 0.2270)),
    ],
    solution: Pose(0.6008, 0.9217, 0.0000),
  ),
  // day 29  ·  approach 0.008
  Level(
    name: 'day 29',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7937, 0.2663, 0.2938)),
      Box(center: V3(-1.2700, 0.0000, 0.0000), half: V3(0.2883, 0.8284, 0.2464), hinged: true),
    ],
    solution: Pose(-2.5460, -0.2724, -0.8056),
  ),
  // day 30  ·  approach 0.012
  Level(
    name: 'day 30',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1633, 0.5266, 0.1798)),
      Box(center: V3(0.0000, 0.8426, 0.0000), half: V3(0.5661, 0.2104, 0.2523), hinged: true),
    ],
    solution: Pose(-2.0172, 0.3746, 0.2402),
  ),
  // day 31  ·  approach 0.052
  Level(
    name: 'day 31',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2484, 0.5164, 0.2284)),
      Box(center: V3(0.0000, 0.8263, 0.0000), half: V3(0.2794, 0.2550, 0.8950)),
    ],
    solution: Pose(-1.0570, 1.0395, 0.0000),
  ),
  // day 32  ·  approach 0.008
  Level(
    name: 'day 32',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2579, 0.5189, 0.2696)),
      Box(center: V3(0.0000, 0.8303, 0.0000), half: V3(0.2706, 0.1979, 0.7640), hinged: true),
    ],
    solution: Pose(2.2666, -0.6969, 0.9672),
  ),
  // day 33  ·  approach 0.008
  Level(
    name: 'day 33',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2184, 0.6828, 0.1720)),
      Box(center: V3(0.0000, 1.0924, 0.0000), half: V3(0.2489, 0.1829, 0.5133), hinged: true),
      Box(center: V3(0.0000, 1.0924, -0.8213), half: V3(0.9011, 0.2283, 0.1794), hinged: true),
    ],
    solution: Pose(0.3142, -1.0837, -0.9515),
  ),
  // day 34  ·  approach 0.048
  Level(
    name: 'day 34',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2468, 0.8521, 0.1779)),
      Box(center: V3(0.0000, -1.3634, 0.0000), half: V3(0.7177, 0.2658, 0.2731)),
    ],
    solution: Pose(-2.5954, -0.6016, 0.0000),
  ),
  // day 35  ·  approach 0.008
  Level(
    name: 'day 35',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7579, 0.2499, 0.2398)),
      Box(center: V3(-1.2127, 0.0000, 0.0000), half: V3(0.1908, 0.2114, 0.5691), hinged: true),
    ],
    solution: Pose(-2.8702, -0.0672, -0.3649),
  ),
  // day 36  ·  approach 0.008
  Level(
    name: 'day 36',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1751, 0.7953, 0.2072)),
      Box(center: V3(0.0000, -1.2725, 0.0000), half: V3(0.2964, 0.2508, 0.8058), hinged: true),
    ],
    solution: Pose(-0.5356, 0.0108, 0.5097),
  ),
  // day 37  ·  approach 0.040
  Level(
    name: 'day 37',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2673, 0.8205, 0.1654)),
      Box(center: V3(0.0000, -1.3128, 0.0000), half: V3(0.6581, 0.2085, 0.2125)),
    ],
    solution: Pose(0.5929, -0.3066, 0.0000),
  ),
  // day 38  ·  approach 0.008
  Level(
    name: 'day 38',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2459, 0.5369, 0.2382)),
      Box(center: V3(0.0000, -0.8590, 0.0000), half: V3(0.6279, 0.2643, 0.2194), hinged: true),
    ],
    solution: Pose(1.7168, -0.8027, 0.8356),
  ),
  // day 39  ·  approach 0.008
  Level(
    name: 'day 39',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1743, 0.5262, 0.2475)),
      Box(center: V3(0.0000, -0.8419, 0.0000), half: V3(0.7542, 0.1690, 0.1987), hinged: true),
    ],
    solution: Pose(0.1564, 0.2557, -0.7106),
  ),
  // day 40  ·  approach 0.036
  Level(
    name: 'day 40',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2227, 0.6635, 0.2094)),
      Box(center: V3(0.0000, -1.0615, 0.0000), half: V3(0.2837, 0.2087, 0.7767)),
    ],
    solution: Pose(2.6896, 0.4197, 0.0000),
  ),
  // day 41  ·  approach 0.008
  Level(
    name: 'day 41',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1868, 0.9448, 0.1860)),
      Box(center: V3(0.0000, -1.5117, 0.0000), half: V3(0.9419, 0.2950, 0.1776), hinged: true),
    ],
    solution: Pose(-0.7870, 0.4577, 0.5138),
  ),
  // day 42  ·  approach 0.008
  Level(
    name: 'day 42',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1932, 0.6505, 0.1866)),
      Box(center: V3(0.0000, 1.0408, 0.0000), half: V3(0.5323, 0.2767, 0.2938), hinged: true),
    ],
    solution: Pose(-2.3007, -0.7529, 0.7916),
  ),
  // day 43  ·  approach 0.032
  Level(
    name: 'day 43',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2791, 0.8099, 0.2675)),
      Box(center: V3(0.0000, 1.2959, 0.0000), half: V3(0.1778, 0.2178, 0.6833)),
    ],
    solution: Pose(-1.2647, 1.0639, 0.0000),
  ),
  // day 44  ·  approach 0.008
  Level(
    name: 'day 44',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8794, 0.2847, 0.2473)),
      Box(center: V3(-1.4070, 0.0000, 0.0000), half: V3(0.2824, 0.7064, 0.2805), hinged: true),
      Box(center: V3(-1.4070, 1.1302, 0.0000), half: V3(0.2025, 0.2109, 0.7553)),
      Box(center: V3(-1.4070, 1.1302, 1.2085), half: V3(0.7829, 0.2141, 0.1604)),
    ],
    solution: Pose(-2.5610, -0.0631, -0.3174),
  ),
  // day 45  ·  approach 0.008
  Level(
    name: 'day 45',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1748, 0.7421, 0.1626)),
      Box(center: V3(0.0000, 1.1873, 0.0000), half: V3(0.2779, 0.2357, 0.6702), hinged: true),
      Box(center: V3(0.0000, 1.1873, -1.0723), half: V3(0.1724, 0.7366, 0.2473), hinged: true),
    ],
    solution: Pose(-0.0370, -0.2058, -0.1997),
  ),
  // day 46  ·  approach 0.032
  Level(
    name: 'day 46',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1959, 0.7005, 0.2247)),
      Box(center: V3(0.0000, -1.1208, 0.0000), half: V3(0.1634, 0.1698, 0.6795)),
    ],
    solution: Pose(-2.1713, 0.6643, 0.0000),
  ),
  // day 47  ·  approach 0.008
  Level(
    name: 'day 47',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.6084, 0.2696, 0.2312)),
      Box(center: V3(-0.9734, 0.0000, 0.0000), half: V3(0.1638, 0.2761, 0.5743), hinged: true),
      Box(center: V3(-0.9734, 0.0000, 0.9188), half: V3(0.7976, 0.2974, 0.2051)),
      Box(center: V3(-2.2495, 0.0000, 0.9188), half: V3(0.1758, 0.2004, 0.8457)),
    ],
    solution: Pose(-1.9756, 0.2089, -0.8254),
  ),
  // day 48  ·  approach 0.008
  Level(
    name: 'day 48',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5016, 0.2753, 0.1874)),
      Box(center: V3(-0.8025, 0.0000, 0.0000), half: V3(0.2032, 0.1810, 0.6278), hinged: true),
    ],
    solution: Pose(1.8608, 0.4098, -1.1847),
  ),
  // day 49  ·  approach 0.028
  Level(
    name: 'day 49',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1818, 0.5680, 0.2264)),
      Box(center: V3(0.0000, -0.9088, 0.0000), half: V3(0.2176, 0.1978, 0.5195)),
    ],
    solution: Pose(0.1678, -0.5748, 0.0000),
  ),
  // day 50  ·  approach 0.008
  Level(
    name: 'day 50',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2088, 0.5719, 0.2168)),
      Box(center: V3(0.0000, -0.9151, 0.0000), half: V3(0.2948, 0.1982, 0.6852), hinged: true),
    ],
    solution: Pose(0.6590, 0.7736, 0.7332),
  ),
  // day 51  ·  approach 0.008
  Level(
    name: 'day 51',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2984, 0.7222, 0.1667)),
      Box(center: V3(0.0000, -1.1555, 0.0000), half: V3(0.2046, 0.2157, 0.9354), hinged: true),
    ],
    solution: Pose(-3.0129, -0.4023, -1.0547),
  ),
  // day 52  ·  approach 0.028
  Level(
    name: 'day 52',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2791, 0.6919, 0.2576)),
      Box(center: V3(0.0000, 1.1071, 0.0000), half: V3(0.5306, 0.1985, 0.2084)),
    ],
    solution: Pose(0.2004, 0.3293, 0.0000),
  ),
  // day 53  ·  approach 0.008
  Level(
    name: 'day 53',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2667, 0.5349, 0.2415)),
      Box(center: V3(0.0000, 0.8559, 0.0000), half: V3(0.6964, 0.1875, 0.1874), hinged: true),
    ],
    solution: Pose(-2.1248, 0.0129, 0.7685),
  ),
  // day 54  ·  approach 0.008
  Level(
    name: 'day 54',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2594, 0.6276, 0.2670)),
      Box(center: V3(0.0000, 1.0041, 0.0000), half: V3(0.7129, 0.2796, 0.1966), hinged: true),
    ],
    solution: Pose(-2.2332, -0.5262, -0.5951),
  ),
  // day 55  ·  approach 0.028
  Level(
    name: 'day 55',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2609, 0.6051, 0.2130)),
      Box(center: V3(0.0000, 0.9682, 0.0000), half: V3(0.2524, 0.2523, 0.8220)),
    ],
    solution: Pose(2.5155, 1.0598, 0.0000),
  ),
  // day 56  ·  approach 0.008
  Level(
    name: 'day 56',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7969, 0.1691, 0.1609)),
      Box(center: V3(-1.2751, 0.0000, 0.0000), half: V3(0.2934, 0.5006, 0.2721), hinged: true),
      Box(center: V3(-1.2751, -0.8009, 0.0000), half: V3(0.7797, 0.1738, 0.2560)),
      Box(center: V3(-0.0276, -0.8009, 0.0000), half: V3(0.2864, 0.8787, 0.2835)),
    ],
    solution: Pose(0.7156, 0.8498, 0.5515),
  ),
  // day 57  ·  approach 0.008
  Level(
    name: 'day 57',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2722, 0.5295, 0.2283)),
      Box(center: V3(0.0000, 0.8472, 0.0000), half: V3(0.1604, 0.2746, 0.9219), hinged: true),
    ],
    solution: Pose(-0.8533, -0.1018, 0.4583),
  ),
  // day 58  ·  approach 0.020
  Level(
    name: 'day 58',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1623, 0.7739, 0.2296)),
      Box(center: V3(0.0000, -1.2383, 0.0000), half: V3(0.2483, 0.2058, 0.6755)),
    ],
    solution: Pose(0.5961, 0.7746, 0.0000),
  ),
  // day 59  ·  approach 0.008
  Level(
    name: 'day 59',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2111, 0.2947, 0.5495)),
      Box(center: V3(0.0000, 0.0000, -0.8792), half: V3(0.2651, 0.5960, 0.1690), hinged: true),
      Box(center: V3(0.0000, -0.9536, -0.8792), half: V3(0.8437, 0.2668, 0.2564)),
    ],
    solution: Pose(2.1840, -0.6962, -0.4810),
  ),
  // day 60  ·  approach 0.004
  Level(
    name: 'day 60',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1861, 0.1651, 0.7335)),
      Box(center: V3(0.0000, 0.0000, 1.1735), half: V3(0.6642, 0.2209, 0.2704), hinged: true),
      Box(center: V3(-1.0628, 0.0000, 1.1735), half: V3(0.1959, 0.9138, 0.2740), hinged: true),
      Box(center: V3(-1.0628, 1.4622, 1.1735), half: V3(0.9486, 0.2261, 0.2980)),
    ],
    solution: Pose(-2.3959, -0.9845, -0.8447),
  ),
  // day 61  ·  approach 0.020
  Level(
    name: 'day 61',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2477, 0.6006, 0.2035)),
      Box(center: V3(0.0000, -0.9610, 0.0000), half: V3(0.1702, 0.2487, 0.9364)),
    ],
    solution: Pose(-0.7620, 0.4148, 0.0000),
  ),
  // day 62  ·  approach 0.008
  Level(
    name: 'day 62',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.9464, 0.2102, 0.2496)),
      Box(center: V3(1.5142, 0.0000, 0.0000), half: V3(0.2988, 0.2084, 0.6777), hinged: true),
      Box(center: V3(1.5142, 0.0000, -1.0844), half: V3(0.8268, 0.2620, 0.2487)),
      Box(center: V3(0.1913, 0.0000, -1.0844), half: V3(0.2239, 0.7271, 0.1769)),
    ],
    solution: Pose(1.9970, 0.7102, 0.7484),
  ),
  // day 63  ·  approach 0.004
  Level(
    name: 'day 63',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5860, 0.2027, 0.2963)),
      Box(center: V3(-0.9376, 0.0000, 0.0000), half: V3(0.2445, 0.2519, 0.8276), hinged: true),
    ],
    solution: Pose(-1.5163, -0.4695, 0.0949),
  ),
  // day 64  ·  approach 0.020
  Level(
    name: 'day 64',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8853, 0.2917, 0.2712)),
      Box(center: V3(-1.4165, 0.0000, 0.0000), half: V3(0.2297, 0.1684, 0.5570)),
      Box(center: V3(-1.4165, 0.0000, 0.8912), half: V3(0.9107, 0.2835, 0.2963)),
    ],
    solution: Pose(-2.6626, -0.7157, 0.0000),
  ),
  // day 65  ·  approach 0.008
  Level(
    name: 'day 65',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8167, 0.2942, 0.2890)),
      Box(center: V3(-1.3068, 0.0000, 0.0000), half: V3(0.2061, 0.1799, 0.5563), hinged: true),
    ],
    solution: Pose(-2.5470, -0.1459, 0.1582),
  ),
  // day 66  ·  approach 0.004
  Level(
    name: 'day 66',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5109, 0.2842, 0.2149)),
      Box(center: V3(-0.8174, 0.0000, 0.0000), half: V3(0.2901, 0.2664, 0.8224), hinged: true),
    ],
    solution: Pose(-0.7381, 0.7297, 0.0720),
  ),
  // day 67  ·  approach 0.020
  Level(
    name: 'day 67',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1619, 0.8511, 0.2500)),
      Box(center: V3(0.0000, -1.3618, 0.0000), half: V3(0.7918, 0.2805, 0.2774)),
    ],
    solution: Pose(-0.1880, -0.4865, 0.0000),
  ),
  // day 68  ·  approach 0.008
  Level(
    name: 'day 68',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1993, 0.7800, 0.2076)),
      Box(center: V3(0.0000, 1.2479, 0.0000), half: V3(0.2809, 0.1983, 0.5315), hinged: true),
    ],
    solution: Pose(0.7426, 1.1006, -0.8705),
  ),
  // day 69  ·  approach 0.004
  Level(
    name: 'day 69',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2725, 0.5237, 0.1800)),
      Box(center: V3(0.0000, 0.8380, 0.0000), half: V3(0.2275, 0.2044, 0.9349), hinged: true),
    ],
    solution: Pose(-1.0463, -0.0971, -0.7942),
  ),
  // day 70  ·  approach 0.016
  Level(
    name: 'day 70',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2711, 0.5483, 0.2275)),
      Box(center: V3(0.0000, -0.8774, 0.0000), half: V3(0.1790, 0.1849, 0.5423)),
      Box(center: V3(0.0000, -0.8774, -0.8677), half: V3(0.2809, 0.8673, 0.2563)),
      Box(center: V3(0.0000, 0.5103, -0.8677), half: V3(0.2471, 0.2735, 0.5264)),
    ],
    solution: Pose(-0.8241, 0.5929, 0.0000),
  ),
  // day 71  ·  approach 0.004
  Level(
    name: 'day 71',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2996, 0.2220, 0.6763)),
      Box(center: V3(0.0000, 0.0000, 1.0820), half: V3(0.6241, 0.2472, 0.1732), hinged: true),
      Box(center: V3(0.9986, 0.0000, 1.0820), half: V3(0.1967, 0.5166, 0.1643)),
      Box(center: V3(0.9986, -0.8265, 1.0820), half: V3(0.9362, 0.2927, 0.1917)),
    ],
    solution: Pose(-1.0823, -1.1034, -1.0340),
  ),
  // day 72  ·  approach 0.004
  Level(
    name: 'day 72',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7094, 0.2049, 0.2763)),
      Box(center: V3(-1.1350, 0.0000, 0.0000), half: V3(0.2921, 0.7843, 0.2935), hinged: true),
    ],
    solution: Pose(-2.9900, 0.4306, 0.0859),
  ),
  // day 73  ·  approach 0.016
  Level(
    name: 'day 73',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2511, 0.6085, 0.2345)),
      Box(center: V3(0.0000, -0.9735, 0.0000), half: V3(0.1741, 0.2516, 0.9210)),
    ],
    solution: Pose(0.1482, -0.5079, 0.0000),
  ),
  // day 74  ·  approach 0.004
  Level(
    name: 'day 74',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7101, 0.1869, 0.1655)),
      Box(center: V3(1.1362, 0.0000, 0.0000), half: V3(0.2259, 0.2945, 0.6702), hinged: true),
    ],
    solution: Pose(-2.5301, -0.8746, 0.2943),
  ),
  // day 75  ·  approach 0.004
  Level(
    name: 'day 75',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8189, 0.2865, 0.2609)),
      Box(center: V3(1.3102, 0.0000, 0.0000), half: V3(0.1957, 0.2160, 0.8606), hinged: true),
    ],
    solution: Pose(-3.0324, 0.1847, 0.9989),
  ),
  // day 76  ·  approach 0.016
  Level(
    name: 'day 76',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2707, 0.5269, 0.2411)),
      Box(center: V3(0.0000, 0.8430, 0.0000), half: V3(0.7348, 0.2383, 0.2335)),
      Box(center: V3(1.1756, 0.8430, 0.0000), half: V3(0.2661, 0.2575, 0.5267)),
    ],
    solution: Pose(0.9590, 0.7713, 0.0000),
  ),
  // day 77  ·  approach 0.004
  Level(
    name: 'day 77',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2013, 0.7934, 0.2646)),
      Box(center: V3(0.0000, -1.2695, 0.0000), half: V3(0.1608, 0.2863, 0.5008), hinged: true),
    ],
    solution: Pose(-2.6459, 1.1095, 0.3457),
  ),
  // day 78  ·  approach 0.004
  Level(
    name: 'day 78',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2284, 0.6479, 0.2154)),
      Box(center: V3(0.0000, -1.0366, 0.0000), half: V3(0.2412, 0.2105, 0.8520), hinged: true),
    ],
    solution: Pose(-3.0882, 0.2438, 0.2982),
  ),
  // day 79  ·  approach 0.012
  Level(
    name: 'day 79',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2211, 0.8619, 0.2684)),
      Box(center: V3(0.0000, -1.3790, 0.0000), half: V3(0.2914, 0.2276, 0.8063)),
      Box(center: V3(0.0000, -1.3790, -1.2901), half: V3(0.2850, 0.6070, 0.2221)),
      Box(center: V3(0.0000, -0.4077, -1.2901), half: V3(0.7683, 0.2011, 0.1608)),
    ],
    solution: Pose(0.6840, -0.8957, 0.0000),
  ),
  // day 80  ·  approach 0.004
  Level(
    name: 'day 80',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.6552, 0.2241, 0.2142)),
      Box(center: V3(-1.0484, 0.0000, 0.0000), half: V3(0.1975, 0.2989, 0.8315), hinged: true),
    ],
    solution: Pose(2.5356, 0.2969, 0.2007),
  ),
  // day 81  ·  approach 0.004
  Level(
    name: 'day 81',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8725, 0.1836, 0.2083)),
      Box(center: V3(-1.3960, 0.0000, 0.0000), half: V3(0.1874, 0.2912, 0.7444), hinged: true),
    ],
    solution: Pose(-3.0267, -0.8689, -0.0832),
  ),
  // day 82  ·  approach 0.012
  Level(
    name: 'day 82',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2579, 0.8879, 0.2787)),
      Box(center: V3(0.0000, -1.4206, 0.0000), half: V3(0.2719, 0.1683, 0.6622)),
    ],
    solution: Pose(1.6280, 1.0937, 0.0000),
  ),
  // day 83  ·  approach 0.004
  Level(
    name: 'day 83',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2931, 0.2524, 0.6684)),
      Box(center: V3(0.0000, 0.0000, 1.0695), half: V3(0.6350, 0.1759, 0.2028), hinged: true),
    ],
    solution: Pose(1.0567, 0.1011, 1.0403),
  ),
  // day 84  ·  approach 0.004
  Level(
    name: 'day 84',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8736, 0.2402, 0.2476)),
      Box(center: V3(1.3978, 0.0000, 0.0000), half: V3(0.2668, 0.2086, 0.5995), hinged: true),
      Box(center: V3(1.3978, 0.0000, -0.9592), half: V3(0.5145, 0.2976, 0.2267), hinged: true),
      Box(center: V3(2.2210, 0.0000, -0.9592), half: V3(0.1795, 0.6815, 0.1819)),
    ],
    solution: Pose(0.1349, -0.9368, -0.1736),
  ),
  // day 85  ·  approach 0.012
  Level(
    name: 'day 85',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2543, 0.2393, 0.9047)),
      Box(center: V3(0.0000, 0.0000, 1.4475), half: V3(0.2847, 0.8292, 0.2875)),
      Box(center: V3(0.0000, 1.3267, 1.4475), half: V3(0.1608, 0.2807, 0.8959)),
      Box(center: V3(0.0000, 1.3267, 2.8809), half: V3(0.7519, 0.1824, 0.1607)),
    ],
    solution: Pose(-2.5097, -0.3727, 0.0000),
  ),
  // day 86  ·  approach 0.004
  Level(
    name: 'day 86',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2937, 0.7298, 0.2678)),
      Box(center: V3(0.0000, -1.1676, 0.0000), half: V3(0.5722, 0.2313, 0.1945), hinged: true),
    ],
    solution: Pose(-1.6637, -0.5914, -0.3282),
  ),
  // day 87  ·  approach 0.004
  Level(
    name: 'day 87',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.6243, 0.2883, 0.2942)),
      Box(center: V3(-0.9988, 0.0000, 0.0000), half: V3(0.2706, 0.5551, 0.2445), hinged: true),
      Box(center: V3(-0.9988, 0.8881, 0.0000), half: V3(0.1741, 0.2091, 0.5387), hinged: true),
    ],
    solution: Pose(1.9987, 0.8764, 1.0832),
  ),
  // day 88  ·  approach 0.012
  Level(
    name: 'day 88',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1782, 0.7180, 0.2317)),
      Box(center: V3(0.0000, -1.1488, 0.0000), half: V3(0.8734, 0.1806, 0.2258)),
      Box(center: V3(1.3974, -1.1488, 0.0000), half: V3(0.2987, 0.2278, 0.9452)),
    ],
    solution: Pose(1.1074, -1.1448, 0.0000),
  ),
  // day 89  ·  approach 0.004
  Level(
    name: 'day 89',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5582, 0.1640, 0.1668)),
      Box(center: V3(0.8931, 0.0000, 0.0000), half: V3(0.2954, 0.6281, 0.1705), hinged: true),
      Box(center: V3(0.8931, -1.0050, 0.0000), half: V3(0.2402, 0.1703, 0.7427)),
    ],
    solution: Pose(-0.9551, -0.8109, -0.4471),
  ),
  // day 90  ·  approach 0.004
  Level(
    name: 'day 90',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8581, 0.1924, 0.2931)),
      Box(center: V3(1.3730, 0.0000, 0.0000), half: V3(0.2547, 0.8306, 0.1987), hinged: true),
    ],
    solution: Pose(0.9231, -0.9668, 1.2686),
  ),
  // day 91  ·  approach 0.008
  Level(
    name: 'day 91',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.9019, 0.1938, 0.2594)),
      Box(center: V3(-1.4430, 0.0000, 0.0000), half: V3(0.2208, 0.8393, 0.2801)),
      Box(center: V3(-1.4430, 1.3429, 0.0000), half: V3(0.1690, 0.2137, 0.5583)),
      Box(center: V3(-1.4430, 1.3429, -0.8933), half: V3(0.5056, 0.2801, 0.2191)),
    ],
    solution: Pose(-1.3286, -0.8796, 0.0000),
  ),
  // day 92  ·  approach 0.004
  Level(
    name: 'day 92',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2882, 0.2924, 0.6503)),
      Box(center: V3(0.0000, 0.0000, -1.0405), half: V3(0.1877, 0.6265, 0.1852), hinged: true),
    ],
    solution: Pose(-0.0281, -0.0724, 0.7630),
  ),
  // day 93  ·  approach 0.004
  Level(
    name: 'day 93',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2733, 0.7956, 0.2461)),
      Box(center: V3(0.0000, 1.2729, 0.0000), half: V3(0.2216, 0.2921, 0.8175), hinged: true),
      Box(center: V3(0.0000, 1.2729, -1.3081), half: V3(0.9010, 0.2003, 0.1916), hinged: true),
      Box(center: V3(1.4417, 1.2729, -1.3081), half: V3(0.2061, 0.9457, 0.2902)),
    ],
    solution: Pose(-2.7736, -0.9893, -0.7833),
  ),
  // day 94  ·  approach 0.008
  Level(
    name: 'day 94',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5265, 0.2581, 0.2800)),
      Box(center: V3(-0.8423, 0.0000, 0.0000), half: V3(0.1620, 0.2946, 0.7201)),
    ],
    solution: Pose(1.4540, 0.0457, 0.0000),
  ),
  // day 95  ·  approach 0.004
  Level(
    name: 'day 95',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2058, 0.2411, 0.7073)),
      Box(center: V3(0.0000, 0.0000, -1.1317), half: V3(0.2701, 0.8851, 0.1901), hinged: true),
      Box(center: V3(0.0000, 1.4162, -1.1317), half: V3(0.2486, 0.2672, 0.9493)),
    ],
    solution: Pose(-3.0423, 0.3441, 1.1168),
  ),
  // day 96  ·  approach 0.004
  Level(
    name: 'day 96',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7646, 0.2307, 0.2249)),
      Box(center: V3(-1.2234, 0.0000, 0.0000), half: V3(0.2902, 0.2621, 0.8456), hinged: true),
      Box(center: V3(-1.2234, 0.0000, 1.3530), half: V3(0.5382, 0.2969, 0.2569), hinged: true),
    ],
    solution: Pose(-0.8324, -1.0510, -0.6345),
  ),
  // day 97  ·  approach 0.008
  Level(
    name: 'day 97',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1993, 0.2335, 0.5601)),
      Box(center: V3(0.0000, 0.0000, -0.8962), half: V3(0.2543, 0.5909, 0.1781)),
      Box(center: V3(0.0000, -0.9454, -0.8962), half: V3(0.2976, 0.2188, 0.6535)),
      Box(center: V3(0.0000, -0.9454, -1.9418), half: V3(0.6572, 0.2759, 0.1958)),
    ],
    solution: Pose(-0.5924, 0.5072, 0.0000),
  ),
  // day 98  ·  approach 0.004
  Level(
    name: 'day 98',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2716, 0.8218, 0.2979)),
      Box(center: V3(0.0000, 1.3148, 0.0000), half: V3(0.1688, 0.2898, 0.8466), hinged: true),
    ],
    solution: Pose(-2.9422, -0.8435, 0.7247),
  ),
  // day 99  ·  approach 0.004
  Level(
    name: 'day 99',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7466, 0.2444, 0.2762)),
      Box(center: V3(1.1945, 0.0000, 0.0000), half: V3(0.2797, 0.8966, 0.2480), hinged: true),
    ],
    solution: Pose(-0.0744, -0.2976, -1.0734),
  ),
  // day 100  ·  approach 0.008
  Level(
    name: 'day 100',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2375, 0.7814, 0.2845)),
      Box(center: V3(0.0000, -1.2502, 0.0000), half: V3(0.2283, 0.2236, 0.8250)),
    ],
    solution: Pose(-2.4752, 1.1891, 0.0000),
  ),
  // day 101  ·  approach 0.004
  Level(
    name: 'day 101',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2511, 0.6977, 0.2620)),
      Box(center: V3(0.0000, 1.1163, 0.0000), half: V3(0.7232, 0.2319, 0.2686), hinged: true),
    ],
    solution: Pose(2.3239, 0.3889, 0.9422),
  ),
  // day 102  ·  approach 0.004
  Level(
    name: 'day 102',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2734, 0.6511, 0.2004)),
      Box(center: V3(0.0000, -1.0418, 0.0000), half: V3(0.8633, 0.2199, 0.2017), hinged: true),
    ],
    solution: Pose(-2.5199, 0.1973, 0.9735),
  ),
  // day 103  ·  approach 0.008
  Level(
    name: 'day 103',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7211, 0.2375, 0.2007)),
      Box(center: V3(1.1538, 0.0000, 0.0000), half: V3(0.2966, 0.8280, 0.2264)),
    ],
    solution: Pose(-2.7192, 1.0229, 0.0000),
  ),
  // day 104  ·  approach 0.004
  Level(
    name: 'day 104',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2746, 0.6417, 0.1994)),
      Box(center: V3(0.0000, -1.0268, 0.0000), half: V3(0.2481, 0.2133, 0.7209), hinged: true),
    ],
    solution: Pose(2.4888, -0.9918, 0.3193),
  ),
  // day 105  ·  approach 0.004
  Level(
    name: 'day 105',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.6341, 0.2632, 0.2904)),
      Box(center: V3(-1.0146, 0.0000, 0.0000), half: V3(0.2234, 0.5078, 0.1826), hinged: true),
    ],
    solution: Pose(2.8834, 0.5970, 0.6201),
  ),
  // day 106  ·  approach 0.008
  Level(
    name: 'day 106',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2077, 0.1851, 0.5194)),
      Box(center: V3(0.0000, 0.0000, -0.8310), half: V3(0.9139, 0.2540, 0.2400)),
    ],
    solution: Pose(-0.6699, -1.1540, 0.0000),
  ),
  // day 107  ·  approach 0.004
  Level(
    name: 'day 107',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1999, 0.7550, 0.1678)),
      Box(center: V3(0.0000, -1.2079, 0.0000), half: V3(0.5204, 0.1934, 0.2259), hinged: true),
    ],
    solution: Pose(-2.2951, -0.7058, 0.4055),
  ),
  // day 108  ·  approach 0.004
  Level(
    name: 'day 108',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5580, 0.1644, 0.2657)),
      Box(center: V3(0.8929, 0.0000, 0.0000), half: V3(0.2474, 0.2817, 0.5369), hinged: true),
      Box(center: V3(0.8929, 0.0000, 0.8591), half: V3(0.5837, 0.2974, 0.2090), hinged: true),
    ],
    solution: Pose(2.9220, 0.6322, 0.2771),
  ),
  // day 109  ·  approach 0.008
  Level(
    name: 'day 109',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7315, 0.2065, 0.2189)),
      Box(center: V3(1.1704, 0.0000, 0.0000), half: V3(0.2565, 0.1945, 0.7549)),
      Box(center: V3(1.1704, 0.0000, -1.2078), half: V3(0.1644, 0.5158, 0.1831)),
      Box(center: V3(1.1704, -0.8253, -1.2078), half: V3(0.2403, 0.2560, 0.8454)),
    ],
    solution: Pose(-1.0296, 0.7576, 0.0000),
  ),
  // day 110  ·  approach 0.004
  Level(
    name: 'day 110',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8074, 0.1667, 0.1750)),
      Box(center: V3(1.2919, 0.0000, 0.0000), half: V3(0.2375, 0.5313, 0.1606), hinged: true),
      Box(center: V3(1.2919, -0.8501, 0.0000), half: V3(0.2636, 0.2765, 0.6647)),
    ],
    solution: Pose(-2.2794, -0.0224, -0.7254),
  ),
  // day 111  ·  approach 0.004
  Level(
    name: 'day 111',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2434, 0.5101, 0.2512)),
      Box(center: V3(0.0000, -0.8161, 0.0000), half: V3(0.8191, 0.1656, 0.1613), hinged: true),
      Box(center: V3(-1.3106, -0.8161, 0.0000), half: V3(0.2555, 0.5579, 0.2159), hinged: true),
    ],
    solution: Pose(-2.4941, 0.0828, 0.9327),
  ),
  // day 112  ·  approach 0.008
  Level(
    name: 'day 112',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.6353, 0.2893, 0.2577)),
      Box(center: V3(-1.0165, 0.0000, 0.0000), half: V3(0.2646, 0.8250, 0.1765)),
      Box(center: V3(-1.0165, -1.3199, 0.0000), half: V3(0.1725, 0.1872, 0.7048)),
    ],
    solution: Pose(-2.0287, 0.7925, 0.0000),
  ),
  // day 113  ·  approach 0.004
  Level(
    name: 'day 113',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5230, 0.2657, 0.2467)),
      Box(center: V3(0.8368, 0.0000, 0.0000), half: V3(0.2089, 0.7016, 0.2520), hinged: true),
    ],
    solution: Pose(-0.4239, 0.1395, 0.4338),
  ),
  // day 114  ·  approach 0.004
  Level(
    name: 'day 114',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8330, 0.2629, 0.2143)),
      Box(center: V3(-1.3328, 0.0000, 0.0000), half: V3(0.2004, 0.2223, 0.5005), hinged: true),
    ],
    solution: Pose(-1.6038, -0.8613, 0.8885),
  ),
  // day 115  ·  approach 0.008
  Level(
    name: 'day 115',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2532, 0.6905, 0.2496)),
      Box(center: V3(0.0000, 1.1049, 0.0000), half: V3(0.2159, 0.2027, 0.7131)),
      Box(center: V3(0.0000, 1.1049, 1.1409), half: V3(0.7541, 0.2401, 0.1699)),
    ],
    solution: Pose(-2.5009, -0.3987, 0.0000),
  ),
  // day 116  ·  approach 0.004
  Level(
    name: 'day 116',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1651, 0.6874, 0.2464)),
      Box(center: V3(0.0000, 1.0998, 0.0000), half: V3(0.2590, 0.2535, 0.6750), hinged: true),
    ],
    solution: Pose(1.1889, 0.6370, -0.6203),
  ),
  // day 117  ·  approach 0.004
  Level(
    name: 'day 117',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2365, 0.2204, 0.6770)),
      Box(center: V3(0.0000, 0.0000, -1.0832), half: V3(0.2026, 0.7539, 0.1688), hinged: true),
    ],
    solution: Pose(2.2293, -0.6850, -0.0011),
  ),
  // day 118  ·  approach 0.004
  Level(
    name: 'day 118',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1623, 0.7697, 0.2202)),
      Box(center: V3(0.0000, -1.2316, 0.0000), half: V3(0.8903, 0.2398, 0.2508)),
      Box(center: V3(-1.4246, -1.2316, 0.0000), half: V3(0.2736, 0.2847, 0.5222)),
    ],
    solution: Pose(2.8788, 1.0283, 0.0000),
  ),
  // day 119  ·  approach 0.004
  Level(
    name: 'day 119',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7380, 0.2073, 0.2653)),
      Box(center: V3(-1.1809, 0.0000, 0.0000), half: V3(0.2422, 0.2912, 0.5790), hinged: true),
    ],
    solution: Pose(3.0457, 0.7128, 1.0371),
  ),
  // day 120  ·  approach 0.004
  Level(
    name: 'day 120',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2910, 0.2404, 0.5394)),
      Box(center: V3(0.0000, 0.0000, -0.8630), half: V3(0.2828, 0.5751, 0.2597), hinged: true),
    ],
    solution: Pose(1.6834, -1.0841, 0.6373),
  ),
  // day 121  ·  approach 0.004
  Level(
    name: 'day 121',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2473, 0.2617, 0.8286)),
      Box(center: V3(0.0000, 0.0000, -1.3258), half: V3(0.5911, 0.1676, 0.2752)),
      Box(center: V3(0.9458, 0.0000, -1.3258), half: V3(0.1857, 0.7680, 0.2652)),
    ],
    solution: Pose(2.0455, -0.1971, 0.0000),
  ),
  // day 122  ·  approach 0.004
  Level(
    name: 'day 122',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1912, 0.8830, 0.2004)),
      Box(center: V3(0.0000, 1.4129, 0.0000), half: V3(0.9344, 0.2986, 0.2917), hinged: true),
    ],
    solution: Pose(1.9294, -0.7564, -1.1876),
  ),
  // day 123  ·  approach 0.004
  Level(
    name: 'day 123',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7691, 0.2897, 0.2408)),
      Box(center: V3(-1.2305, 0.0000, 0.0000), half: V3(0.2873, 0.5412, 0.2104), hinged: true),
      Box(center: V3(-1.2305, 0.8659, 0.0000), half: V3(0.2581, 0.2589, 0.8841), hinged: true),
      Box(center: V3(-1.2305, 0.8659, 1.4146), half: V3(0.5795, 0.2637, 0.2835)),
    ],
    solution: Pose(1.8548, -0.0246, 1.0069),
  ),
  // day 124  ·  approach 0.004
  Level(
    name: 'day 124',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8291, 0.1678, 0.2614)),
      Box(center: V3(1.3266, 0.0000, 0.0000), half: V3(0.1764, 0.9359, 0.2143)),
      Box(center: V3(1.3266, 1.4975, 0.0000), half: V3(0.6939, 0.2199, 0.2772)),
    ],
    solution: Pose(1.2165, 0.3488, 0.0000),
  ),
  // day 125  ·  approach 0.004
  Level(
    name: 'day 125',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1663, 0.5208, 0.2708)),
      Box(center: V3(0.0000, 0.8333, 0.0000), half: V3(0.8884, 0.1686, 0.2048), hinged: true),
      Box(center: V3(-1.4215, 0.8333, 0.0000), half: V3(0.2682, 0.6997, 0.2513)),
    ],
    solution: Pose(-1.0219, 0.5992, 0.0758),
  ),
  // day 126  ·  approach 0.004
  Level(
    name: 'day 126',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2105, 0.7508, 0.2436)),
      Box(center: V3(0.0000, 1.2012, 0.0000), half: V3(0.2917, 0.2412, 0.8283), hinged: true),
    ],
    solution: Pose(1.9901, 0.1484, 0.2323),
  ),
  // day 127  ·  approach 0.004
  Level(
    name: 'day 127',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2606, 0.6207, 0.1921)),
      Box(center: V3(0.0000, 0.9931, 0.0000), half: V3(0.7375, 0.2490, 0.2744)),
      Box(center: V3(1.1800, 0.9931, 0.0000), half: V3(0.2895, 0.6029, 0.2252)),
    ],
    solution: Pose(2.1866, 0.3017, 0.0000),
  ),
  // day 128  ·  approach 0.004
  Level(
    name: 'day 128',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2331, 0.2235, 0.7786)),
      Box(center: V3(0.0000, 0.0000, 1.2457), half: V3(0.2781, 0.8469, 0.1691), hinged: true),
    ],
    solution: Pose(-1.0128, -0.8151, 1.1327),
  ),
  // day 129  ·  approach 0.004
  Level(
    name: 'day 129',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1724, 0.8075, 0.1715)),
      Box(center: V3(0.0000, 1.2919, 0.0000), half: V3(0.1826, 0.1615, 0.7199), hinged: true),
    ],
    solution: Pose(0.3064, 0.5444, 0.1774),
  ),
  // day 130  ·  approach 0.004
  Level(
    name: 'day 130',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2958, 0.1669, 0.8040)),
      Box(center: V3(0.0000, 0.0000, 1.2864), half: V3(0.2566, 0.8067, 0.2999)),
    ],
    solution: Pose(-1.2626, 0.0639, 0.0000),
  ),
  // day 131  ·  approach 0.004
  Level(
    name: 'day 131',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1870, 0.1801, 0.7531)),
      Box(center: V3(0.0000, 0.0000, -1.2049), half: V3(0.2740, 0.8857, 0.2815), hinged: true),
    ],
    solution: Pose(-0.8774, 1.1892, -0.9550),
  ),
  // day 132  ·  approach 0.004
  Level(
    name: 'day 132',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1796, 0.8565, 0.1879)),
      Box(center: V3(0.0000, -1.3703, 0.0000), half: V3(0.5465, 0.2216, 0.2977), hinged: true),
      Box(center: V3(-0.8745, -1.3703, 0.0000), half: V3(0.1848, 0.2350, 0.5567), hinged: true),
    ],
    solution: Pose(-2.8177, -0.7714, 1.1578),
  ),
  // day 133  ·  approach 0.004
  Level(
    name: 'day 133',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7139, 0.2402, 0.2091)),
      Box(center: V3(1.1422, 0.0000, 0.0000), half: V3(0.2283, 0.7199, 0.1612)),
      Box(center: V3(1.1422, -1.1518, 0.0000), half: V3(0.1813, 0.1650, 0.7395)),
    ],
    solution: Pose(3.1258, -0.8088, 0.0000),
  ),
  // day 134  ·  approach 0.004
  Level(
    name: 'day 134',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2672, 0.2756, 0.5489)),
      Box(center: V3(0.0000, 0.0000, 0.8782), half: V3(0.2660, 0.5322, 0.2247), hinged: true),
    ],
    solution: Pose(2.6262, 1.0202, 0.7966),
  ),
  // day 135  ·  approach 0.004
  Level(
    name: 'day 135',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2599, 0.2519, 0.8582)),
      Box(center: V3(0.0000, 0.0000, -1.3732), half: V3(0.2209, 0.7580, 0.1762), hinged: true),
      Box(center: V3(0.0000, -1.2128, -1.3732), half: V3(0.1646, 0.2850, 0.8455), hinged: true),
    ],
    solution: Pose(-2.5584, -1.0626, 1.2250),
  ),
  // day 136  ·  approach 0.004
  Level(
    name: 'day 136',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1776, 0.2192, 0.8053)),
      Box(center: V3(0.0000, 0.0000, 1.2884), half: V3(0.5656, 0.2114, 0.1901)),
      Box(center: V3(0.9050, 0.0000, 1.2884), half: V3(0.2557, 0.2780, 0.6591)),
    ],
    solution: Pose(-1.4646, -0.5506, 0.0000),
  ),
  // day 137  ·  approach 0.004
  Level(
    name: 'day 137',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2626, 0.8435, 0.2301)),
      Box(center: V3(0.0000, 1.3496, 0.0000), half: V3(0.2973, 0.2999, 0.8227), hinged: true),
    ],
    solution: Pose(-2.6501, 0.0254, -0.6426),
  ),
  // day 138  ·  approach 0.004
  Level(
    name: 'day 138',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2393, 0.5960, 0.1690)),
      Box(center: V3(0.0000, 0.9536, 0.0000), half: V3(0.5066, 0.2989, 0.2345), hinged: true),
      Box(center: V3(0.8105, 0.9536, 0.0000), half: V3(0.2379, 0.8124, 0.2913), hinged: true),
      Box(center: V3(0.8105, -0.3463, 0.0000), half: V3(0.6585, 0.2542, 0.2729)),
    ],
    solution: Pose(-1.2270, 0.8925, -0.2957),
  ),
  // day 139  ·  approach 0.004
  Level(
    name: 'day 139',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2389, 0.2212, 0.8669)),
      Box(center: V3(0.0000, 0.0000, -1.3870), half: V3(0.2379, 0.5281, 0.1742)),
      Box(center: V3(0.0000, -0.8449, -1.3870), half: V3(0.6736, 0.1957, 0.1938)),
    ],
    solution: Pose(-2.1930, -0.0213, 0.0000),
  ),
  // day 140  ·  approach 0.004
  Level(
    name: 'day 140',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2161, 0.6452, 0.2928)),
      Box(center: V3(0.0000, -1.0323, 0.0000), half: V3(0.2033, 0.1883, 0.5816), hinged: true),
      Box(center: V3(0.0000, -1.0323, 0.9305), half: V3(0.5243, 0.2527, 0.1765)),
    ],
    solution: Pose(0.9156, -0.3323, 1.1191),
  ),
  // day 141  ·  approach 0.004
  Level(
    name: 'day 141',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2803, 0.2202, 0.6138)),
      Box(center: V3(0.0000, 0.0000, 0.9821), half: V3(0.6757, 0.1898, 0.2655), hinged: true),
      Box(center: V3(1.0812, 0.0000, 0.9821), half: V3(0.1973, 0.1825, 0.6814), hinged: true),
      Box(center: V3(1.0812, 0.0000, -0.1081), half: V3(0.1884, 0.5864, 0.2347)),
    ],
    solution: Pose(0.7658, -1.1216, 1.1073),
  ),
  // day 142  ·  approach 0.004
  Level(
    name: 'day 142',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5675, 0.2442, 0.2743)),
      Box(center: V3(0.9081, 0.0000, 0.0000), half: V3(0.1694, 0.8597, 0.1758)),
      Box(center: V3(0.9081, -1.3755, 0.0000), half: V3(0.6169, 0.1783, 0.2787)),
      Box(center: V3(1.8950, -1.3755, 0.0000), half: V3(0.2822, 0.9370, 0.2942)),
    ],
    solution: Pose(1.4103, -0.4579, 0.0000),
  ),
  // day 143  ·  approach 0.004
  Level(
    name: 'day 143',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2592, 0.5875, 0.2560)),
      Box(center: V3(0.0000, 0.9400, 0.0000), half: V3(0.1940, 0.2103, 0.6022), hinged: true),
    ],
    solution: Pose(-0.9597, -0.5443, -0.0205),
  ),
  // day 144  ·  approach 0.004
  Level(
    name: 'day 144',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.6771, 0.2342, 0.2215)),
      Box(center: V3(-1.0833, 0.0000, 0.0000), half: V3(0.1773, 0.7146, 0.2889), hinged: true),
    ],
    solution: Pose(0.0473, 0.9875, 0.2021),
  ),
  // day 145  ·  approach 0.004
  Level(
    name: 'day 145',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7513, 0.2993, 0.1684)),
      Box(center: V3(1.2021, 0.0000, 0.0000), half: V3(0.2222, 0.9226, 0.1725)),
      Box(center: V3(1.2021, 1.4762, 0.0000), half: V3(0.7886, 0.2460, 0.1685)),
      Box(center: V3(-0.0596, 1.4762, 0.0000), half: V3(0.2955, 0.6712, 0.2767)),
    ],
    solution: Pose(-0.0944, -0.8382, 0.0000),
  ),
  // day 146  ·  approach 0.004
  Level(
    name: 'day 146',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2328, 0.7110, 0.2508)),
      Box(center: V3(0.0000, -1.1375, 0.0000), half: V3(0.8355, 0.1671, 0.2484), hinged: true),
    ],
    solution: Pose(0.9787, 0.3041, -0.8574),
  ),
  // day 147  ·  approach 0.004
  Level(
    name: 'day 147',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1897, 0.1689, 0.7191)),
      Box(center: V3(0.0000, 0.0000, 1.1506), half: V3(0.5580, 0.1925, 0.2995), hinged: true),
    ],
    solution: Pose(0.3062, 0.0507, -1.0391),
  ),
  // day 148  ·  approach 0.004
  Level(
    name: 'day 148',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2506, 0.1685, 0.7926)),
      Box(center: V3(0.0000, 0.0000, -1.2682), half: V3(0.2068, 0.8726, 0.2298)),
      Box(center: V3(0.0000, 1.3962, -1.2682), half: V3(0.2672, 0.1765, 0.5370)),
      Box(center: V3(0.0000, 1.3962, -2.1273), half: V3(0.7838, 0.2022, 0.1848)),
    ],
    solution: Pose(2.2086, 0.7911, 0.0000),
  ),
  // day 149  ·  approach 0.004
  Level(
    name: 'day 149',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5738, 0.1876, 0.2367)),
      Box(center: V3(-0.9181, 0.0000, 0.0000), half: V3(0.2225, 0.6396, 0.2425), hinged: true),
    ],
    solution: Pose(-1.2913, 0.3077, 0.8115),
  ),
  // day 150  ·  approach 0.004
  Level(
    name: 'day 150',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2773, 0.5578, 0.2821)),
      Box(center: V3(0.0000, 0.8924, 0.0000), half: V3(0.9206, 0.1682, 0.1939), hinged: true),
      Box(center: V3(1.4729, 0.8924, 0.0000), half: V3(0.2378, 0.2758, 0.7906), hinged: true),
      Box(center: V3(1.4729, 0.8924, -1.2650), half: V3(0.1877, 0.6160, 0.2753)),
    ],
    solution: Pose(-2.7584, 0.6344, 0.5802),
  ),
  // day 151  ·  approach 0.004
  Level(
    name: 'day 151',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1919, 0.2488, 0.8901)),
      Box(center: V3(0.0000, 0.0000, 1.4242), half: V3(0.6291, 0.2072, 0.2947)),
    ],
    solution: Pose(1.2950, 0.4077, 0.0000),
  ),
  // day 152  ·  approach 0.004
  Level(
    name: 'day 152',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5977, 0.2668, 0.2697)),
      Box(center: V3(-0.9563, 0.0000, 0.0000), half: V3(0.2969, 0.5480, 0.1732), hinged: true),
      Box(center: V3(-0.9563, -0.8769, 0.0000), half: V3(0.6745, 0.1782, 0.2743)),
      Box(center: V3(0.1229, -0.8769, 0.0000), half: V3(0.2496, 0.1825, 0.6279)),
    ],
    solution: Pose(0.7419, 0.0204, 0.9991),
  ),
  // day 153  ·  approach 0.004
  Level(
    name: 'day 153',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1738, 0.8638, 0.2717)),
      Box(center: V3(0.0000, -1.3821, 0.0000), half: V3(0.2723, 0.2819, 0.9445), hinged: true),
    ],
    solution: Pose(-1.8270, -0.7334, -0.6036),
  ),
  // day 154  ·  approach 0.004
  Level(
    name: 'day 154',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7540, 0.2271, 0.1761)),
      Box(center: V3(1.2064, 0.0000, 0.0000), half: V3(0.2531, 0.2855, 0.6387)),
    ],
    solution: Pose(2.1667, -0.6927, 0.0000),
  ),
  // day 155  ·  approach 0.004
  Level(
    name: 'day 155',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8143, 0.2477, 0.2724)),
      Box(center: V3(-1.3028, 0.0000, 0.0000), half: V3(0.2776, 0.1789, 0.7556), hinged: true),
      Box(center: V3(-1.3028, 0.0000, 1.2090), half: V3(0.2572, 0.7287, 0.2240)),
      Box(center: V3(-1.3028, 1.1660, 1.2090), half: V3(0.8928, 0.2900, 0.1952)),
    ],
    solution: Pose(2.2862, 0.4374, 1.2596),
  ),
  // day 156  ·  approach 0.004
  Level(
    name: 'day 156',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1758, 0.5525, 0.2932)),
      Box(center: V3(0.0000, 0.8841, 0.0000), half: V3(0.2811, 0.2209, 0.6015), hinged: true),
    ],
    solution: Pose(0.5040, -0.7562, 0.8693),
  ),
  // day 157  ·  approach 0.004
  Level(
    name: 'day 157',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2785, 0.1826, 0.7363)),
      Box(center: V3(0.0000, 0.0000, -1.1781), half: V3(0.2723, 0.9011, 0.1911)),
    ],
    solution: Pose(1.8713, -0.1372, 0.0000),
  ),
  // day 158  ·  approach 0.004
  Level(
    name: 'day 158',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2706, 0.6398, 0.1927)),
      Box(center: V3(0.0000, -1.0236, 0.0000), half: V3(0.7627, 0.1827, 0.2667), hinged: true),
    ],
    solution: Pose(2.7368, 0.8246, 0.9152),
  ),
  // day 159  ·  approach 0.004
  Level(
    name: 'day 159',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1788, 0.9077, 0.2977)),
      Box(center: V3(0.0000, 1.4523, 0.0000), half: V3(0.2296, 0.2935, 0.7114), hinged: true),
    ],
    solution: Pose(2.2129, 0.8039, -0.7230),
  ),
  // day 160  ·  approach 0.004
  Level(
    name: 'day 160',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1621, 0.7977, 0.2408)),
      Box(center: V3(0.0000, -1.2763, 0.0000), half: V3(0.1883, 0.2183, 0.9087)),
    ],
    solution: Pose(-1.5704, -0.9428, 0.0000),
  ),
  // day 161  ·  approach 0.004
  Level(
    name: 'day 161',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2938, 0.9324, 0.2340)),
      Box(center: V3(0.0000, 1.4918, 0.0000), half: V3(0.2604, 0.2600, 0.5087), hinged: true),
    ],
    solution: Pose(1.9726, -0.4787, -0.8359),
  ),
  // day 162  ·  approach 0.004
  Level(
    name: 'day 162',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2487, 0.7258, 0.1786)),
      Box(center: V3(0.0000, -1.1613, 0.0000), half: V3(0.5095, 0.2676, 0.1779), hinged: true),
      Box(center: V3(-0.8152, -1.1613, 0.0000), half: V3(0.2657, 0.1766, 0.5861), hinged: true),
      Box(center: V3(-0.8152, -1.1613, 0.9378), half: V3(0.1778, 0.7078, 0.2625)),
    ],
    solution: Pose(2.2499, -0.8139, -0.9832),
  ),
  // day 163  ·  approach 0.004
  Level(
    name: 'day 163',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2864, 0.1896, 0.8171)),
      Box(center: V3(0.0000, 0.0000, -1.3074), half: V3(0.6196, 0.2693, 0.2610)),
    ],
    solution: Pose(-0.9151, -0.0303, 0.0000),
  ),
  // day 164  ·  approach 0.004
  Level(
    name: 'day 164',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8134, 0.2342, 0.2564)),
      Box(center: V3(1.3014, 0.0000, 0.0000), half: V3(0.1992, 0.9021, 0.2838), hinged: true),
      Box(center: V3(1.3014, 1.4434, 0.0000), half: V3(0.9439, 0.2924, 0.1856)),
      Box(center: V3(-0.2089, 1.4434, 0.0000), half: V3(0.2199, 0.2401, 0.8791)),
    ],
    solution: Pose(-0.3384, -0.8028, -1.0631),
  ),
  // day 165  ·  approach 0.004
  Level(
    name: 'day 165',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2852, 0.2025, 0.8215)),
      Box(center: V3(0.0000, 0.0000, -1.3144), half: V3(0.1655, 0.5247, 0.1669), hinged: true),
    ],
    solution: Pose(-2.9815, -0.5651, -1.0645),
  ),
  // day 166  ·  approach 0.004
  Level(
    name: 'day 166',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2815, 0.2109, 0.6402)),
      Box(center: V3(0.0000, 0.0000, -1.0243), half: V3(0.2782, 0.7914, 0.2663)),
      Box(center: V3(0.0000, 1.2662, -1.0243), half: V3(0.5747, 0.1926, 0.2817)),
    ],
    solution: Pose(-3.0581, -0.5936, 0.0000),
  ),
  // day 167  ·  approach 0.004
  Level(
    name: 'day 167',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1989, 0.9221, 0.2972)),
      Box(center: V3(0.0000, -1.4753, 0.0000), half: V3(0.7013, 0.2124, 0.2339), hinged: true),
    ],
    solution: Pose(-0.9637, -0.3739, 0.9725),
  ),
  // day 168  ·  approach 0.004
  Level(
    name: 'day 168',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1733, 0.8754, 0.2209)),
      Box(center: V3(0.0000, -1.4006, 0.0000), half: V3(0.2392, 0.2271, 0.7568), hinged: true),
    ],
    solution: Pose(2.6106, 0.8853, 0.7360),
  ),
  // day 169  ·  approach 0.004
  Level(
    name: 'day 169',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.9149, 0.1745, 0.1806)),
      Box(center: V3(-1.4639, 0.0000, 0.0000), half: V3(0.2606, 0.1994, 0.6424)),
      Box(center: V3(-1.4639, 0.0000, 1.0278), half: V3(0.8390, 0.2640, 0.1877)),
    ],
    solution: Pose(-1.4280, 0.1152, 0.0000),
  ),
  // day 170  ·  approach 0.004
  Level(
    name: 'day 170',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1976, 0.7017, 0.2395)),
      Box(center: V3(0.0000, -1.1228, 0.0000), half: V3(0.2307, 0.1697, 0.8361), hinged: true),
      Box(center: V3(0.0000, -1.1228, -1.3378), half: V3(0.9362, 0.2789, 0.2569)),
      Box(center: V3(-1.4979, -1.1228, -1.3378), half: V3(0.2349, 0.2819, 0.7068)),
    ],
    solution: Pose(2.8393, 0.6637, 0.7578),
  ),
  // day 171  ·  approach 0.004
  Level(
    name: 'day 171',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.9144, 0.1885, 0.2709)),
      Box(center: V3(-1.4630, 0.0000, 0.0000), half: V3(0.2312, 0.1672, 0.6461), hinged: true),
      Box(center: V3(-1.4630, 0.0000, 1.0338), half: V3(0.2243, 0.8809, 0.2510), hinged: true),
      Box(center: V3(-1.4630, 1.4094, 1.0338), half: V3(0.2487, 0.1919, 0.6287)),
    ],
    solution: Pose(-0.8234, -0.1683, -0.8079),
  ),
  // day 172  ·  approach 0.004
  Level(
    name: 'day 172',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2134, 0.2995, 0.6432)),
      Box(center: V3(0.0000, 0.0000, 1.0292), half: V3(0.7005, 0.2295, 0.2944)),
    ],
    solution: Pose(2.0480, 0.0793, 0.0000),
  ),
  // day 173  ·  approach 0.004
  Level(
    name: 'day 173',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1904, 0.2427, 0.5076)),
      Box(center: V3(0.0000, 0.0000, -0.8122), half: V3(0.6385, 0.2656, 0.2307), hinged: true),
    ],
    solution: Pose(-2.4170, -0.5237, -0.9529),
  ),
  // day 174  ·  approach 0.004
  Level(
    name: 'day 174',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8807, 0.2379, 0.2648)),
      Box(center: V3(-1.4092, 0.0000, 0.0000), half: V3(0.2698, 0.7459, 0.1695), hinged: true),
    ],
    solution: Pose(-0.1034, -1.1480, -0.4456),
  ),
  // day 175  ·  approach 0.004
  Level(
    name: 'day 175',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5003, 0.2282, 0.2498)),
      Box(center: V3(0.8004, 0.0000, 0.0000), half: V3(0.2214, 0.9159, 0.2982)),
      Box(center: V3(0.8004, 1.4655, 0.0000), half: V3(0.8642, 0.2781, 0.2504)),
    ],
    solution: Pose(-1.6293, 0.7712, 0.0000),
  ),
  // day 176  ·  approach 0.004
  Level(
    name: 'day 176',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.6568, 0.2100, 0.1609)),
      Box(center: V3(-1.0509, 0.0000, 0.0000), half: V3(0.2703, 0.2784, 0.5683), hinged: true),
      Box(center: V3(-1.0509, 0.0000, 0.9093), half: V3(0.2118, 0.8806, 0.2158)),
    ],
    solution: Pose(-2.1016, -0.7951, -0.0002),
  ),
  // day 177  ·  approach 0.004
  Level(
    name: 'day 177',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1612, 0.5513, 0.2720)),
      Box(center: V3(0.0000, -0.8821, 0.0000), half: V3(0.6256, 0.2623, 0.2317), hinged: true),
      Box(center: V3(-1.0010, -0.8821, 0.0000), half: V3(0.1961, 0.7726, 0.2369), hinged: true),
    ],
    solution: Pose(2.4221, 0.3058, -0.9359),
  ),
  // day 178  ·  approach 0.004
  Level(
    name: 'day 178',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1995, 0.7790, 0.1709)),
      Box(center: V3(0.0000, 1.2464, 0.0000), half: V3(0.2670, 0.2841, 0.6488)),
      Box(center: V3(0.0000, 1.2464, 1.0381), half: V3(0.7824, 0.2767, 0.1835)),
    ],
    solution: Pose(-1.2510, 0.8605, 0.0000),
  ),
  // day 179  ·  approach 0.004
  Level(
    name: 'day 179',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.6636, 0.1974, 0.1624)),
      Box(center: V3(-1.0618, 0.0000, 0.0000), half: V3(0.2664, 0.9125, 0.2827), hinged: true),
      Box(center: V3(-1.0618, 1.4601, 0.0000), half: V3(0.5513, 0.2279, 0.2912)),
      Box(center: V3(-0.1796, 1.4601, 0.0000), half: V3(0.2173, 0.1893, 0.8864)),
    ],
    solution: Pose(1.8364, 0.5701, -1.0457),
  ),
  // day 180  ·  approach 0.004
  Level(
    name: 'day 180',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2049, 0.7509, 0.1763)),
      Box(center: V3(0.0000, 1.2014, 0.0000), half: V3(0.2798, 0.2269, 0.8355), hinged: true),
    ],
    solution: Pose(2.0305, -0.3732, 1.0485),
  ),
];
