// GENERATED by tool/gen_levels.dart — do not edit by hand.
//
// Every level here survived rejection sampling: it is not solved
// at the opening pose, its solution basin is narrow enough to be a
// puzzle and wide enough to be findable, and its two walls are
// measurably independent — which is what the hand-authored Tee
// failed. Ordered easiest first within each chapter.
import 'geom.dart';
import 'level.dart';

const generatedLevels = <Level>[
  // #1  approach 0.036 · correlation 0.53
  Level(
    name: '1',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1981, 0.5433, 0.2714)),
      Box(center: V3(0.0000, 0.8693, 0.0000), half: V3(0.5657, 0.2973, 0.1630)),
    ],
    solution: Pose(-2.1503, 0.5569, 0.0000),
  ),
  // #2  approach 0.032 · correlation 0.67
  Level(
    name: '2',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2819, 0.9151, 0.2049)),
      Box(center: V3(0.0000, -1.4641, 0.0000), half: V3(0.5019, 0.2459, 0.1603)),
    ],
    solution: Pose(-0.3322, -0.5508, 0.0000),
  ),
  // #3  approach 0.024 · correlation 0.75
  Level(
    name: '3',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1808, 0.7408, 0.2545)),
      Box(center: V3(0.0000, -1.1852, 0.0000), half: V3(0.7225, 0.2407, 0.1675)),
    ],
    solution: Pose(-3.0350, -0.3674, 0.0000),
  ),
  // #4  approach 0.024 · correlation 1.00
  Level(
    name: '4',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2815, 0.6951, 0.2760)),
      Box(center: V3(0.0000, 1.1121, 0.0000), half: V3(0.7379, 0.2445, 0.2706)),
    ],
    solution: Pose(3.0225, -0.8292, 0.0000),
  ),
  // #5  approach 0.020 · correlation 0.63
  Level(
    name: '5',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2942, 0.9218, 0.2053)),
      Box(center: V3(0.0000, 1.4749, 0.0000), half: V3(0.1998, 0.2637, 0.7969)),
    ],
    solution: Pose(2.8908, -0.8606, 0.0000),
  ),
  // #6  approach 0.016 · correlation 0.80
  Level(
    name: '6',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2087, 0.6995, 0.1685)),
      Box(center: V3(0.0000, 1.1192, 0.0000), half: V3(0.1904, 0.1909, 0.8483)),
    ],
    solution: Pose(-1.7973, -0.3436, 0.0000),
  ),
  // #7  approach 0.012 · correlation 0.50
  Level(
    name: '7',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.6386, 0.2974, 0.2118)),
      Box(center: V3(1.0217, 0.0000, 0.0000), half: V3(0.2413, 0.2623, 0.8173)),
    ],
    solution: Pose(-0.3938, -0.1037, 0.0000),
  ),
  // #8  approach 0.008 · correlation 1.00
  Level(
    name: '8',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5326, 0.1902, 0.2346)),
      Box(center: V3(0.8521, 0.0000, 0.0000), half: V3(0.2481, 0.2310, 0.5857)),
      Box(center: V3(0.8521, 0.0000, 0.9371), half: V3(0.7228, 0.2082, 0.1709)),
    ],
    solution: Pose(2.9019, 0.2789, 0.0000),
  ),
  // #9  approach 0.008 · correlation 0.67
  Level(
    name: '9',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2441, 0.2660, 0.9456)),
      Box(center: V3(0.0000, 0.0000, -1.5130), half: V3(0.2264, 0.7250, 0.1875)),
      Box(center: V3(0.0000, -1.1599, -1.5130), half: V3(0.2692, 0.2757, 0.7475)),
      Box(center: V3(0.0000, -1.1599, -2.7091), half: V3(0.5327, 0.1611, 0.2958)),
    ],
    solution: Pose(-1.5672, 0.1955, 0.0000),
  ),
  // #10  approach 0.008 · correlation 0.22
  Level(
    name: '10',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2752, 0.6838, 0.2387)),
      Box(center: V3(0.0000, -1.0941, 0.0000), half: V3(0.7422, 0.1811, 0.1971)),
      Box(center: V3(1.1875, -1.0941, 0.0000), half: V3(0.2417, 0.2000, 0.6883)),
    ],
    solution: Pose(2.7260, 0.0126, 0.0000),
  ),
  // #11  approach 0.008 · correlation 0.40
  Level(
    name: '11',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8576, 0.1869, 0.2172)),
      Box(center: V3(1.3722, 0.0000, 0.0000), half: V3(0.2585, 0.7483, 0.1611)),
    ],
    solution: Pose(1.5399, 1.0972, 0.0000),
  ),
  // #12  approach 0.004 · correlation 1.00
  Level(
    name: '12',
    hint: 'Both walls, one pose.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7057, 0.2375, 0.2854)),
      Box(center: V3(-1.1292, 0.0000, 0.0000), half: V3(0.2092, 0.2671, 0.5037)),
      Box(center: V3(-1.1292, 0.0000, 0.8060), half: V3(0.1610, 0.6292, 0.2092)),
      Box(center: V3(-1.1292, 1.0068, 0.8060), half: V3(0.2596, 0.1931, 0.7579)),
    ],
    solution: Pose(-0.2015, -1.1590, 0.0000),
  ),
  // #13  approach 0.012 · correlation 0.60
  Level(
    name: '13',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2086, 0.7133, 0.2706)),
      Box(center: V3(0.0000, -1.1413, 0.0000), half: V3(0.2270, 0.1697, 0.9236), hinged: true),
    ],
    solution: Pose(1.9251, -0.3653, -0.2941),
  ),
  // #14  approach 0.008 · correlation 1.00
  Level(
    name: '14',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2960, 0.8356, 0.2584)),
      Box(center: V3(0.0000, -1.3370, 0.0000), half: V3(0.2538, 0.2382, 0.8969), hinged: true),
    ],
    solution: Pose(3.0699, -0.6570, 0.5758),
  ),
  // #15  approach 0.004 · correlation 1.00
  Level(
    name: '15',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1626, 0.8454, 0.2416)),
      Box(center: V3(0.0000, 1.3526, 0.0000), half: V3(0.5264, 0.2908, 0.2527), hinged: true),
    ],
    solution: Pose(-2.9342, -0.2459, -0.6184),
  ),
  // #16  approach 0.004 · correlation 1.00
  Level(
    name: '16',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.6385, 0.1730, 0.1749)),
      Box(center: V3(1.0216, 0.0000, 0.0000), half: V3(0.2073, 0.2017, 0.5600), hinged: true),
      Box(center: V3(1.0216, 0.0000, -0.8960), half: V3(0.1910, 0.6618, 0.2723)),
      Box(center: V3(1.0216, 1.0590, -0.8960), half: V3(0.5912, 0.2728, 0.1649)),
    ],
    solution: Pose(0.1383, 0.0105, 0.4232),
  ),
  // #17  approach 0.004 · correlation 1.00
  Level(
    name: '17',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1949, 0.2788, 0.6372)),
      Box(center: V3(0.0000, 0.0000, -1.0195), half: V3(0.6893, 0.2312, 0.2955), hinged: true),
    ],
    solution: Pose(3.1208, 0.9432, -0.3017),
  ),
  // #18  approach 0.004 · correlation 1.00
  Level(
    name: '18',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2565, 0.2615, 0.6260)),
      Box(center: V3(0.0000, 0.0000, -1.0016), half: V3(0.2733, 0.5857, 0.2681), hinged: true),
      Box(center: V3(0.0000, -0.9371, -1.0016), half: V3(0.7502, 0.2472, 0.2917)),
    ],
    solution: Pose(2.0872, 0.6382, -0.2785),
  ),
  // #19  approach 0.004 · correlation 0.50
  Level(
    name: '19',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1678, 0.9457, 0.2868)),
      Box(center: V3(0.0000, 1.5132, 0.0000), half: V3(0.2320, 0.2484, 0.6025), hinged: true),
    ],
    solution: Pose(-1.8952, -0.0811, 0.5354),
  ),
  // #20  approach 0.004 · correlation 1.00
  Level(
    name: '20',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7876, 0.2948, 0.2797)),
      Box(center: V3(-1.2601, 0.0000, 0.0000), half: V3(0.2906, 0.2124, 0.6411), hinged: true),
    ],
    solution: Pose(-1.9703, 0.0665, 0.6707),
  ),
  // #21  approach 0.004 · correlation 0.50
  Level(
    name: '21',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2224, 0.5683, 0.1863)),
      Box(center: V3(0.0000, 0.9093, 0.0000), half: V3(0.1654, 0.2817, 0.8142), hinged: true),
      Box(center: V3(0.0000, 0.9093, 1.3027), half: V3(0.1712, 0.9241, 0.2705)),
    ],
    solution: Pose(-1.6013, -0.4664, -1.0996),
  ),
  // #22  approach 0.004 · correlation 1.00
  Level(
    name: '22',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2442, 0.1878, 0.7021)),
      Box(center: V3(0.0000, 0.0000, 1.1234), half: V3(0.2909, 0.6199, 0.1805), hinged: true),
    ],
    solution: Pose(-2.4952, 0.9658, 0.9185),
  ),
  // #23  approach 0.004 · correlation 1.00
  Level(
    name: '23',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2317, 0.7171, 0.2318)),
      Box(center: V3(0.0000, 1.1474, 0.0000), half: V3(0.1925, 0.1680, 0.5821), hinged: true),
    ],
    solution: Pose(-1.1899, -0.9860, 1.2837),
  ),
  // #24  approach 0.004 · correlation 1.00
  Level(
    name: '24',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7540, 0.2861, 0.1715)),
      Box(center: V3(1.2065, 0.0000, 0.0000), half: V3(0.2073, 0.2831, 0.6602), hinged: true),
      Box(center: V3(1.2065, 0.0000, 1.0563), half: V3(0.2376, 0.7201, 0.2766)),
      Box(center: V3(1.2065, 1.1522, 1.0563), half: V3(0.6037, 0.1960, 0.1703)),
    ],
    solution: Pose(0.6199, -0.3797, 1.0481),
  ),
  // #25  approach 0.008 · correlation 1.00
  Level(
    name: '25',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2809, 0.1609, 0.5406)),
      Box(center: V3(0.0000, 0.0000, -0.8649), half: V3(0.5391, 0.2592, 0.2327), hinged: true),
    ],
    solution: Pose(0.6091, -0.6082, 0.0054),
  ),
  // #26  approach 0.008 · correlation 0.50
  Level(
    name: '26',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2909, 0.7050, 0.2473)),
      Box(center: V3(0.0000, -1.1280, 0.0000), half: V3(0.2928, 0.2304, 0.7881), hinged: true),
    ],
    solution: Pose(-2.6291, 0.1011, 0.9421),
  ),
  // #27  approach 0.004 · correlation 1.00
  Level(
    name: '27',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5897, 0.1887, 0.2558)),
      Box(center: V3(0.9435, 0.0000, 0.0000), half: V3(0.1919, 0.1906, 0.7296), hinged: true),
    ],
    solution: Pose(-2.5029, 1.0199, 0.6142),
  ),
  // #28  approach 0.004 · correlation 0.33
  Level(
    name: '28',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2810, 0.8513, 0.2524)),
      Box(center: V3(0.0000, 1.3620, 0.0000), half: V3(0.5425, 0.2790, 0.2522), hinged: true),
      Box(center: V3(-0.8680, 1.3620, 0.0000), half: V3(0.1836, 0.2817, 0.5223), hinged: true),
    ],
    solution: Pose(-0.5620, 0.3104, -0.5940),
  ),
  // #29  approach 0.004 · correlation 1.00
  Level(
    name: '29',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7237, 0.1725, 0.1897)),
      Box(center: V3(1.1579, 0.0000, 0.0000), half: V3(0.2764, 0.7423, 0.2858), hinged: true),
    ],
    solution: Pose(-0.7431, 0.9368, -0.6261),
  ),
  // #30  approach 0.004 · correlation 1.00
  Level(
    name: '30',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.6637, 0.1832, 0.2534)),
      Box(center: V3(1.0619, 0.0000, 0.0000), half: V3(0.2566, 0.9281, 0.2231), hinged: true),
      Box(center: V3(1.0619, 1.4850, 0.0000), half: V3(0.2292, 0.2749, 0.6364), hinged: true),
    ],
    solution: Pose(2.2349, -0.0251, 0.1043),
  ),
  // #31  approach 0.004 · correlation 1.00
  Level(
    name: '31',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8738, 0.2398, 0.2285)),
      Box(center: V3(1.3981, 0.0000, 0.0000), half: V3(0.1731, 0.6122, 0.2101), hinged: true),
    ],
    solution: Pose(1.9088, -0.6210, -1.2849),
  ),
  // #32  approach 0.004 · correlation 1.00
  Level(
    name: '32',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7800, 0.2543, 0.2295)),
      Box(center: V3(-1.2480, 0.0000, 0.0000), half: V3(0.1896, 0.5535, 0.2058), hinged: true),
      Box(center: V3(-1.2480, 0.8856, 0.0000), half: V3(0.6458, 0.1756, 0.2329), hinged: true),
      Box(center: V3(-0.2147, 0.8856, 0.0000), half: V3(0.2340, 0.2570, 0.9470)),
    ],
    solution: Pose(2.8594, -1.0070, 0.6970),
  ),
  // #33  approach 0.004 · correlation 1.00
  Level(
    name: '33',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1737, 0.2614, 0.8149)),
      Box(center: V3(0.0000, 0.0000, -1.3038), half: V3(0.5138, 0.1784, 0.1665), hinged: true),
    ],
    solution: Pose(-0.1940, -0.1462, -0.7822),
  ),
  // #34  approach 0.004 · correlation 0.50
  Level(
    name: '34',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8027, 0.2653, 0.2055)),
      Box(center: V3(-1.2843, 0.0000, 0.0000), half: V3(0.1856, 0.5343, 0.2412), hinged: true),
    ],
    solution: Pose(2.4106, 0.6122, 0.7969),
  ),
  // #35  approach 0.004 · correlation 1.00
  Level(
    name: '35',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2359, 0.9244, 0.2492)),
      Box(center: V3(0.0000, -1.4790, 0.0000), half: V3(0.8118, 0.2183, 0.1936), hinged: true),
    ],
    solution: Pose(2.7980, 0.1297, -0.8978),
  ),
  // #36  approach 0.004 · correlation 1.00
  Level(
    name: '36',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2184, 0.2249, 0.7910)),
      Box(center: V3(0.0000, 0.0000, -1.2656), half: V3(0.6276, 0.2315, 0.2999), hinged: true),
      Box(center: V3(-1.0041, 0.0000, -1.2656), half: V3(0.2975, 0.9022, 0.1901), hinged: true),
      Box(center: V3(-1.0041, -1.4435, -1.2656), half: V3(0.1973, 0.2963, 0.6897)),
    ],
    solution: Pose(0.5832, -0.0006, 0.0232),
  ),
];
