// GENERATED by tool/gen_levels_ext.dart — do not edit by hand.
//
// The mixed-shape chapters. Same rejection sampling as
// levels.g.dart — not solved at the opening pose, basin narrow
// enough to be a puzzle and wide enough to be findable — but cut
// from rods, wedges, bulbs, hexes and the three concave shapes
// rather than boxes alone. Ordered easiest first within each
// chapter, on the same `approach` metric.
//
// Pieces are emitted as recipes, not vertices: one lathe is ~90
// points and baking them would make this file a megabyte of
// source nobody can read or diff. `piece()` rebuilds them.
//
// ⚠️ APPEND ONLY — this list is the tail of the save format.
import 'generator.dart';
import 'geom.dart';
import 'level.dart';

final extendedLevels = <Level>[
  // ── THE ROD ────────────────────────────────────────
  // #47  approach 0.084 · correlation 0.91
  Level(
    name: '47',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2479, 0.9310, 0.2185), axis: 1),
      piece(Shape.box, V3(0.0000, 1.4896, 0.0000), V3(0.2677, 0.5905, 0.2444), axis: 2),
    ],
    solution: Pose(2.4259, 0.4429, 0.0000),
  ),
  // #48  approach 0.076 · correlation 0.54
  Level(
    name: '48',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2372, 0.5037, 0.2497), axis: 1),
      piece(Shape.rod, V3(0.0000, -0.8059, 0.0000), V3(0.1875, 0.5242, 0.2266), axis: 0),
    ],
    solution: Pose(2.6612, -0.3980, 0.0000),
  ),
  // #49  approach 0.064 · correlation 0.89
  Level(
    name: '49',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2161, 0.5630, 0.2732), axis: 1),
      piece(Shape.box, V3(0.0000, -0.9007, 0.0000), V3(0.1940, 0.5146, 0.2859), axis: 2),
    ],
    solution: Pose(-0.5253, -0.4527, 0.0000),
  ),
  // #50  approach 0.064 · correlation 0.50
  Level(
    name: '50',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2803, 0.6837, 0.2160), axis: 1),
      piece(Shape.rod, V3(0.0000, 1.0939, 0.0000), V3(0.1925, 0.7414, 0.1511), axis: 2),
    ],
    solution: Pose(2.0619, -0.4753, 0.0000),
  ),
  // #51  approach 0.044 · correlation 0.48
  Level(
    name: '51',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2731, 0.6628, 0.2387), axis: 1),
      piece(Shape.rod, V3(0.0000, 1.0605, 0.0000), V3(0.2894, 0.5134, 0.2474), axis: 2),
    ],
    solution: Pose(2.3989, 1.0947, 0.0000),
  ),
  // #52  approach 0.040 · correlation 0.34
  Level(
    name: '52',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1619, 0.6583, 0.2681), axis: 1),
      piece(Shape.rod, V3(0.0000, -1.0533, 0.0000), V3(0.2019, 0.5005, 0.1514), axis: 2),
    ],
    solution: Pose(-0.4995, 0.3873, 0.0000),
  ),
  // #53  approach 0.036 · correlation 0.45
  Level(
    name: '53',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2461, 0.9104, 0.1622), axis: 1),
      piece(Shape.box, V3(0.0000, -1.4567, 0.0000), V3(0.2944, 0.5569, 0.1706), axis: 0),
    ],
    solution: Pose(0.4891, 1.0997, 0.0000),
  ),
  // #54  approach 0.032 · correlation 0.44
  Level(
    name: '54',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2722, 0.7422, 0.2056), axis: 1),
      piece(Shape.rod, V3(0.0000, -1.1876, 0.0000), V3(0.2175, 0.9331, 0.2057), axis: 2),
    ],
    solution: Pose(-0.9128, -0.6043, 0.0000),
  ),
  // #55  approach 0.016 · correlation 0.24
  Level(
    name: '55',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2018, 0.7677, 0.2333), axis: 1),
      piece(Shape.box, V3(0.0000, -1.2283, 0.0000), V3(0.2539, 0.6228, 0.2889), axis: 0),
      piece(Shape.rod, V3(-0.9965, -1.2283, 0.0000), V3(0.2730, 0.7658, 0.1872), axis: 2),
    ],
    solution: Pose(2.1587, 0.1279, 0.0000),
  ),
  // #56  approach 0.016 · correlation 0.67
  Level(
    name: '56',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1903, 0.7027, 0.2579), axis: 1),
      piece(Shape.rod, V3(0.0000, -1.1243, 0.0000), V3(0.2483, 0.6773, 0.1713), axis: 0),
    ],
    solution: Pose(-3.0962, 1.0592, 0.0000),
  ),
  // #57  approach 0.012 · correlation 1.00
  Level(
    name: '57',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.1965, 0.5962, 0.2142), axis: 0),
      piece(Shape.rod, V3(-0.9539, 0.0000, 0.0000), V3(0.1675, 0.5594, 0.1782), axis: 1),
    ],
    solution: Pose(3.0322, 0.3501, 0.0000),
  ),
  // #58  approach 0.012 · correlation 0.60
  Level(
    name: '58',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.1823, 0.5432, 0.1827), axis: 2),
      piece(Shape.box, V3(0.0000, 0.0000, 0.8691), V3(0.2772, 0.8651, 0.1837), axis: 0),
    ],
    solution: Pose(-2.1988, 0.9059, 0.0000),
  ),
  // #59  approach 0.008 · correlation 0.67
  Level(
    name: '59',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2937, 0.8784, 0.2103), axis: 2),
      piece(Shape.rod, V3(0.0000, 0.0000, 1.4054), V3(0.1965, 0.8967, 0.2724), axis: 1),
      piece(Shape.rod, V3(0.0000, -1.4347, 1.4054), V3(0.2759, 0.7644, 0.2832), axis: 0),
    ],
    solution: Pose(-2.9044, -0.9515, 0.0000),
  ),
  // #60  approach 0.008 · correlation 0.67
  Level(
    name: '60',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2079, 0.8000, 0.2025), axis: 0),
      piece(Shape.box, V3(-1.2801, 0.0000, 0.0000), V3(0.2848, 0.7335, 0.1615), axis: 1),
      piece(Shape.rod, V3(-1.2801, -1.1737, 0.0000), V3(0.2321, 0.8645, 0.2784), axis: 0),
    ],
    solution: Pose(2.2058, -0.6200, 0.0000),
  ),
  // #61  approach 0.008 · correlation 0.50
  Level(
    name: '61',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.1645, 0.5077, 0.1762), axis: 0),
      piece(Shape.rod, V3(-0.8124, 0.0000, 0.0000), V3(0.2508, 0.6482, 0.1794), axis: 1),
    ],
    solution: Pose(0.8532, 0.4796, 0.0000),
  ),
  // #62  approach 0.008 · correlation 0.50
  Level(
    name: '62',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2586, 0.6779, 0.2282), axis: 2),
      piece(Shape.box, V3(0.0000, 0.0000, 1.0846), V3(0.2040, 0.6172, 0.2221), axis: 1),
    ],
    solution: Pose(-1.5126, 0.8531, 0.0000),
  ),
  // #63  approach 0.008 · correlation 0.33
  Level(
    name: '63',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2827, 0.5976, 0.2203), axis: 2),
      piece(Shape.rod, V3(0.0000, 0.0000, -0.9561), V3(0.2458, 0.6723, 0.1931), axis: 0),
    ],
    solution: Pose(-0.9253, 1.0120, 0.0000),
  ),
  // #64  approach 0.008 · correlation 1.00
  Level(
    name: '64',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2396, 0.7046, 0.2374), axis: 0),
      piece(Shape.box, V3(1.1273, 0.0000, 0.0000), V3(0.2904, 0.9067, 0.2977), axis: 1),
      piece(Shape.rod, V3(1.1273, -1.4507, 0.0000), V3(0.2189, 0.7229, 0.2145), axis: 2),
    ],
    solution: Pose(1.3655, -1.0390, 0.0000),
  ),
  // #65  approach 0.004 · correlation 0.33
  Level(
    name: '65',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.1662, 0.6161, 0.1598), axis: 1),
      piece(Shape.rod, V3(0.0000, 0.9858, 0.0000), V3(0.2227, 0.5168, 0.2138), axis: 2),
      piece(Shape.rod, V3(0.0000, 0.9858, 0.8269), V3(0.2809, 0.6520, 0.2792), axis: 1),
    ],
    solution: Pose(2.4373, 0.6597, 0.0000),
  ),
  // #66  approach 0.004 · correlation 1.00
  Level(
    name: '66',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2887, 0.7573, 0.1807), axis: 2),
      piece(Shape.rod, V3(0.0000, 0.0000, 1.2116), V3(0.2779, 0.6329, 0.1894), axis: 0),
      piece(Shape.box, V3(1.0126, 0.0000, 1.2116), V3(0.1618, 0.8079, 0.2400), axis: 1),
    ],
    solution: Pose(0.2096, -0.8492, 0.0000),
  ),
  // #67  approach 0.004 · correlation 0.50
  Level(
    name: '67',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1970, 0.7929, 0.2956), axis: 0),
      piece(Shape.rod, V3(1.2687, 0.0000, 0.0000), V3(0.2359, 0.5533, 0.1979), axis: 1),
      piece(Shape.box, V3(1.2687, 0.8853, 0.0000), V3(0.2912, 0.8847, 0.1849), axis: 0),
    ],
    solution: Pose(-1.9252, 0.5979, 0.0000),
  ),
  // #68  approach 0.004 · correlation 0.50
  Level(
    name: '68',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.1661, 0.6358, 0.1725), axis: 1),
      piece(Shape.rod, V3(0.0000, -1.0173, 0.0000), V3(0.1930, 0.6292, 0.2119), axis: 0),
    ],
    solution: Pose(-3.1048, -0.8757, 0.0000),
  ),
  // #69  approach 0.004 · correlation 0.33
  Level(
    name: '69',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2940, 0.5307, 0.2105), axis: 0),
      piece(Shape.rod, V3(0.8491, 0.0000, 0.0000), V3(0.2314, 0.6858, 0.2755), axis: 1),
      piece(Shape.rod, V3(0.8491, -1.0973, 0.0000), V3(0.2975, 0.9380, 0.2487), axis: 0),
    ],
    solution: Pose(2.3727, -0.3109, 0.0000),
  ),
  // #70  approach 0.004 · correlation 1.00
  Level(
    name: '70',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.1728, 0.8985, 0.2291), axis: 0),
      piece(Shape.rod, V3(1.4376, 0.0000, 0.0000), V3(0.2354, 0.6881, 0.1892), axis: 1),
      piece(Shape.box, V3(1.4376, -1.1010, 0.0000), V3(0.1934, 0.5284, 0.2720), axis: 2),
      piece(Shape.rod, V3(1.4376, -1.1010, 0.8455), V3(0.1999, 0.8422, 0.1927), axis: 0),
    ],
    solution: Pose(1.6007, 0.9260, 0.0000),
  ),
  // #71  approach 0.004 · correlation 0.33
  Level(
    name: '71',
    hint: 'Round from every side but one.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2197, 0.5664, 0.2279), axis: 0),
      piece(Shape.rod, V3(0.9063, 0.0000, 0.0000), V3(0.2996, 0.5207, 0.2350), axis: 2),
    ],
    solution: Pose(-2.7333, -1.1055, 0.0000),
  ),
  // ── THE WEDGE ────────────────────────────────────────
  // #72  approach 0.068 · correlation 0.63
  Level(
    name: '72',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.1723, 0.8821, 0.1684), axis: 1),
      piece(Shape.wedge, V3(0.0000, 1.4114, 0.0000), V3(0.1601, 0.9011, 0.2426), axis: 2),
    ],
    solution: Pose(2.3318, -0.0562, 0.0000),
  ),
  // #73  approach 0.048 · correlation 0.63
  Level(
    name: '73',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.2593, 0.6527, 0.1932), axis: 1),
      piece(Shape.hex, V3(0.0000, -1.0443, 0.0000), V3(0.2046, 0.6428, 0.1930), axis: 2),
    ],
    solution: Pose(1.0980, 0.0752, 0.0000),
  ),
  // #74  approach 0.028 · correlation 0.54
  Level(
    name: '74',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.1916, 0.7203, 0.2600), axis: 1),
      piece(Shape.wedge, V3(0.0000, -1.1525, 0.0000), V3(0.2319, 0.5429, 0.2896), axis: 0),
    ],
    solution: Pose(2.1312, 0.0544, 0.0000),
  ),
  // #75  approach 0.028 · correlation 0.78
  Level(
    name: '75',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2221, 0.6365, 0.2521), axis: 1),
      piece(Shape.wedge, V3(0.0000, 1.0184, 0.0000), V3(0.2342, 0.8015, 0.2335), axis: 0),
    ],
    solution: Pose(-1.3636, -0.1520, 0.0000),
  ),
  // #76  approach 0.024 · correlation 0.60
  Level(
    name: '76',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2179, 0.8865, 0.1914), axis: 1),
      piece(Shape.hex, V3(0.0000, 1.4184, 0.0000), V3(0.2981, 0.8730, 0.2338), axis: 0),
    ],
    solution: Pose(1.9106, -0.8966, 0.0000),
  ),
  // #77  approach 0.020 · correlation 0.38
  Level(
    name: '77',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2490, 0.8081, 0.2102), axis: 1),
      piece(Shape.wedge, V3(0.0000, -1.2930, 0.0000), V3(0.2776, 0.5108, 0.2906), axis: 0),
    ],
    solution: Pose(-0.2169, -1.0053, 0.0000),
  ),
  // #78  approach 0.020 · correlation 0.56
  Level(
    name: '78',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2036, 0.9046, 0.1783), axis: 1),
      piece(Shape.box, V3(0.0000, 1.4474, 0.0000), V3(0.2892, 0.7193, 0.1623), axis: 2),
    ],
    solution: Pose(-1.0638, -0.3506, 0.0000),
  ),
  // #79  approach 0.020 · correlation 0.33
  Level(
    name: '79',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2234, 0.5587, 0.2486), axis: 1),
      piece(Shape.wedge, V3(0.0000, -0.8939, 0.0000), V3(0.1797, 0.7004, 0.1702), axis: 2),
    ],
    solution: Pose(-0.7278, 0.5343, 0.0000),
  ),
  // #80  approach 0.016 · correlation 0.57
  Level(
    name: '80',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.2236, 0.9244, 0.2954), axis: 1),
      piece(Shape.box, V3(0.0000, 1.4791, 0.0000), V3(0.1755, 0.7635, 0.1677), axis: 2),
    ],
    solution: Pose(-0.0809, -0.3416, 0.0000),
  ),
  // #81  approach 0.016 · correlation 0.80
  Level(
    name: '81',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.1804, 0.8047, 0.1645), axis: 1),
      piece(Shape.box, V3(0.0000, -1.2876, 0.0000), V3(0.1708, 0.7103, 0.2695), axis: 0),
      piece(Shape.hex, V3(1.1366, -1.2876, 0.0000), V3(0.2178, 0.5503, 0.2276), axis: 2),
    ],
    solution: Pose(0.0319, 0.8134, 0.0000),
  ),
  // #82  approach 0.016 · correlation 0.29
  Level(
    name: '82',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.2146, 0.8585, 0.2113), axis: 1),
      piece(Shape.box, V3(0.0000, 1.3736, 0.0000), V3(0.2503, 0.5595, 0.1771), axis: 2),
    ],
    solution: Pose(-0.1634, 0.3274, 0.0000),
  ),
  // #83  approach 0.012 · correlation 1.00
  Level(
    name: '83',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.2357, 0.6041, 0.2242), axis: 1),
      piece(Shape.wedge, V3(0.0000, -0.9665, 0.0000), V3(0.2768, 0.7409, 0.1983), axis: 2),
      piece(Shape.hex, V3(0.0000, -0.9665, -1.1855), V3(0.1681, 0.6073, 0.1924), axis: 0),
      piece(Shape.hex, V3(0.9717, -0.9665, -1.1855), V3(0.1956, 0.8198, 0.2324), axis: 1),
    ],
    solution: Pose(0.1454, 0.6653, 0.0000),
  ),
  // #84  approach 0.012 · correlation 0.75
  Level(
    name: '84',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2125, 0.6385, 0.1520), axis: 0),
      piece(Shape.wedge, V3(1.0216, 0.0000, 0.0000), V3(0.2712, 0.7348, 0.1670), axis: 1),
    ],
    solution: Pose(2.9015, 0.9018, 0.0000),
  ),
  // #85  approach 0.008 · correlation 0.67
  Level(
    name: '85',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2946, 0.8844, 0.1783), axis: 0),
      piece(Shape.hex, V3(1.4151, 0.0000, 0.0000), V3(0.1934, 0.6859, 0.2438), axis: 1),
    ],
    solution: Pose(-3.0111, -0.1718, 0.0000),
  ),
  // #86  approach 0.008 · correlation 0.67
  Level(
    name: '86',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2565, 0.6998, 0.2204), axis: 1),
      piece(Shape.wedge, V3(0.0000, -1.1197, 0.0000), V3(0.2838, 0.8971, 0.2725), axis: 0),
      piece(Shape.wedge, V3(1.4354, -1.1197, 0.0000), V3(0.2608, 0.8953, 0.2826), axis: 2),
    ],
    solution: Pose(0.2425, -0.5050, 0.0000),
  ),
  // #87  approach 0.008 · correlation 0.67
  Level(
    name: '87',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.2395, 0.8130, 0.2144), axis: 0),
      piece(Shape.wedge, V3(1.3008, 0.0000, 0.0000), V3(0.2639, 0.5847, 0.1997), axis: 2),
    ],
    solution: Pose(-0.1666, -1.0809, 0.0000),
  ),
  // #88  approach 0.008 · correlation 0.40
  Level(
    name: '88',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.2181, 0.7009, 0.1848), axis: 0),
      piece(Shape.box, V3(1.1215, 0.0000, 0.0000), V3(0.1956, 0.5325, 0.2493), axis: 2),
    ],
    solution: Pose(-2.6441, 0.5663, 0.0000),
  ),
  // #89  approach 0.008 · correlation 0.50
  Level(
    name: '89',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2870, 0.5217, 0.1946), axis: 2),
      piece(Shape.hex, V3(0.0000, 0.0000, -0.8347), V3(0.1869, 0.5758, 0.2774), axis: 1),
    ],
    solution: Pose(-2.4774, 0.5216, 0.0000),
  ),
  // #90  approach 0.004 · correlation 0.25
  Level(
    name: '90',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2075, 0.7565, 0.1638), axis: 0),
      piece(Shape.wedge, V3(-1.2104, 0.0000, 0.0000), V3(0.2852, 0.5344, 0.2559), axis: 1),
    ],
    solution: Pose(0.2042, -0.8321, 0.0000),
  ),
  // #91  approach 0.004 · correlation 1.00
  Level(
    name: '91',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.1623, 0.8323, 0.1741), axis: 1),
      piece(Shape.box, V3(0.0000, -1.3317, 0.0000), V3(0.1958, 0.8662, 0.2671), axis: 2),
      piece(Shape.wedge, V3(0.0000, -1.3317, -1.3860), V3(0.1608, 0.5156, 0.2200), axis: 1),
      piece(Shape.wedge, V3(0.0000, -0.5068, -1.3860), V3(0.2772, 0.8290, 0.2939), axis: 2),
    ],
    solution: Pose(0.9427, 0.6098, 0.0000),
  ),
  // #92  approach 0.004 · correlation 0.33
  Level(
    name: '92',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.2988, 0.7868, 0.2188), axis: 0),
      piece(Shape.wedge, V3(1.2588, 0.0000, 0.0000), V3(0.2960, 0.7841, 0.2943), axis: 1),
      piece(Shape.hex, V3(1.2588, -1.2546, 0.0000), V3(0.1653, 0.6123, 0.2537), axis: 0),
    ],
    solution: Pose(-0.0422, 0.9028, 0.0000),
  ),
  // #93  approach 0.004 · correlation 1.00
  Level(
    name: '93',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.1733, 0.5318, 0.2786), axis: 0),
      piece(Shape.wedge, V3(-0.8508, 0.0000, 0.0000), V3(0.1640, 0.6344, 0.1760), axis: 2),
      piece(Shape.wedge, V3(-0.8508, 0.0000, -1.0151), V3(0.1617, 0.7224, 0.2154), axis: 1),
    ],
    solution: Pose(1.7928, -0.0259, 0.0000),
  ),
  // #94  approach 0.004 · correlation 0.50
  Level(
    name: '94',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1698, 0.7028, 0.2449), axis: 1),
      piece(Shape.box, V3(0.0000, -1.1245, 0.0000), V3(0.1681, 0.8739, 0.2326), axis: 2),
      piece(Shape.box, V3(0.0000, -1.1245, 1.3983), V3(0.1646, 0.6026, 0.2321), axis: 1),
      piece(Shape.wedge, V3(0.0000, -2.0888, 1.3983), V3(0.1881, 0.6022, 0.1707), axis: 0),
    ],
    solution: Pose(2.5705, 0.4850, 0.0000),
  ),
  // #95  approach 0.004 · correlation 1.00
  Level(
    name: '95',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.2809, 0.7481, 0.1926), axis: 2),
      piece(Shape.box, V3(0.0000, 0.0000, -1.1970), V3(0.2858, 0.7409, 0.2086), axis: 1),
      piece(Shape.hex, V3(0.0000, -1.1855, -1.1970), V3(0.2064, 0.5232, 0.1867), axis: 2),
    ],
    solution: Pose(1.4630, -0.1001, 0.0000),
  ),
  // #96  approach 0.004 · correlation 0.50
  Level(
    name: '96',
    hint: 'A triangle here is a rectangle there.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2394, 0.5721, 0.2152), axis: 2),
      piece(Shape.wedge, V3(0.0000, 0.0000, -0.9154), V3(0.1770, 0.7150, 0.2523), axis: 1),
      piece(Shape.box, V3(0.0000, -1.1440, -0.9154), V3(0.2952, 0.6803, 0.2712), axis: 2),
    ],
    solution: Pose(-2.6517, 0.4105, 0.0000),
  ),
  // ── THE BULB ────────────────────────────────────────
  // #97  approach 0.016 · correlation 0.80
  Level(
    name: '97',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2998, 0.5785, 0.2232), axis: 1),
      piece(Shape.rod, V3(0.0000, -0.9256, 0.0000), V3(0.2261, 0.8530, 0.2381), axis: 0, hinged: true),
    ],
    solution: Pose(2.4687, 0.0029, -0.8982),
  ),
  // #98  approach 0.012 · correlation 1.00
  Level(
    name: '98',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1939, 0.5586, 0.2278), axis: 0),
      piece(Shape.rod, V3(-0.8937, 0.0000, 0.0000), V3(0.2279, 0.5676, 0.1755), axis: 2, hinged: true),
    ],
    solution: Pose(0.6668, 0.6843, 1.0818),
  ),
  // #99  approach 0.008 · correlation 1.00
  Level(
    name: '99',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2262, 0.9478, 0.2156), axis: 1),
      piece(Shape.bulb, V3(0.0000, -1.5165, 0.0000), V3(0.1861, 0.6956, 0.2111), axis: 0, hinged: true),
      piece(Shape.box, V3(-1.1130, -1.5165, 0.0000), V3(0.2145, 0.6948, 0.2508), axis: 2),
      piece(Shape.box, V3(-1.1130, -1.5165, 1.1116), V3(0.2108, 0.5072, 0.1640), axis: 0),
    ],
    solution: Pose(-2.7591, -0.4526, -0.2804),
  ),
  // #100  approach 0.008 · correlation 0.67
  Level(
    name: '100',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2443, 0.7094, 0.1744), axis: 1),
      piece(Shape.box, V3(0.0000, 1.1351, 0.0000), V3(0.2586, 0.6862, 0.2222), axis: 2, hinged: true),
    ],
    solution: Pose(-0.3972, -0.6882, 1.2962),
  ),
  // #101  approach 0.008 · correlation 0.40
  Level(
    name: '101',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2463, 0.5291, 0.2805), axis: 0),
      piece(Shape.bulb, V3(-0.8466, 0.0000, 0.0000), V3(0.2386, 0.5899, 0.1722), axis: 2, hinged: true),
    ],
    solution: Pose(-0.9290, -0.4945, 0.6315),
  ),
  // #102  approach 0.008 · correlation 1.00
  Level(
    name: '102',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.1915, 0.9482, 0.2029), axis: 1),
      piece(Shape.bulb, V3(0.0000, 1.5171, 0.0000), V3(0.2725, 0.9197, 0.1810), axis: 2, hinged: true),
    ],
    solution: Pose(-3.0658, 0.9402, -0.6467),
  ),
  // #103  approach 0.004 · correlation 1.00
  Level(
    name: '103',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2324, 0.5787, 0.2081), axis: 1),
      piece(Shape.box, V3(0.0000, 0.9258, 0.0000), V3(0.2059, 0.8407, 0.1522), axis: 2, hinged: true),
    ],
    solution: Pose(1.5898, -0.5998, 0.1227),
  ),
  // #104  approach 0.004 · correlation 1.00
  Level(
    name: '104',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1880, 0.6254, 0.2768), axis: 2),
      piece(Shape.box, V3(0.0000, 0.0000, 1.0006), V3(0.2894, 0.7060, 0.2175), axis: 1, hinged: true),
    ],
    solution: Pose(-0.6262, 0.9391, -0.7595),
  ),
  // #105  approach 0.004 · correlation 1.00
  Level(
    name: '105',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.bulb, V3(0.0000, 0.0000, 0.0000), V3(0.1635, 0.6850, 0.1880), axis: 1),
      piece(Shape.bulb, V3(0.0000, 1.0960, 0.0000), V3(0.2043, 0.8576, 0.1767), axis: 0, hinged: true),
    ],
    solution: Pose(-2.6685, 0.5128, -0.0717),
  ),
  // #106  approach 0.004 · correlation 1.00
  Level(
    name: '106',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2431, 0.6342, 0.1545), axis: 0),
      piece(Shape.bulb, V3(1.0147, 0.0000, 0.0000), V3(0.2839, 0.5586, 0.2276), axis: 1, hinged: true),
    ],
    solution: Pose(-2.9627, -0.9357, -0.4052),
  ),
  // #107  approach 0.004 · correlation 1.00
  Level(
    name: '107',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.bulb, V3(0.0000, 0.0000, 0.0000), V3(0.1858, 0.5213, 0.1806), axis: 2),
      piece(Shape.bulb, V3(0.0000, 0.0000, -0.8341), V3(0.2507, 0.5644, 0.2968), axis: 0, hinged: true),
    ],
    solution: Pose(-1.5082, -0.5516, -1.2577),
  ),
  // #108  approach 0.004 · correlation 0.50
  Level(
    name: '108',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2406, 0.5040, 0.1629), axis: 1),
      piece(Shape.rod, V3(0.0000, -0.8063, 0.0000), V3(0.2626, 0.5361, 0.2927), axis: 2, hinged: true),
    ],
    solution: Pose(-1.5864, 0.7206, -1.1929),
  ),
  // #109  approach 0.004 · correlation 1.00
  Level(
    name: '109',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.bulb, V3(0.0000, 0.0000, 0.0000), V3(0.2005, 0.6950, 0.2284), axis: 1),
      piece(Shape.rod, V3(0.0000, 1.1120, 0.0000), V3(0.2189, 0.6878, 0.2566), axis: 0, hinged: true),
    ],
    solution: Pose(-2.4513, 0.6252, -1.0802),
  ),
  // #110  approach 0.004 · correlation 0.33
  Level(
    name: '110',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.bulb, V3(0.0000, 0.0000, 0.0000), V3(0.2584, 0.5624, 0.1623), axis: 1),
      piece(Shape.bulb, V3(0.0000, -0.8999, 0.0000), V3(0.2264, 0.6175, 0.2029), axis: 2, hinged: true),
    ],
    solution: Pose(2.2961, 0.4957, 0.0614),
  ),
  // #111  approach 0.004 · correlation 1.00
  Level(
    name: '111',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.bulb, V3(0.0000, 0.0000, 0.0000), V3(0.1866, 0.7907, 0.2744), axis: 0),
      piece(Shape.bulb, V3(1.2652, 0.0000, 0.0000), V3(0.2715, 0.5600, 0.2099), axis: 2, hinged: true),
      piece(Shape.bulb, V3(1.2652, 0.0000, -0.8960), V3(0.1809, 0.5824, 0.1765), axis: 1),
    ],
    solution: Pose(0.6501, -0.0863, 0.5902),
  ),
  // #112  approach 0.004 · correlation 1.00
  Level(
    name: '112',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.bulb, V3(0.0000, 0.0000, 0.0000), V3(0.1998, 0.9481, 0.2618), axis: 1),
      piece(Shape.bulb, V3(0.0000, 1.5170, 0.0000), V3(0.2674, 0.8203, 0.2788), axis: 0, hinged: true),
      piece(Shape.rod, V3(-1.3125, 1.5170, 0.0000), V3(0.2618, 0.5332, 0.2680), axis: 2),
    ],
    solution: Pose(2.6862, 0.4836, 0.7517),
  ),
  // #113  approach 0.004 · correlation 0.50
  Level(
    name: '113',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2625, 0.8810, 0.2332), axis: 1),
      piece(Shape.bulb, V3(0.0000, -1.4095, 0.0000), V3(0.2103, 0.8755, 0.2656), axis: 0, hinged: true),
    ],
    solution: Pose(1.2078, 0.3798, -0.0207),
  ),
  // #114  approach 0.004 · correlation 1.00
  Level(
    name: '114',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.bulb, V3(0.0000, 0.0000, 0.0000), V3(0.1868, 0.6291, 0.2736), axis: 1),
      piece(Shape.box, V3(0.0000, -1.0065, 0.0000), V3(0.2627, 0.7593, 0.2992), axis: 2, hinged: true),
    ],
    solution: Pose(2.0974, 0.6487, 1.2731),
  ),
  // #115  approach 0.004 · correlation 1.00
  Level(
    name: '115',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.bulb, V3(0.0000, 0.0000, 0.0000), V3(0.2719, 0.6774, 0.2185), axis: 1),
      piece(Shape.bulb, V3(0.0000, -1.0838, 0.0000), V3(0.2805, 0.5920, 0.2087), axis: 0, hinged: true),
      piece(Shape.bulb, V3(-0.9472, -1.0838, 0.0000), V3(0.1975, 0.7659, 0.2561), axis: 1),
    ],
    solution: Pose(-0.1262, 0.8189, 0.7496),
  ),
  // #116  approach 0.004 · correlation 1.00
  Level(
    name: '116',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.1690, 0.6604, 0.2495), axis: 0),
      piece(Shape.bulb, V3(-1.0566, 0.0000, 0.0000), V3(0.1868, 0.5724, 0.2144), axis: 2, hinged: true),
      piece(Shape.bulb, V3(-1.0566, 0.0000, 0.9159), V3(0.2094, 0.6506, 0.2654), axis: 1),
    ],
    solution: Pose(-1.0911, 0.2830, -0.4192),
  ),
  // #117  approach 0.004 · correlation 1.00
  Level(
    name: '117',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2396, 0.5341, 0.2168), axis: 1),
      piece(Shape.rod, V3(0.0000, 0.8545, 0.0000), V3(0.2126, 0.6855, 0.2581), axis: 2, hinged: true),
    ],
    solution: Pose(-1.1731, -1.1911, 0.3490),
  ),
  // #118  approach 0.004 · correlation 1.00
  Level(
    name: '118',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2218, 0.7699, 0.2984), axis: 1),
      piece(Shape.bulb, V3(0.0000, -1.2318, 0.0000), V3(0.1714, 0.5056, 0.2288), axis: 0, hinged: true),
    ],
    solution: Pose(0.9674, 0.7431, 0.5542),
  ),
  // #119  approach 0.004 · correlation 0.50
  Level(
    name: '119',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.bulb, V3(0.0000, 0.0000, 0.0000), V3(0.1800, 0.5130, 0.2919), axis: 2),
      piece(Shape.box, V3(0.0000, 0.0000, 0.8207), V3(0.1798, 0.5765, 0.1968), axis: 0, hinged: true),
    ],
    solution: Pose(-0.6723, -0.2667, 1.1556),
  ),
  // #120  approach 0.004 · correlation 1.00
  Level(
    name: '120',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2538, 0.6799, 0.2658), axis: 2),
      piece(Shape.box, V3(0.0000, 0.0000, 1.0878), V3(0.2421, 0.8361, 0.2986), axis: 1, hinged: true),
    ],
    solution: Pose(-0.9920, 0.9174, -0.6708),
  ),
  // #121  approach 0.004 · correlation 1.00
  Level(
    name: '121',
    hint: 'No straight edge to line up. Use the width.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2070, 0.6792, 0.2842), axis: 2),
      piece(Shape.bulb, V3(0.0000, 0.0000, -1.0867), V3(0.2833, 0.8144, 0.1594), axis: 0, hinged: true),
    ],
    solution: Pose(-2.7220, 0.3761, -0.6631),
  ),
  // ── THE ANGLE ────────────────────────────────────────
  // #122  approach 0.012 · correlation 0.60
  Level(
    name: '122',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2670, 0.5318, 0.2093), axis: 1),
      piece(Shape.tee, V3(0.0000, 0.8509, 0.0000), V3(0.2677, 0.5176, 0.2307), axis: 0, hinged: true),
      piece(Shape.box, V3(0.8282, 0.8509, 0.0000), V3(0.2080, 0.8928, 0.2751), axis: 2),
      piece(Shape.box, V3(0.8282, 0.8509, 1.4284), V3(0.2699, 0.6799, 0.1973), axis: 0),
    ],
    solution: Pose(-2.6927, -0.0398, -0.8175),
  ),
  // #123  approach 0.008 · correlation 0.40
  Level(
    name: '123',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2363, 0.6062, 0.2259), axis: 1),
      piece(Shape.box, V3(0.0000, 0.9699, 0.0000), V3(0.2985, 0.6460, 0.1876), axis: 0, hinged: true),
    ],
    solution: Pose(0.8244, -0.9561, 1.0487),
  ),
  // #124  approach 0.008 · correlation 0.50
  Level(
    name: '124',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2194, 0.5620, 0.1861), axis: 1),
      piece(Shape.tee, V3(0.0000, 0.8992, 0.0000), V3(0.2237, 0.7241, 0.2773), axis: 2, hinged: true),
    ],
    solution: Pose(-2.4437, 0.4576, -0.4034),
  ),
  // #125  approach 0.008 · correlation 1.00
  Level(
    name: '125',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.tee, V3(0.0000, 0.0000, 0.0000), V3(0.2569, 0.6264, 0.2687), axis: 0),
      piece(Shape.box, V3(1.0023, 0.0000, 0.0000), V3(0.2981, 0.5012, 0.2610), axis: 1, hinged: true),
      piece(Shape.box, V3(1.0023, 0.8019, 0.0000), V3(0.2727, 0.8427, 0.2454), axis: 2),
      piece(Shape.tee, V3(1.0023, 0.8019, -1.3483), V3(0.1860, 0.7968, 0.2177), axis: 0),
    ],
    solution: Pose(-1.8791, 0.0525, 0.6102),
  ),
  // #126  approach 0.008 · correlation 1.00
  Level(
    name: '126',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1832, 0.8740, 0.2337), axis: 2),
      piece(Shape.box, V3(0.0000, 0.0000, 1.3984), V3(0.1621, 0.8087, 0.2625), axis: 0, hinged: true),
    ],
    solution: Pose(-1.8577, 0.9324, -0.9843),
  ),
  // #127  approach 0.008 · correlation 0.50
  Level(
    name: '127',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2785, 0.8748, 0.2576), axis: 1),
      piece(Shape.box, V3(0.0000, 1.3997, 0.0000), V3(0.1877, 0.6321, 0.2259), axis: 0, hinged: true),
    ],
    solution: Pose(-2.4873, 0.3449, 0.0595),
  ),
  // #128  approach 0.008 · correlation 1.00
  Level(
    name: '128',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.tee, V3(0.0000, 0.0000, 0.0000), V3(0.2296, 0.5895, 0.2312), axis: 0),
      piece(Shape.box, V3(0.9432, 0.0000, 0.0000), V3(0.1825, 0.7337, 0.1643), axis: 1, hinged: true),
      piece(Shape.ell, V3(0.9432, -1.1739, 0.0000), V3(0.2530, 0.5249, 0.2797), axis: 2),
      piece(Shape.box, V3(0.9432, -1.1739, 0.8399), V3(0.2829, 0.9121, 0.2306), axis: 1),
    ],
    solution: Pose(1.2731, -0.8481, -0.2767),
  ),
  // #129  approach 0.008 · correlation 1.00
  Level(
    name: '129',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2611, 0.5630, 0.2972), axis: 0),
      piece(Shape.box, V3(0.9008, 0.0000, 0.0000), V3(0.2463, 0.5945, 0.1834), axis: 2, hinged: true),
      piece(Shape.box, V3(0.9008, 0.0000, -0.9512), V3(0.2101, 0.6523, 0.2185), axis: 0),
      piece(Shape.box, V3(-0.1429, 0.0000, -0.9512), V3(0.2576, 0.6837, 0.1777), axis: 1),
    ],
    solution: Pose(2.8683, 0.7587, 0.2790),
  ),
  // #130  approach 0.004 · correlation 1.00
  Level(
    name: '130',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1926, 0.6603, 0.2935), axis: 0),
      piece(Shape.ell, V3(-1.0565, 0.0000, 0.0000), V3(0.2174, 0.8614, 0.2890), axis: 1, hinged: true),
    ],
    solution: Pose(0.3628, 0.9501, -0.9977),
  ),
  // #131  approach 0.004 · correlation 1.00
  Level(
    name: '131',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2919, 0.6419, 0.1969), axis: 2),
      piece(Shape.tee, V3(0.0000, 0.0000, 1.0271), V3(0.2493, 0.7706, 0.1889), axis: 0, hinged: true),
    ],
    solution: Pose(-2.4368, -0.3454, 1.0097),
  ),
  // #132  approach 0.004 · correlation 1.00
  Level(
    name: '132',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1650, 0.8915, 0.2196), axis: 0),
      piece(Shape.box, V3(-1.4265, 0.0000, 0.0000), V3(0.2217, 0.8532, 0.2789), axis: 1, hinged: true),
    ],
    solution: Pose(-0.6365, -0.3240, 0.3496),
  ),
  // #133  approach 0.004 · correlation 1.00
  Level(
    name: '133',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1909, 0.6900, 0.2328), axis: 0),
      piece(Shape.ell, V3(1.1040, 0.0000, 0.0000), V3(0.2269, 0.7961, 0.2415), axis: 1, hinged: true),
      piece(Shape.box, V3(1.1040, -1.2738, 0.0000), V3(0.2893, 0.8389, 0.2418), axis: 0),
      piece(Shape.box, V3(2.4462, -1.2738, 0.0000), V3(0.2297, 0.9354, 0.1997), axis: 2),
    ],
    solution: Pose(2.7411, -0.0156, -0.3360),
  ),
  // #134  approach 0.004 · correlation 0.50
  Level(
    name: '134',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1790, 0.6518, 0.2435), axis: 1),
      piece(Shape.tee, V3(0.0000, -1.0429, 0.0000), V3(0.1950, 0.8479, 0.2550), axis: 0, hinged: true),
    ],
    solution: Pose(-0.6341, -0.7059, -1.2702),
  ),
  // #135  approach 0.004 · correlation 1.00
  Level(
    name: '135',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2365, 0.7811, 0.2743), axis: 0),
      piece(Shape.ell, V3(-1.2497, 0.0000, 0.0000), V3(0.1768, 0.5475, 0.2415), axis: 1, hinged: true),
    ],
    solution: Pose(2.2108, 0.1005, -0.2241),
  ),
  // #136  approach 0.004 · correlation 1.00
  Level(
    name: '136',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2186, 0.5389, 0.2208), axis: 1),
      piece(Shape.ell, V3(0.0000, -0.8622, 0.0000), V3(0.2132, 0.6065, 0.1603), axis: 0, hinged: true),
      piece(Shape.ell, V3(-0.9704, -0.8622, 0.0000), V3(0.2852, 0.7397, 0.2721), axis: 1),
      piece(Shape.box, V3(-0.9704, 0.3214, 0.0000), V3(0.2843, 0.6187, 0.2139), axis: 2),
    ],
    solution: Pose(0.0754, -1.1482, 0.1189),
  ),
  // #137  approach 0.004 · correlation 1.00
  Level(
    name: '137',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.tee, V3(0.0000, 0.0000, 0.0000), V3(0.1653, 0.5690, 0.2776), axis: 0),
      piece(Shape.ell, V3(0.9105, 0.0000, 0.0000), V3(0.1898, 0.7540, 0.2048), axis: 1, hinged: true),
    ],
    solution: Pose(2.3642, -1.1753, 0.6110),
  ),
  // #138  approach 0.004 · correlation 0.50
  Level(
    name: '138',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2533, 0.5889, 0.1513), axis: 0),
      piece(Shape.ell, V3(0.9422, 0.0000, 0.0000), V3(0.2621, 0.5328, 0.1655), axis: 1, hinged: true),
      piece(Shape.ell, V3(0.9422, -0.8525, 0.0000), V3(0.2888, 0.7265, 0.2410), axis: 0),
    ],
    solution: Pose(0.3946, 0.8310, -0.9250),
  ),
  // #139  approach 0.004 · correlation 1.00
  Level(
    name: '139',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1747, 0.7455, 0.1569), axis: 0),
      piece(Shape.box, V3(1.1928, 0.0000, 0.0000), V3(0.2502, 0.6822, 0.1945), axis: 1, hinged: true),
      piece(Shape.ell, V3(1.1928, -1.0916, 0.0000), V3(0.1977, 0.6612, 0.2882), axis: 2),
      piece(Shape.box, V3(1.1928, -1.0916, -1.0580), V3(0.2828, 0.6868, 0.2213), axis: 1),
    ],
    solution: Pose(2.0102, 0.0199, -0.8929),
  ),
  // #140  approach 0.004 · correlation 1.00
  Level(
    name: '140',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2902, 0.5014, 0.2899), axis: 0),
      piece(Shape.tee, V3(-0.8023, 0.0000, 0.0000), V3(0.1692, 0.8963, 0.2767), axis: 2, hinged: true),
    ],
    solution: Pose(0.8141, 0.0741, 0.2444),
  ),
  // #141  approach 0.004 · correlation 1.00
  Level(
    name: '141',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2494, 0.6824, 0.2413), axis: 1),
      piece(Shape.ell, V3(0.0000, 1.0919, 0.0000), V3(0.2901, 0.6331, 0.2087), axis: 0, hinged: true),
      piece(Shape.box, V3(1.0130, 1.0919, 0.0000), V3(0.1715, 0.8137, 0.2894), axis: 1),
    ],
    solution: Pose(2.0521, 0.6556, 0.7647),
  ),
  // #142  approach 0.004 · correlation 1.00
  Level(
    name: '142',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.ell, V3(0.0000, 0.0000, 0.0000), V3(0.2142, 0.5076, 0.2413), axis: 0),
      piece(Shape.box, V3(0.8122, 0.0000, 0.0000), V3(0.1881, 0.6202, 0.1593), axis: 1, hinged: true),
    ],
    solution: Pose(-2.9662, -0.6949, -1.1567),
  ),
  // #143  approach 0.004 · correlation 1.00
  Level(
    name: '143',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.ell, V3(0.0000, 0.0000, 0.0000), V3(0.2291, 0.6995, 0.1961), axis: 2),
      piece(Shape.tee, V3(0.0000, 0.0000, -1.1192), V3(0.2379, 0.5294, 0.2614), axis: 1, hinged: true),
    ],
    solution: Pose(0.6267, -0.3133, -0.9852),
  ),
  // #144  approach 0.004 · correlation 1.00
  Level(
    name: '144',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.ell, V3(0.0000, 0.0000, 0.0000), V3(0.1663, 0.9015, 0.1638), axis: 1),
      piece(Shape.ell, V3(0.0000, 1.4425, 0.0000), V3(0.1880, 0.7713, 0.2334), axis: 0, hinged: true),
    ],
    solution: Pose(2.5530, -0.9097, -0.4818),
  ),
  // #145  approach 0.004 · correlation 1.00
  Level(
    name: '145',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.ell, V3(0.0000, 0.0000, 0.0000), V3(0.2141, 0.8473, 0.2992), axis: 0),
      piece(Shape.box, V3(-1.3556, 0.0000, 0.0000), V3(0.1768, 0.6378, 0.2185), axis: 1, hinged: true),
      piece(Shape.box, V3(-1.3556, 1.0205, 0.0000), V3(0.2782, 0.5879, 0.2542), axis: 0),
    ],
    solution: Pose(0.0447, 1.0007, 1.2640),
  ),
  // #146  approach 0.004 · correlation 1.00
  Level(
    name: '146',
    hint: 'The notch has to land somewhere.',
    boxes: [
      piece(Shape.ell, V3(0.0000, 0.0000, 0.0000), V3(0.2139, 0.8118, 0.2787), axis: 1),
      piece(Shape.box, V3(0.0000, 1.2989, 0.0000), V3(0.1871, 0.7203, 0.2969), axis: 2, hinged: true),
    ],
    solution: Pose(1.1455, -0.3056, -1.1416),
  ),
  // ── THE ARROW ────────────────────────────────────────
  // #147  approach 0.012 · correlation 1.00
  Level(
    name: '147',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2541, 0.7140, 0.2161), axis: 1),
      piece(Shape.chevron, V3(0.0000, -1.1424, 0.0000), V3(0.1833, 0.5882, 0.2860), axis: 2, hinged: true),
    ],
    solution: Pose(-0.1125, -0.3436, 0.2358),
  ),
  // #148  approach 0.008 · correlation 0.33
  Level(
    name: '148',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1982, 0.9136, 0.2871), axis: 1),
      piece(Shape.chevron, V3(0.0000, -1.4618, 0.0000), V3(0.1672, 0.6263, 0.2731), axis: 0, hinged: true),
    ],
    solution: Pose(-1.8537, -0.7829, 0.3479),
  ),
  // #149  approach 0.008 · correlation 0.67
  Level(
    name: '149',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.0000), V3(0.1884, 0.7329, 0.2163), axis: 0),
      piece(Shape.wedge, V3(1.1726, 0.0000, 0.0000), V3(0.2902, 0.5056, 0.2462), axis: 2, hinged: true),
      piece(Shape.chevron, V3(1.1726, 0.0000, -0.8089), V3(0.1948, 0.6653, 0.1576), axis: 1),
      piece(Shape.box, V3(1.1726, -1.0644, -0.8089), V3(0.2273, 0.8396, 0.2310), axis: 0),
    ],
    solution: Pose(1.9517, -0.7994, -0.2124),
  ),
  // #150  approach 0.008 · correlation 1.00
  Level(
    name: '150',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.0000), V3(0.2219, 0.7751, 0.2626), axis: 1),
      piece(Shape.box, V3(0.0000, -1.2402, 0.0000), V3(0.2519, 0.8698, 0.2329), axis: 0, hinged: true),
    ],
    solution: Pose(-2.6497, -0.2776, -1.2938),
  ),
  // #151  approach 0.008 · correlation 1.00
  Level(
    name: '151',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.0000), V3(0.2830, 0.7142, 0.2963), axis: 0),
      piece(Shape.box, V3(1.1427, 0.0000, 0.0000), V3(0.1620, 0.9039, 0.1549), axis: 2, hinged: true),
    ],
    solution: Pose(-0.1152, 0.8079, 0.6914),
  ),
  // #152  approach 0.004 · correlation 1.00
  Level(
    name: '152',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.0000), V3(0.2028, 0.6512, 0.2503), axis: 0),
      piece(Shape.box, V3(1.0419, 0.0000, 0.0000), V3(0.1960, 0.9274, 0.2508), axis: 2, hinged: true),
      piece(Shape.box, V3(1.0419, 0.0000, 1.4838), V3(0.2095, 0.6320, 0.2570), axis: 0),
    ],
    solution: Pose(-0.3863, 0.0330, 1.0284),
  ),
  // #153  approach 0.004 · correlation 1.00
  Level(
    name: '153',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2767, 0.6226, 0.2377), axis: 0),
      piece(Shape.box, V3(-0.9961, 0.0000, 0.0000), V3(0.2562, 0.7572, 0.2946), axis: 1, hinged: true),
      piece(Shape.chevron, V3(-0.9961, 1.2115, 0.0000), V3(0.2677, 0.9446, 0.1713), axis: 0),
    ],
    solution: Pose(2.5097, 0.0098, 1.0217),
  ),
  // #154  approach 0.004 · correlation 0.50
  Level(
    name: '154',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2176, 0.5350, 0.2566), axis: 1),
      piece(Shape.chevron, V3(0.0000, -0.8560, 0.0000), V3(0.2626, 0.8542, 0.1629), axis: 0, hinged: true),
    ],
    solution: Pose(-2.0987, 0.1190, -0.8173),
  ),
  // #155  approach 0.004 · correlation 1.00
  Level(
    name: '155',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2677, 0.7260, 0.1900), axis: 0),
      piece(Shape.chevron, V3(1.1616, 0.0000, 0.0000), V3(0.2618, 0.8491, 0.1729), axis: 2, hinged: true),
    ],
    solution: Pose(-1.6951, 0.8026, -0.3902),
  ),
  // #156  approach 0.004 · correlation 0.33
  Level(
    name: '156',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2809, 0.7637, 0.2467), axis: 1),
      piece(Shape.box, V3(0.0000, -1.2220, 0.0000), V3(0.2238, 0.5537, 0.2152), axis: 2, hinged: true),
    ],
    solution: Pose(-1.1871, 1.1123, -0.5988),
  ),
  // #157  approach 0.004 · correlation 1.00
  Level(
    name: '157',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1643, 0.8037, 0.1752), axis: 0),
      piece(Shape.wedge, V3(-1.2859, 0.0000, 0.0000), V3(0.2373, 0.6699, 0.2191), axis: 2, hinged: true),
    ],
    solution: Pose(3.1384, -0.4986, -0.5059),
  ),
  // #158  approach 0.004 · correlation 1.00
  Level(
    name: '158',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2361, 0.8671, 0.2624), axis: 1),
      piece(Shape.chevron, V3(0.0000, 1.3873, 0.0000), V3(0.1722, 0.5202, 0.2483), axis: 2, hinged: true),
      piece(Shape.box, V3(0.0000, 1.3873, -0.8323), V3(0.2094, 0.6169, 0.1514), axis: 0),
      piece(Shape.chevron, V3(-0.9870, 1.3873, -0.8323), V3(0.1931, 0.7990, 0.2194), axis: 1),
    ],
    solution: Pose(-0.9563, 0.7598, -0.1353),
  ),
  // #159  approach 0.004 · correlation 1.00
  Level(
    name: '159',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2636, 0.6149, 0.1616), axis: 1),
      piece(Shape.chevron, V3(0.0000, 0.9838, 0.0000), V3(0.1725, 0.5152, 0.2738), axis: 2, hinged: true),
      piece(Shape.chevron, V3(0.0000, 0.9838, 0.8243), V3(0.2251, 0.8969, 0.1572), axis: 1),
      piece(Shape.wedge, V3(0.0000, 2.4188, 0.8243), V3(0.2618, 0.6870, 0.2721), axis: 2),
    ],
    solution: Pose(-0.0341, 0.7995, -0.2484),
  ),
  // #160  approach 0.004 · correlation 1.00
  Level(
    name: '160',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2153, 0.7479, 0.2451), axis: 1),
      piece(Shape.box, V3(0.0000, 1.1967, 0.0000), V3(0.2833, 0.9274, 0.2195), axis: 2, hinged: true),
      piece(Shape.chevron, V3(0.0000, 1.1967, -1.4839), V3(0.2143, 0.5541, 0.2930), axis: 0),
      piece(Shape.wedge, V3(0.8865, 1.1967, -1.4839), V3(0.2799, 0.9377, 0.2770), axis: 2),
    ],
    solution: Pose(2.8332, 0.6249, 0.6088),
  ),
  // #161  approach 0.004 · correlation 1.00
  Level(
    name: '161',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.0000), V3(0.2759, 0.6932, 0.1740), axis: 1),
      piece(Shape.wedge, V3(0.0000, -1.1091, 0.0000), V3(0.2594, 0.8621, 0.2166), axis: 2, hinged: true),
    ],
    solution: Pose(1.8984, 0.6178, 1.2142),
  ),
  // #162  approach 0.004 · correlation 1.00
  Level(
    name: '162',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2822, 0.8710, 0.2145), axis: 1),
      piece(Shape.chevron, V3(0.0000, 1.3936, 0.0000), V3(0.1684, 0.9018, 0.2442), axis: 2, hinged: true),
      piece(Shape.box, V3(0.0000, 1.3936, -1.4429), V3(0.2467, 0.5136, 0.1726), axis: 1),
      piece(Shape.wedge, V3(0.0000, 0.5719, -1.4429), V3(0.2002, 0.6006, 0.2345), axis: 0),
    ],
    solution: Pose(2.1126, 0.0049, 0.9162),
  ),
  // #163  approach 0.004 · correlation 1.00
  Level(
    name: '163',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2416, 0.8133, 0.2550), axis: 1),
      piece(Shape.chevron, V3(0.0000, 1.3013, 0.0000), V3(0.2798, 0.7725, 0.2682), axis: 0, hinged: true),
    ],
    solution: Pose(-1.7372, -0.5720, 0.2464),
  ),
  // #164  approach 0.004 · correlation 0.25
  Level(
    name: '164',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2394, 0.9001, 0.1720), axis: 1),
      piece(Shape.box, V3(0.0000, 1.4402, 0.0000), V3(0.2687, 0.6910, 0.2140), axis: 0, hinged: true),
    ],
    solution: Pose(0.6876, -0.2667, 0.2878),
  ),
  // #165  approach 0.004 · correlation 1.00
  Level(
    name: '165',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2551, 0.7134, 0.2065), axis: 0),
      piece(Shape.wedge, V3(1.1415, 0.0000, 0.0000), V3(0.2622, 0.5039, 0.2773), axis: 1, hinged: true),
      piece(Shape.wedge, V3(1.1415, -0.8063, 0.0000), V3(0.2068, 0.7823, 0.1736), axis: 2),
    ],
    solution: Pose(-2.3882, 0.4234, -0.4999),
  ),
  // #166  approach 0.004 · correlation 1.00
  Level(
    name: '166',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2224, 0.7938, 0.2809), axis: 1),
      piece(Shape.chevron, V3(0.0000, -1.2701, 0.0000), V3(0.2734, 0.8114, 0.1961), axis: 0, hinged: true),
      piece(Shape.wedge, V3(1.2982, -1.2701, 0.0000), V3(0.2003, 0.8463, 0.2546), axis: 1),
      piece(Shape.box, V3(1.2982, 0.0840, 0.0000), V3(0.1942, 0.8852, 0.2700), axis: 0),
    ],
    solution: Pose(2.1740, 0.3015, 0.9362),
  ),
  // #167  approach 0.004 · correlation 1.00
  Level(
    name: '167',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2958, 0.8535, 0.2488), axis: 0),
      piece(Shape.box, V3(-1.3656, 0.0000, 0.0000), V3(0.1853, 0.7554, 0.1647), axis: 1, hinged: true),
      piece(Shape.wedge, V3(-1.3656, 1.2086, 0.0000), V3(0.2631, 0.5884, 0.2016), axis: 0),
      piece(Shape.chevron, V3(-2.3069, 1.2086, 0.0000), V3(0.1617, 0.6471, 0.1572), axis: 1),
    ],
    solution: Pose(-1.8571, 0.3688, -0.2607),
  ),
  // #168  approach 0.004 · correlation 1.00
  Level(
    name: '168',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.0000), V3(0.2471, 0.7137, 0.2121), axis: 0),
      piece(Shape.wedge, V3(-1.1420, 0.0000, 0.0000), V3(0.2121, 0.7125, 0.2486), axis: 1, hinged: true),
    ],
    solution: Pose(2.4371, 0.2898, -0.1947),
  ),
  // #169  approach 0.004 · correlation 0.50
  Level(
    name: '169',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.0000), V3(0.2750, 0.5466, 0.1660), axis: 0),
      piece(Shape.chevron, V3(0.8745, 0.0000, 0.0000), V3(0.1698, 0.5569, 0.2411), axis: 2, hinged: true),
    ],
    solution: Pose(0.0189, 0.5058, -0.4182),
  ),
  // #170  approach 0.004 · correlation 1.00
  Level(
    name: '170',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1706, 0.8405, 0.2926), axis: 1),
      piece(Shape.wedge, V3(0.0000, 1.3448, 0.0000), V3(0.2300, 0.8296, 0.2111), axis: 0, hinged: true),
      piece(Shape.chevron, V3(1.3273, 1.3448, 0.0000), V3(0.2092, 0.5583, 0.2931), axis: 1),
      piece(Shape.chevron, V3(1.3273, 0.4515, 0.0000), V3(0.2559, 0.6780, 0.2580), axis: 2),
    ],
    solution: Pose(0.3791, -0.0365, -0.5689),
  ),
  // #171  approach 0.004 · correlation 1.00
  Level(
    name: '171',
    hint: 'Both shadows point. Rarely the same way.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2087, 0.5813, 0.1748), axis: 2),
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.9300), V3(0.2746, 0.6276, 0.1590), axis: 0, hinged: true),
      piece(Shape.wedge, V3(1.0042, 0.0000, 0.9300), V3(0.2121, 0.8839, 0.2022), axis: 2),
    ],
    solution: Pose(-2.6234, -1.0582, 1.1447),
  ),
  // ── ASSEMBLY ────────────────────────────────────────
  // #172  approach 0.016 · correlation 1.00
  Level(
    name: '172',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.2225, 0.5151, 0.2786), axis: 1),
      piece(Shape.hex, V3(0.0000, 0.8241, 0.0000), V3(0.2154, 0.5354, 0.2481), axis: 0, hinged: true),
      piece(Shape.hex, V3(0.8566, 0.8241, 0.0000), V3(0.1880, 0.5392, 0.1804), axis: 2, hinged: true),
      piece(Shape.box, V3(0.8566, 0.8241, 0.8628), V3(0.2243, 0.6791, 0.1674), axis: 0),
    ],
    solution: Pose(-2.4445, -0.1552, 0.6800),
  ),
  // #173  approach 0.012 · correlation 1.00
  Level(
    name: '173',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.1798, 0.5698, 0.1729), axis: 2),
      piece(Shape.wedge, V3(0.0000, 0.0000, -0.9117), V3(0.2898, 0.5648, 0.2072), axis: 1, hinged: true),
      piece(Shape.wedge, V3(0.0000, -0.9036, -0.9117), V3(0.2025, 0.5373, 0.2598), axis: 2, hinged: true),
      piece(Shape.rod, V3(0.0000, -0.9036, -0.0520), V3(0.2553, 0.8980, 0.1896), axis: 1),
    ],
    solution: Pose(-2.2286, -0.8328, -0.3731),
  ),
  // #174  approach 0.012 · correlation 0.75
  Level(
    name: '174',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2414, 0.6237, 0.2269), axis: 0),
      piece(Shape.box, V3(-0.9979, 0.0000, 0.0000), V3(0.2574, 0.5151, 0.1579), axis: 1, hinged: true),
    ],
    solution: Pose(3.1306, -0.4152, -0.9895),
  ),
  // #175  approach 0.012 · correlation 0.75
  Level(
    name: '175',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2154, 0.5898, 0.2037), axis: 1),
      piece(Shape.box, V3(0.0000, 0.9437, 0.0000), V3(0.1870, 0.6229, 0.2273), axis: 0, hinged: true),
    ],
    solution: Pose(2.4919, 0.0178, 0.1271),
  ),
  // #176  approach 0.008 · correlation 1.00
  Level(
    name: '176',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2691, 0.5002, 0.2331), axis: 1),
      piece(Shape.rod, V3(0.0000, 0.8004, 0.0000), V3(0.2259, 0.5805, 0.2454), axis: 0, hinged: true),
      piece(Shape.hex, V3(-0.9288, 0.8004, 0.0000), V3(0.2719, 0.5025, 0.2782), axis: 2, hinged: true),
    ],
    solution: Pose(-0.0657, -0.2233, 0.0170),
  ),
  // #177  approach 0.008 · correlation 1.00
  Level(
    name: '177',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2209, 0.6150, 0.1682), axis: 2),
      piece(Shape.box, V3(0.0000, 0.0000, -0.9840), V3(0.1637, 0.7334, 0.2833), axis: 0, hinged: true),
    ],
    solution: Pose(-2.0520, 1.1560, -0.1081),
  ),
  // #178  approach 0.008 · correlation 1.00
  Level(
    name: '178',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2860, 0.6894, 0.2670), axis: 0),
      piece(Shape.box, V3(-1.1030, 0.0000, 0.0000), V3(0.2225, 0.5213, 0.2594), axis: 1, hinged: true),
      piece(Shape.box, V3(-1.1030, 0.8341, 0.0000), V3(0.1815, 0.6343, 0.2138), axis: 0, hinged: true),
      piece(Shape.hex, V3(-0.0881, 0.8341, 0.0000), V3(0.2448, 0.5276, 0.2855), axis: 2),
    ],
    solution: Pose(-1.6969, -0.6210, -0.4194),
  ),
  // #179  approach 0.008 · correlation 1.00
  Level(
    name: '179',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2173, 0.5321, 0.2131), axis: 1),
      piece(Shape.hex, V3(0.0000, 0.8514, 0.0000), V3(0.2823, 0.7672, 0.1708), axis: 0, hinged: true),
      piece(Shape.wedge, V3(1.2275, 0.8514, 0.0000), V3(0.1722, 0.8380, 0.1972), axis: 1, hinged: true),
    ],
    solution: Pose(3.0105, -0.6684, -0.4081),
  ),
  // #180  approach 0.004 · correlation 0.17
  Level(
    name: '180',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2211, 0.5563, 0.2612), axis: 1),
      piece(Shape.box, V3(0.0000, 0.8900, 0.0000), V3(0.2038, 0.6053, 0.2959), axis: 2, hinged: true),
    ],
    solution: Pose(2.8443, -0.6839, 0.9119),
  ),
  // #181  approach 0.004 · correlation 1.00
  Level(
    name: '181',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2678, 0.9079, 0.2967), axis: 0),
      piece(Shape.hex, V3(1.4526, 0.0000, 0.0000), V3(0.1940, 0.9015, 0.2306), axis: 1, hinged: true),
    ],
    solution: Pose(2.6642, 0.6366, -0.8930),
  ),
  // #182  approach 0.004 · correlation 1.00
  Level(
    name: '182',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2049, 0.5442, 0.1989), axis: 2),
      piece(Shape.rod, V3(0.0000, 0.0000, 0.8707), V3(0.2494, 0.7605, 0.2562), axis: 1, hinged: true),
    ],
    solution: Pose(0.0629, -0.9200, 0.6875),
  ),
  // #183  approach 0.004 · correlation 1.00
  Level(
    name: '183',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2735, 0.9386, 0.2796), axis: 0),
      piece(Shape.wedge, V3(1.5017, 0.0000, 0.0000), V3(0.2654, 0.8115, 0.2664), axis: 1, hinged: true),
    ],
    solution: Pose(-1.2145, -0.7132, 0.8791),
  ),
  // #184  approach 0.004 · correlation 1.00
  Level(
    name: '184',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.2981, 0.5020, 0.2053), axis: 2),
      piece(Shape.wedge, V3(0.0000, 0.0000, -0.8031), V3(0.2425, 0.8633, 0.2885), axis: 0, hinged: true),
      piece(Shape.hex, V3(-1.3814, 0.0000, -0.8031), V3(0.2855, 0.6698, 0.1770), axis: 1, hinged: true),
    ],
    solution: Pose(-2.2862, -0.7428, 0.3195),
  ),
  // #185  approach 0.004 · correlation 1.00
  Level(
    name: '185',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.2957, 0.6870, 0.2577), axis: 0),
      piece(Shape.rod, V3(-1.0992, 0.0000, 0.0000), V3(0.2936, 0.5705, 0.1729), axis: 2, hinged: true),
      piece(Shape.rod, V3(-1.0992, 0.0000, 0.9129), V3(0.2140, 0.6907, 0.1756), axis: 0, hinged: true),
      piece(Shape.hex, V3(0.0059, 0.0000, 0.9129), V3(0.2076, 0.8875, 0.2579), axis: 1),
    ],
    solution: Pose(2.2069, -0.2382, 0.2436),
  ),
  // #186  approach 0.004 · correlation 1.00
  Level(
    name: '186',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2729, 0.6183, 0.1593), axis: 2),
      piece(Shape.wedge, V3(0.0000, 0.0000, -0.9892), V3(0.1901, 0.5259, 0.2588), axis: 1, hinged: true),
      piece(Shape.rod, V3(0.0000, 0.8415, -0.9892), V3(0.2157, 0.8433, 0.2483), axis: 2, hinged: true),
    ],
    solution: Pose(0.0016, -1.1143, 0.9262),
  ),
  // #187  approach 0.004 · correlation 1.00
  Level(
    name: '187',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.2198, 0.6054, 0.2347), axis: 1),
      piece(Shape.wedge, V3(0.0000, 0.9686, 0.0000), V3(0.1758, 0.7334, 0.1501), axis: 2, hinged: true),
      piece(Shape.hex, V3(0.0000, 0.9686, -1.1735), V3(0.1638, 0.5301, 0.2262), axis: 0, hinged: true),
    ],
    solution: Pose(2.8620, 0.3544, 0.6241),
  ),
  // #188  approach 0.004 · correlation 1.00
  Level(
    name: '188',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.1997, 0.7957, 0.1688), axis: 1),
      piece(Shape.wedge, V3(0.0000, -1.2731, 0.0000), V3(0.2686, 0.7958, 0.1602), axis: 0, hinged: true),
    ],
    solution: Pose(0.3665, 0.3849, 0.9141),
  ),
  // #189  approach 0.004 · correlation 1.00
  Level(
    name: '189',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2149, 0.8143, 0.2056), axis: 1),
      piece(Shape.wedge, V3(0.0000, -1.3029, 0.0000), V3(0.2012, 0.9041, 0.2308), axis: 0, hinged: true),
      piece(Shape.wedge, V3(-1.4466, -1.3029, 0.0000), V3(0.2983, 0.6217, 0.2365), axis: 1, hinged: true),
      piece(Shape.box, V3(-1.4466, -2.2977, 0.0000), V3(0.2354, 0.7283, 0.2040), axis: 2),
    ],
    solution: Pose(2.5213, -0.1060, 0.3796),
  ),
  // #190  approach 0.004 · correlation 0.33
  Level(
    name: '190',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2936, 0.6756, 0.1857), axis: 1),
      piece(Shape.wedge, V3(0.0000, 1.0810, 0.0000), V3(0.2997, 0.7640, 0.2821), axis: 2, hinged: true),
    ],
    solution: Pose(0.5276, -0.8105, -0.1480),
  ),
  // #191  approach 0.004 · correlation 1.00
  Level(
    name: '191',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2813, 0.6587, 0.2894), axis: 0),
      piece(Shape.wedge, V3(-1.0538, 0.0000, 0.0000), V3(0.2056, 0.8819, 0.1683), axis: 2, hinged: true),
    ],
    solution: Pose(-0.2891, -0.8616, 1.0200),
  ),
  // #192  approach 0.004 · correlation 0.50
  Level(
    name: '192',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2785, 0.5430, 0.2737), axis: 2),
      piece(Shape.hex, V3(0.0000, 0.0000, -0.8688), V3(0.2242, 0.8345, 0.1955), axis: 0, hinged: true),
    ],
    solution: Pose(-2.5910, 0.0012, 0.0111),
  ),
  // #193  approach 0.004 · correlation 0.50
  Level(
    name: '193',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2857, 0.6755, 0.1515), axis: 1),
      piece(Shape.rod, V3(0.0000, 1.0808, 0.0000), V3(0.2522, 0.6874, 0.1563), axis: 2, hinged: true),
      piece(Shape.wedge, V3(0.0000, 1.0808, 1.0998), V3(0.2366, 0.8772, 0.1620), axis: 0, hinged: true),
    ],
    solution: Pose(-2.3526, 0.4414, 0.1150),
  ),
  // #194  approach 0.004 · correlation 1.00
  Level(
    name: '194',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2925, 0.6978, 0.2811), axis: 0),
      piece(Shape.hex, V3(-1.1165, 0.0000, 0.0000), V3(0.2950, 0.7083, 0.2317), axis: 2, hinged: true),
    ],
    solution: Pose(-2.2460, -0.5479, -0.9167),
  ),
  // #195  approach 0.004 · correlation 0.50
  Level(
    name: '195',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2615, 0.6202, 0.2601), axis: 1),
      piece(Shape.rod, V3(0.0000, 0.9922, 0.0000), V3(0.2612, 0.6350, 0.2730), axis: 2, hinged: true),
    ],
    solution: Pose(0.9930, -0.6913, -0.5662),
  ),
  // #196  approach 0.004 · correlation 0.50
  Level(
    name: '196',
    hint: 'Two folds, and the parts are no longer alike.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.2772, 0.6178, 0.2983), axis: 1),
      piece(Shape.hex, V3(0.0000, 0.9885, 0.0000), V3(0.2643, 0.6726, 0.1964), axis: 2, hinged: true),
    ],
    solution: Pose(2.1890, -1.0578, 0.2445),
  ),
  // ── TANGLE ────────────────────────────────────────
  // #197  approach 0.008 · correlation 0.40
  Level(
    name: '197',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.tee, V3(0.0000, 0.0000, 0.0000), V3(0.2130, 0.6024, 0.1572), axis: 1),
      piece(Shape.box, V3(0.0000, 0.9639, 0.0000), V3(0.2669, 0.5090, 0.2383), axis: 0, hinged: true),
    ],
    solution: Pose(2.0470, 0.0261, -0.4296),
  ),
  // #198  approach 0.008 · correlation 0.67
  Level(
    name: '198',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1820, 0.7348, 0.2238), axis: 1),
      piece(Shape.tee, V3(0.0000, 1.1757, 0.0000), V3(0.1903, 0.6425, 0.2121), axis: 0, hinged: true),
    ],
    solution: Pose(-0.7368, 0.6481, 0.4193),
  ),
  // #199  approach 0.008 · correlation 0.67
  Level(
    name: '199',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2350, 0.6731, 0.2896), axis: 0),
      piece(Shape.tee, V3(1.0769, 0.0000, 0.0000), V3(0.2876, 0.5542, 0.2005), axis: 1, hinged: true),
      piece(Shape.tee, V3(1.0769, 0.8867, 0.0000), V3(0.2919, 0.6581, 0.2033), axis: 0, hinged: true),
      piece(Shape.box, V3(2.1298, 0.8867, 0.0000), V3(0.2995, 0.7449, 0.2160), axis: 1),
    ],
    solution: Pose(2.4439, 1.1103, 0.9151),
  ),
  // #200  approach 0.008 · correlation 0.50
  Level(
    name: '200',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2011, 0.6756, 0.2015), axis: 1),
      piece(Shape.box, V3(0.0000, -1.0810, 0.0000), V3(0.2276, 0.6381, 0.1957), axis: 0, hinged: true),
    ],
    solution: Pose(-0.5684, -0.1512, 0.2754),
  ),
  // #201  approach 0.004 · correlation 1.00
  Level(
    name: '201',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.ell, V3(0.0000, 0.0000, 0.0000), V3(0.1867, 0.8475, 0.2979), axis: 1),
      piece(Shape.box, V3(0.0000, 1.3560, 0.0000), V3(0.2734, 0.5201, 0.1589), axis: 0, hinged: true),
      piece(Shape.ell, V3(-0.8322, 1.3560, 0.0000), V3(0.2707, 0.7407, 0.2820), axis: 2, hinged: true),
      piece(Shape.ell, V3(-0.8322, 1.3560, 1.1851), V3(0.2466, 0.5824, 0.1573), axis: 1),
    ],
    solution: Pose(-1.7918, 0.5074, 0.1176),
  ),
  // #202  approach 0.004 · correlation 1.00
  Level(
    name: '202',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1806, 0.6068, 0.1993), axis: 1),
      piece(Shape.ell, V3(0.0000, 0.9709, 0.0000), V3(0.1629, 0.6739, 0.1648), axis: 0, hinged: true),
      piece(Shape.tee, V3(-1.0782, 0.9709, 0.0000), V3(0.2714, 0.5663, 0.1685), axis: 2, hinged: true),
      piece(Shape.tee, V3(-1.0782, 0.9709, -0.9062), V3(0.1839, 0.7293, 0.1509), axis: 0),
    ],
    solution: Pose(-0.0851, -0.3305, -0.1178),
  ),
  // #203  approach 0.004 · correlation 1.00
  Level(
    name: '203',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.0000), V3(0.1999, 0.6122, 0.2301), axis: 2),
      piece(Shape.box, V3(0.0000, 0.0000, 0.9795), V3(0.1790, 0.8347, 0.2083), axis: 0, hinged: true),
    ],
    solution: Pose(1.7819, 0.3686, -1.2549),
  ),
  // #204  approach 0.004 · correlation 1.00
  Level(
    name: '204',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.ell, V3(0.0000, 0.0000, 0.0000), V3(0.2988, 0.5360, 0.2089), axis: 2),
      piece(Shape.box, V3(0.0000, 0.0000, -0.8576), V3(0.1950, 0.7255, 0.2032), axis: 0, hinged: true),
    ],
    solution: Pose(2.9909, 0.4039, -1.2603),
  ),
  // #205  approach 0.004 · correlation 1.00
  Level(
    name: '205',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.ell, V3(0.0000, 0.0000, 0.0000), V3(0.2979, 0.5754, 0.2052), axis: 2),
      piece(Shape.tee, V3(0.0000, 0.0000, 0.9206), V3(0.2117, 0.7663, 0.2819), axis: 1, hinged: true),
    ],
    solution: Pose(-0.8210, 0.4357, -1.0785),
  ),
  // #206  approach 0.004 · correlation 1.00
  Level(
    name: '206',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.ell, V3(0.0000, 0.0000, 0.0000), V3(0.1810, 0.7837, 0.2967), axis: 2),
      piece(Shape.chevron, V3(0.0000, 0.0000, -1.2539), V3(0.1779, 0.8984, 0.2766), axis: 0, hinged: true),
    ],
    solution: Pose(-0.4130, 0.5955, 0.9483),
  ),
  // #207  approach 0.004 · correlation 0.25
  Level(
    name: '207',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2766, 0.5468, 0.2191), axis: 0),
      piece(Shape.box, V3(0.8749, 0.0000, 0.0000), V3(0.1610, 0.7338, 0.2736), axis: 1, hinged: true),
    ],
    solution: Pose(1.7632, 0.9356, -0.7397),
  ),
  // #208  approach 0.004 · correlation 1.00
  Level(
    name: '208',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.0000), V3(0.2455, 0.5196, 0.1633), axis: 2),
      piece(Shape.tee, V3(0.0000, 0.0000, 0.8313), V3(0.2790, 0.8167, 0.2966), axis: 1, hinged: true),
      piece(Shape.tee, V3(0.0000, 1.3067, 0.8313), V3(0.2711, 0.6997, 0.2622), axis: 2, hinged: true),
    ],
    solution: Pose(0.1278, -0.0945, 0.5408),
  ),
  // #209  approach 0.004 · correlation 1.00
  Level(
    name: '209',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2426, 0.7363, 0.1850), axis: 2),
      piece(Shape.chevron, V3(0.0000, 0.0000, 1.1781), V3(0.2149, 0.5741, 0.1797), axis: 0, hinged: true),
      piece(Shape.ell, V3(0.9186, 0.0000, 1.1781), V3(0.2096, 0.6343, 0.1922), axis: 2, hinged: true),
    ],
    solution: Pose(-0.3778, -1.0655, -0.5228),
  ),
  // #210  approach 0.004 · correlation 0.50
  Level(
    name: '210',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1807, 0.5332, 0.2716), axis: 1),
      piece(Shape.chevron, V3(0.0000, -0.8532, 0.0000), V3(0.2501, 0.6739, 0.2400), axis: 0, hinged: true),
    ],
    solution: Pose(-2.9206, -0.9066, -0.1506),
  ),
  // #211  approach 0.004 · correlation 1.00
  Level(
    name: '211',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.tee, V3(0.0000, 0.0000, 0.0000), V3(0.2790, 0.5671, 0.1966), axis: 0),
      piece(Shape.tee, V3(0.9074, 0.0000, 0.0000), V3(0.2624, 0.6297, 0.2562), axis: 1, hinged: true),
    ],
    solution: Pose(-2.9400, -0.8301, -0.9127),
  ),
  // #212  approach 0.004 · correlation 1.00
  Level(
    name: '212',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.0000), V3(0.2125, 0.7605, 0.2796), axis: 0),
      piece(Shape.chevron, V3(1.2168, 0.0000, 0.0000), V3(0.1726, 0.5945, 0.2695), axis: 1, hinged: true),
      piece(Shape.ell, V3(1.2168, -0.9512, 0.0000), V3(0.2315, 0.6558, 0.2462), axis: 2, hinged: true),
    ],
    solution: Pose(0.1374, -0.0539, 0.3744),
  ),
  // #213  approach 0.004 · correlation 1.00
  Level(
    name: '213',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.ell, V3(0.0000, 0.0000, 0.0000), V3(0.2883, 0.7722, 0.1716), axis: 1),
      piece(Shape.chevron, V3(0.0000, 1.2355, 0.0000), V3(0.2259, 0.6406, 0.1657), axis: 2, hinged: true),
      piece(Shape.ell, V3(0.0000, 1.2355, -1.0249), V3(0.2954, 0.8585, 0.2667), axis: 1, hinged: true),
    ],
    solution: Pose(-3.1229, 0.8338, -1.1189),
  ),
  // #214  approach 0.004 · correlation 1.00
  Level(
    name: '214',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.0000), V3(0.2260, 0.6600, 0.2403), axis: 0),
      piece(Shape.ell, V3(-1.0560, 0.0000, 0.0000), V3(0.2915, 0.6628, 0.1597), axis: 1, hinged: true),
    ],
    solution: Pose(-0.3524, 1.0626, 0.2624),
  ),
  // #215  approach 0.004 · correlation 1.00
  Level(
    name: '215',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.0000), V3(0.1651, 0.6692, 0.1870), axis: 1),
      piece(Shape.tee, V3(0.0000, -1.0706, 0.0000), V3(0.2939, 0.7272, 0.1716), axis: 2, hinged: true),
    ],
    solution: Pose(0.0059, -0.4121, 0.0722),
  ),
  // #216  approach 0.004 · correlation 1.00
  Level(
    name: '216',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.ell, V3(0.0000, 0.0000, 0.0000), V3(0.2931, 0.5356, 0.2177), axis: 2),
      piece(Shape.chevron, V3(0.0000, 0.0000, -0.8569), V3(0.2591, 0.8363, 0.2670), axis: 0, hinged: true),
    ],
    solution: Pose(2.8196, 0.5172, 0.1648),
  ),
  // #217  approach 0.004 · correlation 1.00
  Level(
    name: '217',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.0000), V3(0.1933, 0.5834, 0.2535), axis: 0),
      piece(Shape.chevron, V3(0.9334, 0.0000, 0.0000), V3(0.2820, 0.7706, 0.2905), axis: 1, hinged: true),
      piece(Shape.box, V3(0.9334, 1.2330, 0.0000), V3(0.2211, 0.7015, 0.1929), axis: 2, hinged: true),
      piece(Shape.box, V3(0.9334, 1.2330, 1.1223), V3(0.2843, 0.9231, 0.2603), axis: 1),
    ],
    solution: Pose(-1.3580, -0.7584, -0.8637),
  ),
  // #218  approach 0.004 · correlation 1.00
  Level(
    name: '218',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.tee, V3(0.0000, 0.0000, 0.0000), V3(0.2084, 0.6349, 0.2496), axis: 0),
      piece(Shape.chevron, V3(-1.0158, 0.0000, 0.0000), V3(0.2365, 0.8104, 0.2555), axis: 2, hinged: true),
    ],
    solution: Pose(-0.4484, -1.0112, 0.9072),
  ),
  // #219  approach 0.004 · correlation 1.00
  Level(
    name: '219',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.ell, V3(0.0000, 0.0000, 0.0000), V3(0.2786, 0.5981, 0.2647), axis: 2),
      piece(Shape.ell, V3(0.0000, 0.0000, 0.9569), V3(0.2753, 0.5593, 0.1918), axis: 0, hinged: true),
      piece(Shape.box, V3(0.8949, 0.0000, 0.9569), V3(0.2298, 0.7963, 0.2094), axis: 1, hinged: true),
      piece(Shape.tee, V3(0.8949, 1.2741, 0.9569), V3(0.2783, 0.6857, 0.2022), axis: 2),
    ],
    solution: Pose(-0.6143, 0.3487, -1.2442),
  ),
  // #220  approach 0.004 · correlation 0.50
  Level(
    name: '220',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2941, 0.6643, 0.2088), axis: 2),
      piece(Shape.box, V3(0.0000, 0.0000, -1.0629), V3(0.2081, 0.8917, 0.2843), axis: 0, hinged: true),
    ],
    solution: Pose(-1.4420, 1.0408, -1.0071),
  ),
  // #221  approach 0.004 · correlation 1.00
  Level(
    name: '221',
    hint: 'Every piece has a bite out of it.',
    boxes: [
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.0000), V3(0.2254, 0.7934, 0.2814), axis: 2),
      piece(Shape.box, V3(0.0000, 0.0000, 1.2694), V3(0.2804, 0.6743, 0.2517), axis: 0, hinged: true),
      piece(Shape.tee, V3(-1.0788, 0.0000, 1.2694), V3(0.2535, 0.5312, 0.2345), axis: 2, hinged: true),
      piece(Shape.box, V3(-1.0788, 0.0000, 0.4195), V3(0.1677, 0.8995, 0.2146), axis: 1),
    ],
    solution: Pose(2.7599, 0.2109, -1.0056),
  ),
  // ── THE WORKS ────────────────────────────────────────
  // #222  approach 0.028 · correlation 0.88
  Level(
    name: '222',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2958, 0.6031, 0.2760), axis: 1),
      piece(Shape.box, V3(0.0000, -0.9650, 0.0000), V3(0.2839, 0.6439, 0.2088), axis: 2, hinged: true),
    ],
    solution: Pose(2.6782, -0.5895, -0.4801),
  ),
  // #223  approach 0.012 · correlation 0.75
  Level(
    name: '223',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.tee, V3(0.0000, 0.0000, 0.0000), V3(0.2443, 0.5331, 0.1614), axis: 0),
      piece(Shape.hex, V3(-0.8530, 0.0000, 0.0000), V3(0.2029, 0.5754, 0.2903), axis: 1, hinged: true),
    ],
    solution: Pose(3.1145, 0.9066, 0.9746),
  ),
  // #224  approach 0.008 · correlation 0.67
  Level(
    name: '224',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2860, 0.7498, 0.2182), axis: 1),
      piece(Shape.box, V3(0.0000, -1.1997, 0.0000), V3(0.2632, 0.8024, 0.2553), axis: 0, hinged: true),
    ],
    solution: Pose(-1.5136, -0.3824, 0.2934),
  ),
  // #225  approach 0.008 · correlation 0.67
  Level(
    name: '225',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2427, 0.5710, 0.2670), axis: 0),
      piece(Shape.box, V3(0.9137, 0.0000, 0.0000), V3(0.2120, 0.6754, 0.2770), axis: 1, hinged: true),
    ],
    solution: Pose(-2.2378, 0.0907, -0.3792),
  ),
  // #226  approach 0.008 · correlation 0.50
  Level(
    name: '226',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.tee, V3(0.0000, 0.0000, 0.0000), V3(0.2917, 0.6465, 0.2165), axis: 1),
      piece(Shape.bulb, V3(0.0000, -1.0344, 0.0000), V3(0.2119, 0.6226, 0.2825), axis: 0, hinged: true),
    ],
    solution: Pose(0.6996, -0.5706, -0.2627),
  ),
  // #227  approach 0.008 · correlation 0.67
  Level(
    name: '227',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2063, 0.5848, 0.2842), axis: 1),
      piece(Shape.rod, V3(0.0000, 0.9357, 0.0000), V3(0.1971, 0.7263, 0.1856), axis: 0, hinged: true),
    ],
    solution: Pose(-0.5938, -0.0562, -1.0287),
  ),
  // #228  approach 0.008 · correlation 1.00
  Level(
    name: '228',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2028, 0.8068, 0.2976), axis: 1),
      piece(Shape.bulb, V3(0.0000, 1.2909, 0.0000), V3(0.2087, 0.8177, 0.2911), axis: 2, hinged: true),
    ],
    solution: Pose(-2.2363, -0.3568, -0.8936),
  ),
  // #229  approach 0.008 · correlation 0.67
  Level(
    name: '229',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1899, 0.5792, 0.1847), axis: 0),
      piece(Shape.wedge, V3(0.9268, 0.0000, 0.0000), V3(0.2696, 0.8675, 0.2829), axis: 2, hinged: true),
    ],
    solution: Pose(2.9598, -0.1751, 0.9739),
  ),
  // #230  approach 0.008 · correlation 1.00
  Level(
    name: '230',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1756, 0.7995, 0.2463), axis: 0),
      piece(Shape.hex, V3(-1.2792, 0.0000, 0.0000), V3(0.1950, 0.5821, 0.2139), axis: 1, hinged: true),
    ],
    solution: Pose(2.4016, 1.0054, 0.2045),
  ),
  // #231  approach 0.008 · correlation 0.50
  Level(
    name: '231',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2874, 0.6322, 0.2765), axis: 1),
      piece(Shape.tee, V3(0.0000, -1.0116, 0.0000), V3(0.2992, 0.9444, 0.1941), axis: 2, hinged: true),
    ],
    solution: Pose(0.0768, 0.9677, 0.4898),
  ),
  // #232  approach 0.008 · correlation 1.00
  Level(
    name: '232',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2436, 0.5041, 0.1845), axis: 2),
      piece(Shape.bulb, V3(0.0000, 0.0000, 0.8066), V3(0.2808, 0.9443, 0.2996), axis: 0, hinged: true),
    ],
    solution: Pose(-2.4673, -1.0726, -1.1051),
  ),
  // #233  approach 0.008 · correlation 1.00
  Level(
    name: '233',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.chevron, V3(0.0000, 0.0000, 0.0000), V3(0.1799, 0.7273, 0.1695), axis: 2),
      piece(Shape.box, V3(0.0000, 0.0000, 1.1636), V3(0.2133, 0.6745, 0.2961), axis: 0, hinged: true),
    ],
    solution: Pose(-0.5529, -0.6123, -1.2926),
  ),
  // #234  approach 0.008 · correlation 1.00
  Level(
    name: '234',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2464, 0.5838, 0.2325), axis: 0),
      piece(Shape.wedge, V3(-0.9341, 0.0000, 0.0000), V3(0.2205, 0.6537, 0.2815), axis: 1, hinged: true),
    ],
    solution: Pose(0.4249, 1.1594, -0.3955),
  ),
  // #235  approach 0.004 · correlation 1.00
  Level(
    name: '235',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2279, 0.6423, 0.2131), axis: 0),
      piece(Shape.hex, V3(1.0277, 0.0000, 0.0000), V3(0.1952, 0.9286, 0.2907), axis: 1, hinged: true),
    ],
    solution: Pose(-2.6462, -0.3313, -1.0791),
  ),
  // #236  approach 0.004 · correlation 1.00
  Level(
    name: '236',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.2621, 0.6649, 0.2006), axis: 0),
      piece(Shape.box, V3(-1.0638, 0.0000, 0.0000), V3(0.2862, 0.8895, 0.2899), axis: 1, hinged: true),
    ],
    solution: Pose(-1.9339, -0.9406, 0.8542),
  ),
  // #237  approach 0.004 · correlation 0.50
  Level(
    name: '237',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1829, 0.6150, 0.1507), axis: 1),
      piece(Shape.bulb, V3(0.0000, 0.9840, 0.0000), V3(0.2376, 0.5978, 0.2771), axis: 0, hinged: true),
    ],
    solution: Pose(1.1074, -0.3265, -0.7653),
  ),
  // #238  approach 0.004 · correlation 1.00
  Level(
    name: '238',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2233, 0.5674, 0.2495), axis: 0),
      piece(Shape.tee, V3(-0.9079, 0.0000, 0.0000), V3(0.1882, 0.7904, 0.2295), axis: 1, hinged: true),
      piece(Shape.bulb, V3(-0.9079, -1.2646, 0.0000), V3(0.2193, 0.6151, 0.2189), axis: 2, hinged: true),
    ],
    solution: Pose(-0.0105, 0.3868, -0.6346),
  ),
  // #239  approach 0.004 · correlation 0.50
  Level(
    name: '239',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2850, 0.6042, 0.2531), axis: 1),
      piece(Shape.box, V3(0.0000, 0.9667, 0.0000), V3(0.2384, 0.6324, 0.1508), axis: 2, hinged: true),
    ],
    solution: Pose(0.8525, -0.8520, -1.0438),
  ),
  // #240  approach 0.004 · correlation 1.00
  Level(
    name: '240',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.hex, V3(0.0000, 0.0000, 0.0000), V3(0.2915, 0.7435, 0.1559), axis: 0),
      piece(Shape.rod, V3(-1.1896, 0.0000, 0.0000), V3(0.1925, 0.6386, 0.2021), axis: 1, hinged: true),
      piece(Shape.bulb, V3(-1.1896, -1.0218, 0.0000), V3(0.2675, 0.5889, 0.2422), axis: 2, hinged: true),
    ],
    solution: Pose(2.8304, -0.6284, 1.0939),
  ),
  // #241  approach 0.004 · correlation 0.50
  Level(
    name: '241',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2590, 0.6188, 0.1928), axis: 0),
      piece(Shape.box, V3(-0.9900, 0.0000, 0.0000), V3(0.1883, 0.8484, 0.1789), axis: 1, hinged: true),
    ],
    solution: Pose(1.7321, -0.8685, 1.0595),
  ),
  // #242  approach 0.004 · correlation 0.50
  Level(
    name: '242',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1962, 0.6717, 0.1908), axis: 2),
      piece(Shape.box, V3(0.0000, 0.0000, -1.0747), V3(0.2280, 0.9242, 0.2946), axis: 1, hinged: true),
    ],
    solution: Pose(-2.9511, 0.8363, 0.9406),
  ),
  // #243  approach 0.004 · correlation 1.00
  Level(
    name: '243',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.rod, V3(0.0000, 0.0000, 0.0000), V3(0.2343, 0.9201, 0.2644), axis: 2),
      piece(Shape.tee, V3(0.0000, 0.0000, -1.4722), V3(0.2489, 0.7200, 0.2030), axis: 0, hinged: true),
      piece(Shape.wedge, V3(1.1521, 0.0000, -1.4722), V3(0.2681, 0.8451, 0.2377), axis: 1, hinged: true),
      piece(Shape.chevron, V3(1.1521, -1.3522, -1.4722), V3(0.2440, 0.8477, 0.1931), axis: 0),
    ],
    solution: Pose(-0.5668, -0.3666, -0.8041),
  ),
  // #244  approach 0.004 · correlation 0.50
  Level(
    name: '244',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.1870, 0.7599, 0.2777), axis: 1),
      piece(Shape.bulb, V3(0.0000, -1.2159, 0.0000), V3(0.1846, 0.8974, 0.2464), axis: 2, hinged: true),
    ],
    solution: Pose(1.1790, -0.2520, 1.0092),
  ),
  // #245  approach 0.004 · correlation 1.00
  Level(
    name: '245',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.wedge, V3(0.0000, 0.0000, 0.0000), V3(0.1823, 0.7702, 0.2809), axis: 1),
      piece(Shape.box, V3(0.0000, 1.2323, 0.0000), V3(0.2154, 0.5784, 0.1547), axis: 0, hinged: true),
    ],
    solution: Pose(-2.0764, 0.7252, 0.6921),
  ),
  // #246  approach 0.004 · correlation 1.00
  Level(
    name: '246',
    hint: 'Everything the room knows how to be.',
    boxes: [
      piece(Shape.box, V3(0.0000, 0.0000, 0.0000), V3(0.2815, 0.5729, 0.2844), axis: 1),
      piece(Shape.rod, V3(0.0000, -0.9167, 0.0000), V3(0.2587, 0.5604, 0.1708), axis: 2, hinged: true),
      piece(Shape.bulb, V3(0.0000, -0.9167, 0.8966), V3(0.2324, 0.5399, 0.1922), axis: 0, hinged: true),
    ],
    solution: Pose(2.1821, -0.3161, 1.0198),
  ),
];
