// GENERATED by tool/gen_levels.dart — do not edit by hand.
//
// Every level here survived rejection sampling: it is not solved
// at the opening pose, its solution basin is narrow enough to be a
// puzzle and wide enough to be findable, and its two walls are
// measurably independent — which is what the hand-authored Tee
// failed. Ordered easiest first within each chapter.
import 'geom.dart';
import 'level.dart';

const generatedLevels = <Level>[
  // #1  approach 0.084 · correlation 1.00
  Level(
    name: '1',
    hint: 'Drag to rotate.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2577, 0.8367, 0.2708)),
      Box(center: V3(0.0000, -1.2550, 0.0000), half: V3(0.1956, 0.8245, 0.2496)),
    ],
    solution: Pose(-0.1240, 0.5741, 0.0000),
  ),
  // #2  approach 0.060 · correlation 1.00
  Level(
    name: '2',
    hint: 'Drag to rotate.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5775, 0.2033, 0.2011)),
      Box(center: V3(0.0000, 0.0000, -0.3017), half: V3(0.5297, 0.2467, 0.2191)),
      Box(center: V3(0.0000, 0.0000, 0.0269), half: V3(0.2804, 0.2850, 0.8143)),
      Box(center: V3(0.0000, 0.4275, 0.0269), half: V3(0.8676, 0.2792, 0.2656)),
    ],
    solution: Pose(-0.1054, -0.1313, 0.0000),
  ),
  // #3  approach 0.052 · correlation 0.62
  Level(
    name: '3',
    hint: 'Drag to rotate.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2641, 0.7977, 0.2858)),
      Box(center: V3(0.3962, 0.0000, 0.0000), half: V3(0.2476, 0.6412, 0.2187)),
    ],
    solution: Pose(1.4846, 0.4331, 0.0000),
  ),
  // #4  approach 0.032 · correlation 0.73
  Level(
    name: '4',
    hint: 'Drag to rotate.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2668, 0.6008, 0.2527)),
      Box(center: V3(-0.4002, 0.0000, 0.0000), half: V3(0.1629, 0.8914, 0.1726)),
    ],
    solution: Pose(-2.9892, 0.4389, 0.0000),
  ),
  // #5  approach 0.028 · correlation 0.88
  Level(
    name: '5',
    hint: 'Drag to rotate.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1825, 0.5425, 0.2768)),
      Box(center: V3(0.2737, 0.0000, 0.0000), half: V3(0.7446, 0.2620, 0.1795)),
      Box(center: V3(0.2737, -0.3930, 0.0000), half: V3(0.2987, 0.7701, 0.2864)),
      Box(center: V3(0.2737, -0.3930, -0.4296), half: V3(0.2949, 0.8435, 0.2539)),
    ],
    solution: Pose(1.3983, -0.3340, 0.0000),
  ),
  // #6  approach 0.024 · correlation 0.33
  Level(
    name: '6',
    hint: 'Drag to rotate.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5862, 0.2901, 0.2186)),
      Box(center: V3(0.0000, 0.0000, -0.3280), half: V3(0.3000, 0.8542, 0.2045)),
    ],
    solution: Pose(-1.1370, -0.1968, 0.0000),
  ),
  // #7  approach 0.024 · correlation 0.55
  Level(
    name: '7',
    hint: 'Drag to rotate.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2757, 0.5784, 0.2444)),
      Box(center: V3(0.0000, 0.0000, 0.3666), half: V3(0.2635, 0.8938, 0.2843)),
    ],
    solution: Pose(3.0192, 0.7985, 0.0000),
  ),
  // #8  approach 0.020 · correlation 1.00
  Level(
    name: '8',
    hint: 'Drag to rotate.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2825, 0.8301, 0.2937)),
      Box(center: V3(0.4237, 0.0000, 0.0000), half: V3(0.6902, 0.2002, 0.2990)),
      Box(center: V3(0.4237, 0.0000, -0.4485), half: V3(0.1769, 0.8812, 0.2546)),
    ],
    solution: Pose(2.5407, 0.4928, 0.0000),
  ),
  // #9  approach 0.016 · correlation 0.29
  Level(
    name: '9',
    hint: 'Drag to rotate.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2281, 0.5900, 0.1938)),
      Box(center: V3(0.3421, 0.0000, 0.0000), half: V3(0.2751, 0.8543, 0.2176)),
    ],
    solution: Pose(-0.6705, 0.6942, 0.0000),
  ),
  // #10  approach 0.008 · correlation 1.00
  Level(
    name: '10',
    hint: 'Drag to rotate.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1775, 0.7171, 0.1861)),
      Box(center: V3(-0.2662, 0.0000, 0.0000), half: V3(0.2371, 0.2577, 0.9230)),
      Box(center: V3(-0.2662, 0.0000, 1.3845), half: V3(0.6043, 0.2978, 0.1716)),
    ],
    solution: Pose(1.7507, 0.8138, 0.0000),
  ),
  // #11  approach 0.004 · correlation 0.25
  Level(
    name: '11',
    hint: 'Drag to rotate.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5139, 0.2469, 0.2471)),
      Box(center: V3(0.7708, 0.0000, 0.0000), half: V3(0.2261, 0.1763, 0.7473)),
      Box(center: V3(0.7708, -0.2644, 0.0000), half: V3(0.5134, 0.1705, 0.2476)),
      Box(center: V3(0.7708, -0.0087, 0.0000), half: V3(0.7287, 0.2296, 0.2158)),
    ],
    solution: Pose(-0.4216, -1.1896, 0.0000),
  ),
  // #12  approach 0.004 · correlation 0.33
  Level(
    name: '12',
    hint: 'Drag to rotate.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2918, 0.2982, 0.7373)),
      Box(center: V3(0.0000, 0.0000, 1.1060), half: V3(0.2011, 0.5267, 0.2120)),
    ],
    solution: Pose(-0.2840, -1.0078, 0.0000),
  ),
  // #13  approach 0.064 · correlation 0.84
  Level(
    name: '13',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2785, 0.8054, 0.2961)),
      Box(center: V3(-0.4178, 0.0000, 0.0000), half: V3(0.5666, 0.2207, 0.2481), hinged: true),
      Box(center: V3(-0.4178, 0.0000, -0.3721), half: V3(0.1612, 0.8652, 0.1987)),
    ],
    solution: Pose(0.9491, 0.9095, 0.7903),
  ),
  // #14  approach 0.040 · correlation 0.50
  Level(
    name: '14',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.5986, 0.2612, 0.2449)),
      Box(center: V3(0.8979, 0.0000, 0.0000), half: V3(0.7954, 0.2543, 0.1622), hinged: true),
    ],
    solution: Pose(-3.0734, -0.4637, 0.0779),
  ),
  // #15  approach 0.036 · correlation 0.28
  Level(
    name: '15',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1705, 0.5295, 0.2814)),
      Box(center: V3(-0.2558, 0.0000, 0.0000), half: V3(0.1810, 0.5449, 0.2765), hinged: true),
    ],
    solution: Pose(2.3522, -0.5646, -1.0536),
  ),
  // #16  approach 0.028 · correlation 0.54
  Level(
    name: '16',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2820, 0.2656, 0.9221)),
      Box(center: V3(0.0000, 0.3984, 0.0000), half: V3(0.7203, 0.2763, 0.2961), hinged: true),
    ],
    solution: Pose(1.0037, -0.8195, -0.5400),
  ),
  // #17  approach 0.024 · correlation 1.00
  Level(
    name: '17',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8016, 0.2718, 0.2234)),
      Box(center: V3(0.0000, -0.4078, 0.0000), half: V3(0.2671, 0.5713, 0.2734), hinged: true),
    ],
    solution: Pose(3.1006, -1.1028, 0.1178),
  ),
  // #18  approach 0.020 · correlation 1.00
  Level(
    name: '18',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2624, 0.7368, 0.2651)),
      Box(center: V3(0.3937, 0.0000, 0.0000), half: V3(0.8777, 0.2790, 0.2365), hinged: true),
      Box(center: V3(0.3937, 0.0000, -0.3548), half: V3(0.2365, 0.2130, 0.9283)),
    ],
    solution: Pose(1.5120, 0.5257, -1.1390),
  ),
  // #19  approach 0.016 · correlation 0.36
  Level(
    name: '19',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2450, 0.6018, 0.1875)),
      Box(center: V3(-0.3675, 0.0000, 0.0000), half: V3(0.5126, 0.2829, 0.2452), hinged: true),
      Box(center: V3(-0.3675, 0.4243, 0.0000), half: V3(0.2857, 0.2516, 0.7102)),
      Box(center: V3(-0.7961, 0.4243, 0.0000), half: V3(0.5564, 0.2244, 0.2182)),
    ],
    solution: Pose(0.5767, 0.9826, -0.0198),
  ),
  // #20  approach 0.012 · correlation 0.75
  Level(
    name: '20',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1637, 0.2293, 0.5167)),
      Box(center: V3(0.2455, 0.0000, 0.0000), half: V3(0.2261, 0.6230, 0.1604), hinged: true),
    ],
    solution: Pose(0.0789, -1.1202, 0.1351),
  ),
  // #21  approach 0.008 · correlation 0.29
  Level(
    name: '21',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.8837, 0.2510, 0.1932)),
      Box(center: V3(0.0000, 0.0000, -0.2898), half: V3(0.8176, 0.1614, 0.2756), hinged: true),
      Box(center: V3(0.0000, 0.2421, -0.2898), half: V3(0.9471, 0.2416, 0.2650)),
      Box(center: V3(0.0000, 0.6044, -0.2898), half: V3(0.2707, 0.8086, 0.2480)),
    ],
    solution: Pose(-2.1474, 0.4439, -1.1873),
  ),
  // #22  approach 0.004 · correlation 0.17
  Level(
    name: '22',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2968, 0.2135, 0.8419)),
      Box(center: V3(0.0000, 0.3202, 0.0000), half: V3(0.9399, 0.2541, 0.2531), hinged: true),
      Box(center: V3(0.0000, -0.0610, 0.0000), half: V3(0.5131, 0.2509, 0.2235)),
    ],
    solution: Pose(-1.9167, -0.9470, 1.1955),
  ),
  // #23  approach 0.004 · correlation 0.50
  Level(
    name: '23',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7503, 0.1895, 0.2889)),
      Box(center: V3(1.1255, 0.0000, 0.0000), half: V3(0.6082, 0.1832, 0.1709), hinged: true),
    ],
    solution: Pose(0.5780, 0.5032, 0.3808),
  ),
  // #24  approach 0.004 · correlation 0.50
  Level(
    name: '24',
    hint: 'One arm folds.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1695, 0.7489, 0.2140)),
      Box(center: V3(0.0000, 0.0000, 0.3210), half: V3(0.2556, 0.2615, 0.6412), hinged: true),
      Box(center: V3(0.3834, 0.0000, 0.3210), half: V3(0.6222, 0.2290, 0.1807)),
    ],
    solution: Pose(-1.6565, 0.6702, -0.1593),
  ),
  // #25  approach 0.048 · correlation 0.86
  Level(
    name: '25',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2172, 0.6627, 0.2543)),
      Box(center: V3(0.0000, 0.9940, 0.0000), half: V3(0.2226, 0.1625, 0.5554), hinged: true),
    ],
    solution: Pose(-2.6703, -0.0047, -0.0738),
  ),
  // #26  approach 0.048 · correlation 0.71
  Level(
    name: '26',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.1607, 0.2929, 0.7652)),
      Box(center: V3(0.2410, 0.0000, 0.0000), half: V3(0.7366, 0.2516, 0.2092), hinged: true),
    ],
    solution: Pose(-2.0576, -0.0475, 1.1964),
  ),
  // #27  approach 0.044 · correlation 0.34
  Level(
    name: '27',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2194, 0.6838, 0.1743)),
      Box(center: V3(-0.3291, 0.0000, 0.0000), half: V3(0.1794, 0.2916, 0.7018), hinged: true),
      Box(center: V3(-0.0600, 0.0000, 0.0000), half: V3(0.2797, 0.2886, 0.7430), hinged: true),
    ],
    solution: Pose(0.4508, -0.9508, -1.0708),
  ),
  // #28  approach 0.020 · correlation 1.00
  Level(
    name: '28',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2583, 0.2451, 0.8069)),
      Box(center: V3(0.3875, 0.0000, 0.0000), half: V3(0.5245, 0.2370, 0.2902), hinged: true),
      Box(center: V3(0.3875, 0.0000, -0.4354), half: V3(0.5605, 0.2773, 0.2248), hinged: true),
      Box(center: V3(0.3875, 0.4159, -0.4354), half: V3(0.1643, 0.2813, 0.8140)),
    ],
    solution: Pose(-1.5873, 0.0947, 0.6480),
  ),
  // #29  approach 0.012 · correlation 0.60
  Level(
    name: '29',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2669, 0.5922, 0.2277)),
      Box(center: V3(-0.4003, 0.0000, 0.0000), half: V3(0.2871, 0.2238, 0.6432), hinged: true),
    ],
    solution: Pose(3.0461, 0.0800, -0.1306),
  ),
  // #30  approach 0.012 · correlation 1.00
  Level(
    name: '30',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2146, 0.6427, 0.1615)),
      Box(center: V3(0.0000, 0.0000, 0.2422), half: V3(0.7601, 0.2742, 0.2108), hinged: true),
      Box(center: V3(0.0000, 0.4113, 0.2422), half: V3(0.2160, 0.6023, 0.2269), hinged: true),
      Box(center: V3(0.3239, 0.4113, 0.2422), half: V3(0.2748, 0.5242, 0.1829)),
    ],
    solution: Pose(-0.0834, -1.0010, 0.3285),
  ),
  // #31  approach 0.012 · correlation 0.75
  Level(
    name: '31',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2956, 0.1948, 0.5131)),
      Box(center: V3(0.0000, 0.0000, -0.7696), half: V3(0.2443, 0.8775, 0.2055), hinged: true),
      Box(center: V3(0.0000, 0.0000, -1.0778), half: V3(0.2558, 0.7075, 0.1916), hinged: true),
    ],
    solution: Pose(1.1036, -0.9366, 0.1336),
  ),
  // #32  approach 0.012 · correlation 0.75
  Level(
    name: '32',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2878, 0.2380, 0.6251)),
      Box(center: V3(0.4317, 0.0000, 0.0000), half: V3(0.2936, 0.1982, 0.7665), hinged: true),
    ],
    solution: Pose(2.2779, -0.0893, 1.1789),
  ),
  // #33  approach 0.012 · correlation 0.60
  Level(
    name: '33',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2354, 0.5574, 0.2149)),
      Box(center: V3(0.3531, 0.0000, 0.0000), half: V3(0.2266, 0.9182, 0.2587), hinged: true),
      Box(center: V3(0.0133, 0.0000, 0.0000), half: V3(0.8202, 0.2950, 0.2788), hinged: true),
    ],
    solution: Pose(-0.1999, 0.8524, 0.6579),
  ),
  // #34  approach 0.008 · correlation 0.50
  Level(
    name: '34',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.7833, 0.2056, 0.1855)),
      Box(center: V3(0.0000, 0.0000, -0.2783), half: V3(0.2161, 0.7400, 0.1959), hinged: true),
    ],
    solution: Pose(2.3768, -1.1787, 0.0912),
  ),
  // #35  approach 0.004 · correlation 0.50
  Level(
    name: '35',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.2144, 0.5658, 0.2415)),
      Box(center: V3(0.0000, -0.8487, 0.0000), half: V3(0.2350, 0.2687, 0.5910), hinged: true),
      Box(center: V3(0.0000, -1.2518, 0.0000), half: V3(0.2650, 0.1762, 0.6732), hinged: true),
    ],
    solution: Pose(-1.6004, -0.9940, 0.1954),
  ),
  // #36  approach 0.004 · correlation 0.25
  Level(
    name: '36',
    hint: 'Two arms fold.',
    boxes: [
      Box(center: V3(0.0000, 0.0000, 0.0000), half: V3(0.9342, 0.1689, 0.2708)),
      Box(center: V3(0.0000, 0.2533, 0.0000), half: V3(0.6660, 0.2789, 0.2574), hinged: true),
      Box(center: V3(-0.9989, 0.2533, 0.0000), half: V3(0.8487, 0.2930, 0.2239), hinged: true),
    ],
    solution: Pose(3.1036, 0.4880, 1.1360),
  ),
];
