// Generates lib/dailies.g.dart — the daily room pool.
//
// Run: dart run tool/gen_dailies.dart
//
// Why a baked pool rather than generating from the date at runtime:
// "everyone gets the same room today" is the entire point, and it only holds
// if the level is bit-identical on every device. Runtime generation would lean
// on dart:math Random producing the same stream on every platform and AOT
// target, which is not a promise the SDK makes. Baking the pool makes the
// guarantee structural instead of hopeful, and costs nothing at startup.
//
// The pool wraps. At [_perBand] × 3 days it starts over, which is honest and
// far enough out to not be a launch problem — extend the bands when it nears.

import 'dart:io';

import 'package:in_two_lights/generator.dart';
import 'package:in_two_lights/geom.dart';

const _perBand = 60;

/// Seeds are deliberately different from tool/gen_levels.dart, so a daily is
/// never a campaign level the player has already solved.
const _bands = [
  (seed: 7711, hinges: 0, hint: 'Both walls, one pose.'),
  (seed: 8822, hinges: 1, hint: 'One arm folds.'),
  (seed: 9933, hinges: 2, hint: 'Two arms fold.'),
];

String _v3(V3 v) => 'V3(${_d(v.x)}, ${_d(v.y)}, ${_d(v.z)})';
String _d(double x) => x.toStringAsFixed(4);

void main() {
  final sw = Stopwatch()..start();
  final bands = <List<Generated>>[];
  final hints = <String>[];

  for (final b in _bands) {
    stdout.writeln('daily band (${b.hinges} hinge) — sampling…');
    final kept = generateChapter(
      seed: b.seed,
      wanted: _perBand,
      hinges: b.hinges,
      maxTries: 40000,
    );
    stdout.writeln('  kept ${kept.length}/$_perBand in ${sw.elapsed.inSeconds}s');
    bands.add(kept);
    hints.add(b.hint);
  }

  // Round-robin the bands rather than concatenating them. generateChapter
  // returns easiest-first, which is right for a campaign and wrong for a
  // daily: nobody should get a fortnight of easy rooms followed by a fortnight
  // of hard ones. Interleaving means consecutive days differ in shape and
  // difficulty wanders instead of ramping.
  final order = <(Generated, String)>[];
  final depth = bands.map((b) => b.length).reduce((a, b) => a > b ? a : b);
  for (var i = 0; i < depth; i++) {
    for (var b = 0; b < bands.length; b++) {
      if (i < bands[b].length) order.add((bands[b][i], hints[b]));
    }
  }

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_dailies.dart — do not edit by hand.')
    ..writeln('//')
    ..writeln('// The daily room pool. Same rejection sampling as the campaign,')
    ..writeln('// different seeds so a daily is never a level already played,')
    ..writeln('// and interleaved across hinge counts so difficulty wanders')
    ..writeln('// rather than ramps. Indexed by date — see lib/daily.dart.')
    ..writeln("import 'geom.dart';")
    ..writeln("import 'level.dart';")
    ..writeln()
    ..writeln('const dailyLevels = <Level>[');

  var n = 0;
  for (final (g, hint) in order) {
    n++;
    out
      ..writeln('  // day $n  ·  approach ${g.metrics.approach.toStringAsFixed(3)}')
      ..writeln('  Level(')
      ..writeln("    name: 'day $n',")
      ..writeln("    hint: '$hint',")
      ..writeln('    boxes: [');
    for (final b in g.level.boxes) {
      out.writeln('      Box(center: ${_v3(b.center)}, '
          'half: ${_v3(b.half)}'
          '${b.hinged ? ', hinged: true' : ''}),');
    }
    out
      ..writeln('    ],')
      ..writeln('    solution: Pose(${_d(g.level.solution.yaw)}, '
          '${_d(g.level.solution.pitch)}, '
          '${_d(g.level.solution.hinge)}),')
      ..writeln('  ),');
  }
  out.writeln('];');

  File('lib/dailies.g.dart').writeAsStringSync(out.toString());
  stdout.writeln('wrote lib/dailies.g.dart — $n days in ${sw.elapsed.inSeconds}s');
}
