// Offline level generator. Run by hand, commit the output:
//
//   dart run tool/gen_levels.dart
//
// This is not build_runner and there is no watch mode — the repo's "no codegen"
// rule is about generators in the hot path. This one runs on a desktop, pays
// the expensive curation cost once, and emits a plain readable Dart file.
import 'dart:io';

import 'package:in_two_lights/generator.dart';
import 'package:in_two_lights/geom.dart';

const _chapters = [
  (seed: 1101, wanted: 12, hinges: 0, hint: 'Drag to rotate.'),
  (seed: 2202, wanted: 12, hinges: 1, hint: 'One arm folds.'),
  (seed: 3303, wanted: 12, hinges: 2, hint: 'Two arms fold.'),
];

String _v3(V3 v) => 'V3(${_d(v.x)}, ${_d(v.y)}, ${_d(v.z)})';
String _d(double x) => x.toStringAsFixed(4);

void main() {
  final sw = Stopwatch()..start();
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_levels.dart — do not edit by hand.')
    ..writeln('//')
    ..writeln('// Every level here survived rejection sampling: it is not solved')
    ..writeln('// at the opening pose, its solution basin is narrow enough to be a')
    ..writeln('// puzzle and wide enough to be findable, and its two walls are')
    ..writeln('// measurably independent — which is what the hand-authored Tee')
    ..writeln('// failed. Ordered easiest first within each chapter.')
    ..writeln("import 'geom.dart';")
    ..writeln("import 'level.dart';")
    ..writeln()
    ..writeln('const generatedLevels = <Level>[');

  var n = 0;
  for (final c in _chapters) {
    stdout.writeln('chapter (${c.hinges} hinge) — sampling…');
    final kept = generateChapter(
      seed: c.seed,
      wanted: c.wanted,
      hinges: c.hinges,
    );
    stdout.writeln('  kept ${kept.length}/${c.wanted} in ${sw.elapsed.inSeconds}s');

    for (final g in kept) {
      n++;
      final approach = g.metrics.approach.toStringAsFixed(3);
      final corr = g.metrics.correlation.toStringAsFixed(2);
      out
        ..writeln('  // #$n  approach $approach · correlation $corr')
        ..writeln('  Level(')
        ..writeln("    name: '$n',")
        ..writeln("    hint: '${c.hint}',")
        ..writeln('    boxes: [');
      for (final b in g.level.boxes) {
        out.writeln('      Box(center: ${_v3(b.center)}, '
            'half: ${_v3(b.half)}'
            '${b.hinged ? ', hinged: true' : ''}),');
      }
      out
        ..writeln('    ],')
        ..writeln('    solution: Pose(${_d(g.level.solution.yaw)}, '
            '${_d(g.level.solution.pitch)}, '
            '${_d(g.level.solution.hinge)}),')
        ..writeln('  ),');
    }
  }

  out.writeln('];');
  File('lib/levels.g.dart').writeAsStringSync(out.toString());
  stdout.writeln('wrote lib/levels.g.dart — $n levels in ${sw.elapsed.inSeconds}s');
}
