// Offline generator for the mixed-shape chapters. Run by hand, commit output:
//
//   dart run tool/gen_levels_ext.dart
//
// Deliberately a second tool rather than more chapters inside
// `gen_levels.dart`. That one owns `lib/levels.g.dart`, whose 36 rooms sit at
// campaign indices 3–14, 16–30 and 31–39 — regenerating them with any drift at
// all would move stars onto different puzzles. Keeping the two apart means the
// original file is never rewritten to add a level to the end of the game.
//
// ⚠️ APPEND ONLY. `allLevels` order is the save format (see forms.dart). New
// chapters go on the end; inserting one shifts every star after it and needs
// `Progress.campaignKey` bumped, which throws away everyone's progress.
import 'dart:io';

import 'package:in_two_lights/generator.dart';
import 'package:in_two_lights/geom.dart';

/// Eight chapters of 25. Each is named for the shape family it is actually cut
/// from — the pool is restricted rather than the name being decorative, so a
/// regeneration cannot quietly make the titles lie.
///
/// Joint count rises 0 → 1 → 2 across the eight, which is the same progression
/// chapters I–III use, replayed over a vocabulary the player has not seen.
const _chapters = [
  (
    seed: 4404, wanted: 25, hinges: 0, name: 'THE ROD',
    pool: [Shape.box, Shape.rod, Shape.rod],
    hint: 'Round from every side but one.',
  ),
  (
    seed: 5505, wanted: 25, hinges: 0, name: 'THE WEDGE',
    pool: [Shape.box, Shape.wedge, Shape.wedge, Shape.hex],
    hint: 'A triangle here is a rectangle there.',
  ),
  (
    seed: 6606, wanted: 25, hinges: 1, name: 'THE BULB',
    pool: [Shape.box, Shape.bulb, Shape.bulb, Shape.rod],
    hint: 'No straight edge to line up. Use the width.',
  ),
  (
    seed: 7707, wanted: 25, hinges: 1, name: 'THE ANGLE',
    pool: [Shape.box, Shape.ell, Shape.ell, Shape.tee],
    hint: 'The notch has to land somewhere.',
  ),
  (
    seed: 8808, wanted: 25, hinges: 1, name: 'THE ARROW',
    pool: [Shape.box, Shape.chevron, Shape.chevron, Shape.wedge],
    hint: 'Both shadows point. Rarely the same way.',
  ),
  (
    seed: 9909, wanted: 25, hinges: 2, name: 'ASSEMBLY',
    pool: [Shape.box, Shape.rod, Shape.wedge, Shape.hex],
    hint: 'Two folds, and the parts are no longer alike.',
  ),
  (
    seed: 1010, wanted: 25, hinges: 2, name: 'TANGLE',
    pool: [Shape.box, Shape.ell, Shape.tee, Shape.chevron],
    hint: 'Every piece has a bite out of it.',
  ),
  (
    seed: 1111, wanted: 25, hinges: 2, name: 'THE WORKS',
    pool: kAllShapes,
    hint: 'Everything the room knows how to be.',
  ),
];

String _v3(V3 v) => 'V3(${_d(v.x)}, ${_d(v.y)}, ${_d(v.z)})';
String _d(double x) => x.toStringAsFixed(4);

void main() {
  final sw = Stopwatch()..start();
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_levels_ext.dart — do not edit by hand.')
    ..writeln('//')
    ..writeln('// The mixed-shape chapters. Same rejection sampling as')
    ..writeln('// levels.g.dart — not solved at the opening pose, basin narrow')
    ..writeln('// enough to be a puzzle and wide enough to be findable — but cut')
    ..writeln('// from rods, wedges, bulbs, hexes and the three concave shapes')
    ..writeln('// rather than boxes alone. Ordered easiest first within each')
    ..writeln('// chapter, on the same `approach` metric.')
    ..writeln('//')
    ..writeln('// Pieces are emitted as recipes, not vertices: one lathe is ~90')
    ..writeln('// points and baking them would make this file a megabyte of')
    ..writeln('// source nobody can read or diff. `piece()` rebuilds them.')
    ..writeln('//')
    ..writeln('// ⚠️ APPEND ONLY — this list is the tail of the save format.')
    ..writeln("import 'generator.dart';")
    ..writeln("import 'geom.dart';")
    ..writeln("import 'level.dart';")
    ..writeln()
    ..writeln('final extendedLevels = <Level>[');

  var n = 47; // continues after the 47 authored + generated campaign rooms
  var chapterSizes = <int>[];

  for (final c in _chapters) {
    stdout.writeln('${c.name} (${c.hinges} hinge, ${c.pool.length}-shape pool) — sampling…');
    final kept = generateChapter(
      seed: c.seed,
      wanted: c.wanted,
      hinges: c.hinges,
      mixed: true,
      pool: c.pool,
      // Mixed rooms are rejected more often than box chains — a lathe pair
      // solves from too many poses, a chevron pair from almost none — so the
      // budget is larger than gen_levels.dart's.
      maxTries: 40000,
    );
    stdout.writeln('  kept ${kept.length}/${c.wanted} at ${sw.elapsed.inSeconds}s');
    if (kept.length < c.wanted) {
      stderr.writeln('  ⚠️ SHORT by ${c.wanted - kept.length} — raise maxTries '
          'or widen the pool for ${c.name}');
    }
    chapterSizes.add(kept.length);

    out.writeln('  // ── ${c.name} ${'─' * 40}');
    for (final g in kept) {
      final approach = g.metrics.approach.toStringAsFixed(3);
      final corr = g.metrics.correlation.toStringAsFixed(2);
      out
        ..writeln('  // #$n  approach $approach · correlation $corr')
        ..writeln('  Level(')
        ..writeln("    name: '$n',")
        ..writeln("    hint: '${c.hint}',")
        ..writeln('    boxes: [');
      for (final s in g.specs!) {
        out.writeln('      piece(${s.shape}, ${_v3(s.at)}, ${_v3(s.size)}, '
            'axis: ${s.axis}${s.hinged ? ', hinged: true' : ''}),');
      }
      out
        ..writeln('    ],')
        ..writeln('    solution: Pose(${_d(g.level.solution.yaw)}, '
            '${_d(g.level.solution.pitch)}, '
            '${_d(g.level.solution.hinge)}),')
        ..writeln('  ),');
      n++;
    }
  }

  out.writeln('];');
  File('lib/levels_ext.g.dart').writeAsStringSync(out.toString());

  // The chapter table in progress.dart has to agree with what was actually
  // kept. Printing it here beats hand-counting a 200-level file.
  var at = 47;
  final starts = <int>[];
  for (final s in chapterSizes) {
    starts.add(at);
    at += s;
  }
  stdout
    ..writeln('wrote lib/levels_ext.g.dart — ${n - 47} levels '
        'in ${sw.elapsed.inSeconds}s')
    ..writeln('')
    ..writeln('paste into progress.dart:')
    ..writeln('  chapterStarts += ${starts.join(', ')}')
    ..writeln('  chapterNames  += ${_chapters.map((c) => "'${c.name}'").join(', ')}')
    ..writeln('  total levels   = $n');
}
